// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F03-momentum/D07-F03-A24-know-sure-thing-kst/implementations/typescript/know_sure_thing_kst.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F03-A24: Know Sure Thing (KST). */
import { knowSureThingKst as nativeKnowSureThingKst, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F03-A24";
export const TITLE = "Know Sure Thing (KST)";

export function knowSureThingKst(input: TopicInput): TopicResult {
  return nativeKnowSureThingKst(input);
}
