/**
 * Know Sure Thing (KST)
 *
 * Topic D07-F03-A24 · Technical Indicators / Momentum · difficulty 2
 * Shape: series-transform · entry: knowSureThingKst()
 * Article: https://thefintechbuilder.com/technical-indicators/momentum/know-sure-thing-kst/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F03-A24-know-sure-thing-kst
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { knowSureThingKst as run } from "./impl.ts";

export const meta = {
  id: "D07-F03-A24",
  title: "Know Sure Thing (KST)",
  slug: "know-sure-thing-kst",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F03",
  family: "Momentum",
  difficulty: 2,
  archetype: "series-transform",
  entry: "knowSureThingKst",
  path: "technical-indicators/momentum/know-sure-thing-kst",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/momentum/know-sure-thing-kst/",
  repoUrl: null,
} as const;
