/**
 * Hilbert Transform SineWave
 *
 * Topic D09-F06-A04 · Statistical Time Series / Hilbert and Ehlers Cycle Analytics · difficulty 2
 * Shape: record-transform · entry: hilbertTransformSinewave()
 * Article: https://thefintechbuilder.com/statistical-time-series/hilbert-and-ehlers-cycle-analytics/hilbert-transform-sinewave/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D09-F06-A04-hilbert-transform-sinewave
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { hilbertTransformSinewave as run } from "./impl.ts";

export const meta = {
  id: "D09-F06-A04",
  title: "Hilbert Transform SineWave",
  slug: "hilbert-transform-sinewave",
  domainId: "D09",
  domain: "Statistical Time Series",
  familyId: "D09-F06",
  family: "Hilbert and Ehlers Cycle Analytics",
  difficulty: 2,
  archetype: "record-transform",
  entry: "hilbertTransformSinewave",
  path: "statistical-time-series/hilbert-and-ehlers-cycle-analytics/hilbert-transform-sinewave",
  articleUrl: "https://thefintechbuilder.com/statistical-time-series/hilbert-and-ehlers-cycle-analytics/hilbert-transform-sinewave/",
  repoUrl: null,
} as const;
