// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D10-volatility-and-covariance/D10-F03-conditional-volatility/D10-F03-A06-har-rv/implementations/typescript/har_rv.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Standalone D10-F03-A06 reference. Generated from validated D10 v2 source. */
export class ContractError extends Error {}
type RecordValue=Record<string, any>;
type Matrix=number[][];
const sum=(x:number[]):number=>x.reduce((a,b)=>a+b,0);


function requireValue(ok: unknown, code: string, message: string): asserts ok {
  if (!ok) throw new ContractError(`${code}: ${message}`);
}

function finite(x: unknown, name: string): number {
  requireValue(typeof x === 'number' && Number.isFinite(x), 'NUMBER', `${name} must be a finite number`);
  return x;
}

function param(p: RecordValue, key: string, fallback: number): number {
  return finite(Object.hasOwn(p, key) ? p[key] : fallback, key);
}

function vector(value: unknown, name: string, minimum = 1): number[] {
  requireValue(Array.isArray(value) && value.length >= minimum, 'SHAPE', `${name} needs ${minimum} or more values`);
  return value.map((v, i) => finite(v, `${name}[${i}]`));
}

function seriesResult(series: (RecordValue | null)[], diagnostics: RecordValue): RecordValue {
  const at = series.findIndex(v => v !== null);
  return {series, latest: series.at(-1) ?? null, ready: series.length > 0 && series.at(-1) !== null,
    ready_at: at < 0 ? null : at, diagnostics};
}

function har(data: RecordValue, p: RecordValue): RecordValue {
  const rv = vector(data.realized_variance, 'realized_variance');
  requireValue(Math.min(...rv) >= 0, 'RANGE', 'realized_variance must be nonnegative');
  const b0 = param(p, 'beta0', 0), bd = param(p, 'beta_daily', .45), bw = param(p, 'beta_weekly', .35), bm = param(p, 'beta_monthly', .15);
  const series = rv.map((daily, i) => {
    if (i < 21) return null;
    const weekly = sum(rv.slice(i - 4, i + 1)) / 5, monthly = sum(rv.slice(i - 21, i + 1)) / 22;
    const terms = [b0, bd * daily, bw * weekly, bm * monthly], raw = sum(terms);
    return {index: i, forecast_index: i + 1, forecast_raw: raw, forecast: raw >= 0 ? raw : null, valid: raw >= 0, daily, weekly, monthly, contributions: terms, baseline: daily};
  });
  return seriesResult(series, {causal: true, input_count: rv.length, fitted_parameters: false});
}
export function calculate(data: RecordValue): RecordValue {
  requireValue(data && typeof data === 'object' && !Array.isArray(data),'SHAPE','input must be an object');
  const p=Object.hasOwn(data,'parameters')?data.parameters:{};
  requireValue(p && typeof p === 'object' && !Array.isArray(p),'SHAPE','parameters must be an object');
  const result=har(data,p);
  function check(v:any):void {
    if(typeof v==='number')requireValue(Number.isFinite(v),'NUMERIC','nonfinite computed output');
    else if(Array.isArray(v))v.forEach(check);
    else if(v && typeof v==='object')Object.values(v).forEach(check);
  }
  check(result);
  return {topic_id:"D10-F03-A06",title:"HAR-RV",parameters:p,...result};
}
