/**
 * Historical Constituent Reconstruction: Rebuild the Roster Without Looking Ahead
 *
 * Topic D02-F04-A01 · Corporate Actions and Security Master Data / Point-in-Time Universe · difficulty 4
 * Shape: record-transform · entry: calculate()
 * Article: https://thefintechbuilder.com/corporate-actions-and-security-master-data/point-in-time-universe/historical-constituent-reconstruction/
 * Repo:    https://github.com/IslamBaraka90/Fintech-Historical-Constituent-Reconstruction-Corporate-Actions-algorithm
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D02-F04-A01-historical-constituent-reconstruction
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { calculate as run } from "./impl.ts";

export const meta = {
  id: "D02-F04-A01",
  title: "Historical Constituent Reconstruction: Rebuild the Roster Without Looking Ahead",
  slug: "historical-constituent-reconstruction",
  domainId: "D02",
  domain: "Corporate Actions and Security Master Data",
  familyId: "D02-F04",
  family: "Point-in-Time Universe",
  difficulty: 4,
  archetype: "record-transform",
  entry: "calculate",
  path: "corporate-actions-and-security-master-data/point-in-time-universe/historical-constituent-reconstruction",
  articleUrl: "https://thefintechbuilder.com/corporate-actions-and-security-master-data/point-in-time-universe/historical-constituent-reconstruction/",
  repoUrl: "https://github.com/IslamBaraka90/Fintech-Historical-Constituent-Reconstruction-Corporate-Actions-algorithm",
} as const;
