// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D06-price-action-and-candlesticks/D06-F01-candle-foundations/D06-F01-A01-candle-anatomy/implementations/typescript/candleAnatomy.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free reference implementation for D06-F01-A01 Candle Anatomy. */

export type Direction = "bullish" | "bearish" | "neutral";

export interface CandleInput {
  open: number;
  high: number;
  low: number;
  close: number;
  timestamp?: string;
  instrument_id?: string;
  interval?: string;
  is_closed?: boolean;
  volume?: number;
  price_basis?: string;
  session?: string;
}

export interface CandleAnatomy {
  open: number;
  high: number;
  low: number;
  close: number;
  timestamp: string | null;
  instrument_id: string | null;
  interval: string | null;
  is_closed: boolean | null;
  volume: number | null;
  price_basis: string | null;
  session: string | null;
  body_high: number;
  body_low: number;
  body: number;
  upper_shadow: number;
  lower_shadow: number;
  range: number;
  direction: Direction;
  body_to_range: number | null;
  upper_shadow_to_range: number | null;
  lower_shadow_to_range: number | null;
  open_position: number | null;
  close_position: number | null;
}

export class CandleValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "CandleValidationError";
  }
}

function finiteNumber(value: unknown, field: string): number {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    throw new CandleValidationError(`${field} must be a finite real number.`);
  }
  return value;
}

function optionalString(
  candle: Record<string, unknown>,
  field: string,
): string | null {
  const value = candle[field];
  if (value === undefined || value === null) return null;
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new CandleValidationError(
      `${field} must be a non-empty string when provided.`,
    );
  }
  return value;
}

export function analyzeCandle(
  candle: CandleInput,
  directionEpsilon = 0,
): CandleAnatomy {
  const epsilon = finiteNumber(directionEpsilon, "direction_epsilon");
  if (epsilon < 0) {
    throw new CandleValidationError(
      "direction_epsilon must be non-negative.",
    );
  }

  if (candle === null || typeof candle !== "object" || Array.isArray(candle)) {
    throw new CandleValidationError("candle must be an object.");
  }

  const record = candle as unknown as Record<string, unknown>;

  const open = finiteNumber(candle.open, "open");
  const high = finiteNumber(candle.high, "high");
  const low = finiteNumber(candle.low, "low");
  const close = finiteNumber(candle.close, "close");
  const timestamp = optionalString(record, "timestamp");
  const instrumentId = optionalString(record, "instrument_id");
  const interval = optionalString(record, "interval");
  const priceBasis = optionalString(record, "price_basis");
  const session = optionalString(record, "session");
  if (
    candle.is_closed !== undefined &&
    candle.is_closed !== null &&
    typeof candle.is_closed !== "boolean"
  ) {
    throw new CandleValidationError(
      "is_closed must be a boolean when provided.",
    );
  }
  const volume =
    candle.volume === undefined || candle.volume === null
      ? null
      : finiteNumber(candle.volume, "volume");

  const bodyHigh = Math.max(open, close);
  const bodyLow = Math.min(open, close);
  if (high < bodyHigh) {
    throw new CandleValidationError(
      "high must be at least max(open, close).",
    );
  }
  if (low > bodyLow) {
    throw new CandleValidationError(
      "low must be at most min(open, close).",
    );
  }

  const body = Math.abs(close - open);
  const upperShadow = high - bodyHigh;
  const lowerShadow = bodyLow - low;
  const range = high - low;
  const difference = close - open;

  let direction: Direction;
  if (difference > epsilon) {
    direction = "bullish";
  } else if (-difference > epsilon) {
    direction = "bearish";
  } else {
    direction = "neutral";
  }

  const hasRange = range !== 0;
  return {
    open,
    high,
    low,
    close,
    timestamp,
    instrument_id: instrumentId,
    interval,
    is_closed: candle.is_closed ?? null,
    volume,
    price_basis: priceBasis,
    session,
    body_high: bodyHigh,
    body_low: bodyLow,
    body,
    upper_shadow: upperShadow,
    lower_shadow: lowerShadow,
    range,
    direction,
    body_to_range: hasRange ? body / range : null,
    upper_shadow_to_range: hasRange ? upperShadow / range : null,
    lower_shadow_to_range: hasRange ? lowerShadow / range : null,
    open_position: hasRange ? (open - low) / range : null,
    close_position: hasRange ? (close - low) / range : null,
  };
}

export function analyzeCandles(
  candles: readonly CandleInput[],
  directionEpsilon = 0,
): CandleAnatomy[] {
  return candles.map((candle) => analyzeCandle(candle, directionEpsilon));
}
