// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D01-market-data-engineering/D01-F02-cleaning-and-validation/D01-F02-A06-crossed-locked-market-detector/implementations/typescript/marketState.ts
// Re-run `npm run sync` after changing the catalog implementation.

export type MarketState = "NORMAL" | "LOCKED" | "CROSSED" | "INVALID";

export type QuoteSnapshot = Record<string, unknown> & {
  instrument: string;
  market_scope: string;
  feed: string;
  event_time: string;
  receive_time: string;
  sequence: number;
  bid: number;
  ask: number;
  tick_size: number;
};

export type DetectorOptions = {
  tolerance_ticks?: number;
  relative_tolerance_ppm?: number;
};

const requiredContext = [
  "instrument", "market_scope", "feed", "event_time", "receive_time", "sequence",
];

function invalid(quote: Record<string, unknown>, index: number, reason: string) {
  return {
    ...quote,
    index,
    state: "INVALID" as MarketState,
    spread: null,
    spread_ticks: null,
    effective_tolerance: null,
    numeric_guard: null,
    diagnostic: "CONTEXT_OR_VALUE_INVALID",
    reason,
  };
}

function parseTime(value: unknown): number {
  if (typeof value !== "string" || !/(Z|[+-]\d\d:\d\d)$/.test(value)) {
    throw new Error("timestamp must include an offset or Z");
  }
  const parsed = Date.parse(value);
  if (!Number.isFinite(parsed)) throw new Error("timestamp must be valid ISO-8601");
  return parsed;
}

export function classifyMarkets(
  quotes: Record<string, unknown>[],
  options: DetectorOptions = {},
) {
  const toleranceTicks = options.tolerance_ticks ?? 0;
  const relativeTolerancePpm = options.relative_tolerance_ppm ?? 0;
  for (const [name, value] of [
    ["tolerance_ticks", toleranceTicks],
    ["relative_tolerance_ppm", relativeTolerancePpm],
  ] as const) {
    if (!Number.isFinite(value) || value < 0) {
      throw new Error(`${name} must be finite and nonnegative`);
    }
  }

  return quotes.map((quote, index) => {
    const missing = requiredContext.filter((field) => !(field in quote));
    if (missing.length) return invalid(quote, index, `missing context: ${missing.join(", ")}`);

    const bid = Number(quote.bid);
    const ask = Number(quote.ask);
    const tickSize = Number(quote.tick_size);
    const sequence = Number(quote.sequence);
    let eventTime: number;
    let receiveTime: number;
    try {
      eventTime = parseTime(quote.event_time);
      receiveTime = parseTime(quote.receive_time);
    } catch (error) {
      return invalid(quote, index, `unusable field: ${(error as Error).message}`);
    }
    if (
      quote.bid === null || quote.ask === null || quote.tick_size === null ||
      !Number.isFinite(bid) || !Number.isFinite(ask) || !Number.isFinite(tickSize) ||
      !Number.isInteger(sequence)
    ) return invalid(quote, index, "bid, ask, tick_size, and sequence must be numeric");
    if (bid < 0 || ask < 0 || tickSize <= 0 || sequence < 0) {
      return invalid(quote, index, "prices/sequence must be nonnegative and tick_size positive");
    }

    const spread = ask - bid;
    const priceScale = Math.max(Math.abs(bid), Math.abs(ask), 1);
    const effectiveTolerance = Math.max(
      tickSize * toleranceTicks,
      priceScale * relativeTolerancePpm * 1e-6,
    );
    const numericGuard = priceScale * Number.EPSILON * 8;
    const boundary = effectiveTolerance + numericGuard;
    const state: MarketState = Math.abs(spread) <= boundary
      ? "LOCKED"
      : spread < -boundary ? "CROSSED" : "NORMAL";
    const diagnostic = state === "LOCKED"
      ? "LOCKED_OBSERVATION"
      : state === "CROSSED" ? "CROSSED_OBSERVATION" : "POSITIVE_SPREAD_OBSERVATION";
    const contextWarnings = receiveTime < eventTime ? ["RECEIVE_BEFORE_EVENT_CHECK_CLOCKS"] : [];
    return {
      ...quote,
      index,
      bid,
      ask,
      tick_size: tickSize,
      spread,
      spread_ticks: spread / tickSize,
      effective_tolerance: effectiveTolerance,
      numeric_guard: numericGuard,
      state,
      diagnostic,
      context_warnings: contextWarnings,
      reason: null,
    };
  });
}
