/**
 * Crossed/Locked Market Detector
 *
 * Topic D01-F02-A06 · Market Data Engineering / Cleaning and Validation · difficulty 2
 * Shape: row-classify · entry: classifyMarkets()
 * Article: https://thefintechbuilder.com/market-data-engineering/cleaning-and-validation/crossed-locked-market-detector/
 * Repo:    https://github.com/IslamBaraka90/Fintech-Crossed-Locked-Market-Detector-Data-Quality-algorithm
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D01-F02-A06-crossed-locked-market-detector
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { classifyMarkets as run } from "./impl.ts";

export const meta = {
  id: "D01-F02-A06",
  title: "Crossed/Locked Market Detector",
  slug: "crossed-locked-market-detector",
  domainId: "D01",
  domain: "Market Data Engineering",
  familyId: "D01-F02",
  family: "Cleaning and Validation",
  difficulty: 2,
  archetype: "row-classify",
  entry: "classifyMarkets",
  path: "market-data-engineering/cleaning-and-validation/crossed-locked-market-detector",
  articleUrl: "https://thefintechbuilder.com/market-data-engineering/cleaning-and-validation/crossed-locked-market-detector/",
  repoUrl: "https://github.com/IslamBaraka90/Fintech-Crossed-Locked-Market-Detector-Data-Quality-algorithm",
} as const;
