/**
 * Fibonacci Pivot Points
 *
 * Topic D08-F01-A06 · Geometric Chart Patterns / Pivots and Levels · difficulty 2
 * Shape: record-transform · entry: fibonacciPivotPoints()
 * Article: https://thefintechbuilder.com/geometric-chart-patterns/pivots-and-levels/fibonacci-pivot-points/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D08-F01-A06-fibonacci-pivot-points
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { fibonacciPivotPoints as run } from "./impl.ts";

export const meta = {
  id: "D08-F01-A06",
  title: "Fibonacci Pivot Points",
  slug: "fibonacci-pivot-points",
  domainId: "D08",
  domain: "Geometric Chart Patterns",
  familyId: "D08-F01",
  family: "Pivots and Levels",
  difficulty: 2,
  archetype: "record-transform",
  entry: "fibonacciPivotPoints",
  path: "geometric-chart-patterns/pivots-and-levels/fibonacci-pivot-points",
  articleUrl: "https://thefintechbuilder.com/geometric-chart-patterns/pivots-and-levels/fibonacci-pivot-points/",
  repoUrl: null,
} as const;
