/**
 * Baxter-King Filter
 *
 * Topic D09-F05-A03 · Statistical Time Series / Decomposition and Cycles · difficulty 4
 * Shape: record-transform · entry: bkFilter()
 * Article: https://thefintechbuilder.com/statistical-time-series/decomposition-and-cycles/baxter-king-filter/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D09-F05-A03-baxter-king-filter
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { bkFilter as run } from "./impl.ts";

export const meta = {
  id: "D09-F05-A03",
  title: "Baxter-King Filter",
  slug: "baxter-king-filter",
  domainId: "D09",
  domain: "Statistical Time Series",
  familyId: "D09-F05",
  family: "Decomposition and Cycles",
  difficulty: 4,
  archetype: "record-transform",
  entry: "bkFilter",
  path: "statistical-time-series/decomposition-and-cycles/baxter-king-filter",
  articleUrl: "https://thefintechbuilder.com/statistical-time-series/decomposition-and-cycles/baxter-king-filter/",
  repoUrl: null,
} as const;
