/**
 * Effect Size, Practical Significance, and Multiple Comparisons
 *
 * Topic D00-F08-A10 · Financial Mathematics, Statistics, and Data Foundations / Sampling, Estimation, and Statistical Inference · difficulty 1
 * Shape: record-transform · entry: effectSizePracticalSignificanceAndMultipleComparisons()
 * Article: https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/sampling-estimation-and-statistical-inference/effect-size-practical-significance-and-multiple-comparisons/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F08-A10-effect-size-prac
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { effectSizePracticalSignificanceAndMultipleComparisons as run } from "./impl.ts";

export const meta = {
  id: "D00-F08-A10",
  title: "Effect Size, Practical Significance, and Multiple Comparisons",
  slug: "effect-size-practical-significance-and-multiple-comparisons",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F08",
  family: "Sampling, Estimation, and Statistical Inference",
  difficulty: 1,
  archetype: "record-transform",
  entry: "effectSizePracticalSignificanceAndMultipleComparisons",
  path: "financial-mathematics-statistics-and-data-foundations/sampling-estimation-and-statistical-inference/effect-size-practical-significance-and-multiple-comparisons",
  articleUrl: "https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/sampling-estimation-and-statistical-inference/effect-size-practical-significance-and-multiple-comparisons/",
  repoUrl: null,
} as const;
