/**
 * REIT Fundamental Score
 *
 * Topic D18-F10-A03 · Fundamental Analysis and Valuation / Sector-Specific Equity Scoring · difficulty 4
 * Shape: record-transform · entry: reitFundamentalScore()
 * Article: https://thefintechbuilder.com/fundamental-analysis-and-valuation/sector-specific-equity-scoring/reit-fundamental-score/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D18-F10-A03-reit-fundamental-score
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { reitFundamentalScore as run } from "./impl.ts";

export const meta = {
  id: "D18-F10-A03",
  title: "REIT Fundamental Score",
  slug: "reit-fundamental-score",
  domainId: "D18",
  domain: "Fundamental Analysis and Valuation",
  familyId: "D18-F10",
  family: "Sector-Specific Equity Scoring",
  difficulty: 4,
  archetype: "record-transform",
  entry: "reitFundamentalScore",
  path: "fundamental-analysis-and-valuation/sector-specific-equity-scoring/reit-fundamental-score",
  articleUrl: "https://thefintechbuilder.com/fundamental-analysis-and-valuation/sector-specific-equity-scoring/reit-fundamental-score/",
  repoUrl: null,
} as const;
