// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D06-price-action-and-candlesticks/D06-F04-multi-candle-patterns/D06-F04-A12-upside-gap-two-crows/implementations/typescript/upside_gap_two_crows.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D06-F04-A12: Upside Gap Two Crows. */
import { upsideGapTwoCrows as nativeUpsideGapTwoCrows, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D06-F04-A12";
export const TITLE = "Upside Gap Two Crows";

export function upsideGapTwoCrows(input: TopicInput): TopicResult {
  return nativeUpsideGapTwoCrows(input);
}
