/**
 * Herfindahl Constituent Concentration
 *
 * Topic D04-F05-A02 · Market Breadth and Internals / Concentration and Diffusion · difficulty 2
 * Shape: record-transform · entry: calculate()
 * Article: https://thefintechbuilder.com/market-breadth-and-internals/concentration-and-diffusion/herfindahl-constituent-concentration/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D04-F05-A02-herfindahl-constituent-concentration
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { calculate as run } from "./impl.ts";

export const meta = {
  id: "D04-F05-A02",
  title: "Herfindahl Constituent Concentration",
  slug: "herfindahl-constituent-concentration",
  domainId: "D04",
  domain: "Market Breadth and Internals",
  familyId: "D04-F05",
  family: "Concentration and Diffusion",
  difficulty: 2,
  archetype: "record-transform",
  entry: "calculate",
  path: "market-breadth-and-internals/concentration-and-diffusion/herfindahl-constituent-concentration",
  articleUrl: "https://thefintechbuilder.com/market-breadth-and-internals/concentration-and-diffusion/herfindahl-constituent-concentration/",
  repoUrl: null,
} as const;
