/**
 * Holt-Winters
 *
 * Topic D09-F02-A05 · Statistical Time Series / Forecast Models · difficulty 3
 * Shape: record-transform · entry: forecastHoltWintersAdditive()
 * Article: https://thefintechbuilder.com/statistical-time-series/forecast-models/holt-winters/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D09-F02-A05-holt-winters
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { forecastHoltWintersAdditive as run } from "./impl.ts";

export const meta = {
  id: "D09-F02-A05",
  title: "Holt-Winters",
  slug: "holt-winters",
  domainId: "D09",
  domain: "Statistical Time Series",
  familyId: "D09-F02",
  family: "Forecast Models",
  difficulty: 3,
  archetype: "record-transform",
  entry: "forecastHoltWintersAdditive",
  path: "statistical-time-series/forecast-models/holt-winters",
  articleUrl: "https://thefintechbuilder.com/statistical-time-series/forecast-models/holt-winters/",
  repoUrl: null,
} as const;
