/**
 * Vertical Horizontal Filter
 *
 * Topic D07-F02-A15 · Technical Indicators / Trend Systems · difficulty 2
 * Shape: series-transform · entry: verticalHorizontalFilter()
 * Article: https://thefintechbuilder.com/technical-indicators/trend-systems/vertical-horizontal-filter/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F02-A15-vertical-horizontal-filter
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { verticalHorizontalFilter as run } from "./impl.ts";

export const meta = {
  id: "D07-F02-A15",
  title: "Vertical Horizontal Filter",
  slug: "vertical-horizontal-filter",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F02",
  family: "Trend Systems",
  difficulty: 2,
  archetype: "series-transform",
  entry: "verticalHorizontalFilter",
  path: "technical-indicators/trend-systems/vertical-horizontal-filter",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/trend-systems/vertical-horizontal-filter/",
  repoUrl: null,
} as const;
