/**
 * Hawkes Order-Arrival Model
 *
 * Topic D11-F04-A05 · Market Microstructure / Order-Book Dynamics · difficulty 5
 * Shape: record-transform · entry: hawkesOrderArrival()
 * Article: https://thefintechbuilder.com/market-microstructure/order-book-dynamics/hawkes-order-arrival-model/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D11-F04-A05-hawkes-order-arrival-model
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { hawkesOrderArrival as run } from "./impl.ts";

export const meta = {
  id: "D11-F04-A05",
  title: "Hawkes Order-Arrival Model",
  slug: "hawkes-order-arrival-model",
  domainId: "D11",
  domain: "Market Microstructure",
  familyId: "D11-F04",
  family: "Order-Book Dynamics",
  difficulty: 5,
  archetype: "record-transform",
  entry: "hawkesOrderArrival",
  path: "market-microstructure/order-book-dynamics/hawkes-order-arrival-model",
  articleUrl: "https://thefintechbuilder.com/market-microstructure/order-book-dynamics/hawkes-order-arrival-model/",
  repoUrl: null,
} as const;
