/**
 * Poisson Distribution and Event Counts
 *
 * Topic D00-F07-A03 · Financial Mathematics, Statistics, and Data Foundations / Probability Distributions and Simulation Basics · difficulty 1
 * Shape: record-transform · entry: poissonDistributionAndEventCounts()
 * Article: https://thefintechbuilder.com/foundations/probability-distributions-and-simulation-basics/poisson-distribution-and-event-counts/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F07-A03-poisson-distribu
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { poissonDistributionAndEventCounts as run } from "./impl.ts";

export const meta = {
  id: "D00-F07-A03",
  title: "Poisson Distribution and Event Counts",
  slug: "poisson-distribution-and-event-counts",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F07",
  family: "Probability Distributions and Simulation Basics",
  difficulty: 1,
  archetype: "record-transform",
  entry: "poissonDistributionAndEventCounts",
  path: "foundations/probability-distributions-and-simulation-basics/poisson-distribution-and-event-counts",
  articleUrl: "https://thefintechbuilder.com/foundations/probability-distributions-and-simulation-basics/poisson-distribution-and-event-counts/",
  repoUrl: null,
} as const;
