// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D11-market-microstructure/D11-F01-trade-classification/D11-F01-A02-quote-test/implementations/typescript/trade-classification.ts
// Re-run `npm run sync` after changing the catalog implementation.
//
// This family shares one implementation across its topics; the body lives at
// src/_shared/trade-classification.ts and is re-exported here so the public surface of
// this subpath is unchanged.

export * from "../../../_shared/trade-classification.ts";
