// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F05-volume-indicators/D07-F05-A05-volume-price-trend/implementations/typescript/volume.ts
// Re-run `npm run sync` after changing the catalog implementation.
//
// This family shares one implementation across its topics; the body lives at
// src/_shared/volume.ts and is re-exported here so the public surface of
// this subpath is unchanged.

export * from "../../../_shared/volume.ts";
