/**
 * Squeeze Momentum
 *
 * Topic D07-F07-A12 · Technical Indicators / Bands, Envelopes, and Squeezes · difficulty 2
 * Shape: series-transform · entry: squeezeMomentum()
 * Article: https://thefintechbuilder.com/technical-indicators/bands-envelopes-and-squeezes/squeeze-momentum/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F07-A12-squeeze-momentum
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { squeezeMomentum as run } from "./impl.ts";

export const meta = {
  id: "D07-F07-A12",
  title: "Squeeze Momentum",
  slug: "squeeze-momentum",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F07",
  family: "Bands, Envelopes, and Squeezes",
  difficulty: 2,
  archetype: "series-transform",
  entry: "squeezeMomentum",
  path: "technical-indicators/bands-envelopes-and-squeezes/squeeze-momentum",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/bands-envelopes-and-squeezes/squeeze-momentum/",
  repoUrl: null,
} as const;
