/**
 * Breadth-Divergence Detector
 *
 * Topic D04-F04-A06 · Market Breadth and Internals / Thrust and Pressure · difficulty 5
 * Shape: record-transform · entry: calculate()
 * Article: https://thefintechbuilder.com/market-breadth-and-internals/thrust-and-pressure/breadth-divergence-detector/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D04-F04-A06-breadth-divergence-detector
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { calculate as run } from "./impl.ts";

export const meta = {
  id: "D04-F04-A06",
  title: "Breadth-Divergence Detector",
  slug: "breadth-divergence-detector",
  domainId: "D04",
  domain: "Market Breadth and Internals",
  familyId: "D04-F04",
  family: "Thrust and Pressure",
  difficulty: 5,
  archetype: "record-transform",
  entry: "calculate",
  path: "market-breadth-and-internals/thrust-and-pressure/breadth-divergence-detector",
  articleUrl: "https://thefintechbuilder.com/market-breadth-and-internals/thrust-and-pressure/breadth-divergence-detector/",
  repoUrl: null,
} as const;
