// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F01-trend-smoothing/D07-F01-A16-least-squares-moving-average-lsma/implementations/typescript/least_squares_moving_average_lsma.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F01-A16: Least-Squares Moving Average (LSMA). */
import { leastSquaresMovingAverageLsma as nativeLeastSquaresMovingAverageLsma, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F01-A16";
export const TITLE = "Least-Squares Moving Average (LSMA)";

export function leastSquaresMovingAverageLsma(input: TopicInput): TopicResult {
  return nativeLeastSquaresMovingAverageLsma(input);
}
