/**
 * Ticker-Change Chain Resolution
 *
 * Topic D02-F03-A02 · Corporate Actions and Security Master Data / Identity Continuity · difficulty 3
 * Shape: row-classify · entry: resolveTickerChain()
 * Article: https://thefintechbuilder.com/corporate-actions-and-security-master-data/identity-continuity/ticker-change-chain-resolution/
 * Repo:    https://github.com/IslamBaraka90/Fintech-Ticker-Change-Chain-Resolution-Corporate-Actions-algorithm
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D02-F03-A02-ticker-change-chain-resolution
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { resolveTickerChain as run } from "./impl.ts";

export const meta = {
  id: "D02-F03-A02",
  title: "Ticker-Change Chain Resolution",
  slug: "ticker-change-chain-resolution",
  domainId: "D02",
  domain: "Corporate Actions and Security Master Data",
  familyId: "D02-F03",
  family: "Identity Continuity",
  difficulty: 3,
  archetype: "row-classify",
  entry: "resolveTickerChain",
  path: "corporate-actions-and-security-master-data/identity-continuity/ticker-change-chain-resolution",
  articleUrl: "https://thefintechbuilder.com/corporate-actions-and-security-master-data/identity-continuity/ticker-change-chain-resolution/",
  repoUrl: "https://github.com/IslamBaraka90/Fintech-Ticker-Change-Chain-Resolution-Corporate-Actions-algorithm",
} as const;
