// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D01-market-data-engineering/D01-F03-time-synchronization/D01-F03-A03-refresh-time-sampling/implementations/typescript/refreshTime.ts
// Re-run `npm run sync` after changing the catalog implementation.

export type Observation = {
  partition: string;
  instrument: string;
  record_id: string;
  revision: number;
  event_time: string;
  available_at: string;
  value: number;
};

type Internal = Observation & { _event_ms: number; _available_ms: number };

const milliseconds = (value: string): number => {
  if (typeof value !== "string" || !value.endsWith("Z")) {
    throw new Error("timestamps must be RFC 3339 UTC strings ending in Z");
  }
  const parsed = Date.parse(value);
  if (!Number.isFinite(parsed)) throw new Error(`invalid timestamp: ${value}`);
  return parsed;
};

const formatMs = (value: number): string => new Date(value).toISOString();

function validate(
  observations: Observation[], requiredInstruments: string[],
): { rows: Internal[]; instruments: string[] } {
  const instruments = [...new Set(requiredInstruments)].sort();
  if (instruments.length < 2 || instruments.some((item) => !item)) {
    throw new Error("requiredInstruments must contain at least two names");
  }
  const allowed = new Set(instruments);
  const rows: Internal[] = observations.map((raw) => {
    const required: (keyof Observation)[] = [
      "partition", "instrument", "record_id", "revision", "event_time",
      "available_at", "value",
    ];
    const missing = required.filter((field) => raw[field] === undefined);
    if (missing.length) throw new Error(`missing fields: ${missing.join(", ")}`);
    if (!allowed.has(raw.instrument)) throw new Error(`unexpected instrument: ${raw.instrument}`);
    if (!raw.partition || !raw.record_id) throw new Error("partition and record_id must be non-empty");
    if (!Number.isInteger(raw.revision) || raw.revision < 0) throw new Error("revision must be a non-negative integer");
    if (!Number.isFinite(raw.value)) throw new Error("value must be finite");
    const event = milliseconds(raw.event_time), available = milliseconds(raw.available_at);
    if (event > available) throw new Error("event_time cannot be after available_at");
    return { ...raw, _event_ms: event, _available_ms: available };
  });
  rows.sort((a, b) =>
    a.partition.localeCompare(b.partition) || a._available_ms - b._available_ms ||
    a.instrument.localeCompare(b.instrument) || a.record_id.localeCompare(b.record_id) ||
    a.revision - b.revision
  );
  const histories = new Map<string, Internal[]>(), eventOwners = new Map<string, string>();
  for (const row of rows) {
    const eventKey = `${row.partition}\0${row.instrument}\0${row._event_ms}`;
    const eventOwner = eventOwners.get(eventKey);
    if (eventOwner !== undefined && eventOwner !== row.record_id) {
      throw new Error("ambiguous duplicate event_time across distinct record_id values");
    }
    eventOwners.set(eventKey, row.record_id);
    const key = `${row.partition}\0${row.record_id}`, history = histories.get(key) ?? [];
    if (!history.length && row.revision !== 0) throw new Error("the first revision of a record must be zero");
    if (history.length) {
      const previous = history.at(-1)!;
      if (row.instrument !== previous.instrument) throw new Error("a correction cannot change instrument");
      if (row.revision !== previous.revision + 1) throw new Error("record revisions must be contiguous");
      if (row._available_ms <= previous._available_ms) throw new Error("corrections must become available strictly later");
    }
    history.push(row); histories.set(key, history);
  }
  return { rows, instruments };
}

function latestSources(known: Internal[], instruments: string[]): Record<string, Internal> {
  const latest = new Map<string, Internal>();
  for (const row of known) latest.set(row.record_id, row);
  const result: Record<string, Internal> = {};
  for (const instrument of instruments) {
    const candidates = [...latest.values()].filter((row) => row.instrument === instrument);
    if (!candidates.length) throw new Error(`no known observation for ${instrument}`);
    const owners = new Map<number, string>();
    for (const row of candidates) {
      const owner = owners.get(row._event_ms);
      if (owner !== undefined && owner !== row.record_id) {
        throw new Error("ambiguous duplicate event_time across distinct record_id values");
      }
      owners.set(row._event_ms, row.record_id);
    }
    result[instrument] = candidates.reduce((best, row) =>
      row._event_ms > best._event_ms ||
      (row._event_ms === best._event_ms && row._available_ms > best._available_ms) ||
      (row._event_ms === best._event_ms && row._available_ms === best._available_ms && row.record_id > best.record_id)
        ? row : best
    );
  }
  return result;
}

export function refreshTimeSample(
  observations: Observation[], requiredInstruments: string[], maxStalenessMs: number,
) {
  if (!Number.isInteger(maxStalenessMs) || maxStalenessMs < 0) {
    throw new Error("maxStalenessMs must be a non-negative integer");
  }
  const { rows, instruments } = validate(observations, requiredInstruments);
  const partitions = [...new Set(rows.map((row) => row.partition))].sort();
  const outputRows: any[] = [], summaries: any[] = [];
  for (const partition of partitions) {
    const arrivals = rows.filter((row) => row.partition === partition);
    const byInstrument = Object.fromEntries(instruments.map((instrument) => [
      instrument, arrivals.filter((row) => row.instrument === instrument),
    ])) as Record<string, Internal[]>;
    let cursor = Number.NEGATIVE_INFINITY, sequence = 0, discardedTotal = 0;
    let staleCount = 0, acceptedCount = 0;
    while (true) {
      const firstNew: Record<string, Internal> = {};
      let complete = true;
      for (const instrument of instruments) {
        const found = byInstrument[instrument].find((row) => row._available_ms > cursor);
        if (!found) { complete = false; break; }
        firstNew[instrument] = found;
      }
      if (!complete) break;
      const refresh = Math.max(...Object.values(firstNew).map((row) => row._available_ms));
      const interval = arrivals.filter((row) => row._available_ms > cursor && row._available_ms <= refresh);
      const known = arrivals.filter((row) => row._available_ms <= refresh);
      const selected = latestSources(known, instruments);
      const selectedInterval = new Set(Object.values(selected)
        .filter((row) => row._available_ms > cursor && row._available_ms <= refresh)
        .map((row) => `${row.record_id}\0${row.revision}`));
      const discarded = interval.length - selectedInterval.size;
      discardedTotal += discarded;
      const ages = Object.fromEntries(instruments.map((instrument) => [
        instrument, refresh - selected[instrument]._event_ms,
      ]));
      const status = Math.max(...Object.values(ages)) > maxStalenessMs ? "stale" : "accepted";
      staleCount += status === "stale" ? 1 : 0;
      acceptedCount += status === "accepted" ? 1 : 0;
      outputRows.push({
        partition, sequence: ++sequence,
        previous_refresh_available_at: Number.isFinite(cursor) ? formatMs(cursor) : null,
        refresh_available_at: formatMs(refresh),
        controller_instruments: instruments.filter((instrument) => firstNew[instrument]._available_ms === refresh),
        status,
        values: Object.fromEntries(instruments.map((instrument) => [instrument, selected[instrument].value])),
        sources: Object.fromEntries(instruments.map((instrument) => [instrument, {
          record_id: selected[instrument].record_id,
          revision: selected[instrument].revision,
          event_time: selected[instrument].event_time,
          available_at: selected[instrument].available_at,
        }])),
        event_age_ms: ages,
        arrivals_by_instrument: Object.fromEntries(instruments.map((instrument) => [
          instrument, interval.filter((row) => row.instrument === instrument).length,
        ])),
        discarded_updates: discarded,
      });
      cursor = refresh;
    }
    const tail = arrivals.filter((row) => row._available_ms > cursor).length;
    summaries.push({
      partition, input_updates: arrivals.length, refresh_candidates: sequence,
      accepted_rows: acceptedCount, stale_rows: staleCount,
      discarded_updates: discardedTotal, unmatched_tail_updates: tail,
      loss_fraction: { numerator: discardedTotal + tail, denominator: arrivals.length },
    });
  }
  return { rows: outputRows, partitions: summaries };
}
