/**
 * Hasbrouck Price Impact
 *
 * Topic D11-F03-A04 · Market Microstructure / Order-Flow and Impact · difficulty 5
 * Shape: record-transform · entry: hasbrouckPriceImpact()
 * Article: https://thefintechbuilder.com/market-microstructure/order-flow-and-impact/hasbrouck-price-impact/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D11-F03-A04-hasbrouck-price-impact
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { hasbrouckPriceImpact as run } from "./impl.ts";

export const meta = {
  id: "D11-F03-A04",
  title: "Hasbrouck Price Impact",
  slug: "hasbrouck-price-impact",
  domainId: "D11",
  domain: "Market Microstructure",
  familyId: "D11-F03",
  family: "Order-Flow and Impact",
  difficulty: 5,
  archetype: "record-transform",
  entry: "hasbrouckPriceImpact",
  path: "market-microstructure/order-flow-and-impact/hasbrouck-price-impact",
  articleUrl: "https://thefintechbuilder.com/market-microstructure/order-flow-and-impact/hasbrouck-price-impact/",
  repoUrl: null,
} as const;
