// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D14-portfolio-construction/D14-F03-bayesian-and-robust-allocation/D14-F03-A01-black-litterman/implementations/typescript/black-litterman.ts
// Re-run `npm run sync` after changing the catalog implementation.

export class ContractError extends Error {
}
type Vector = number[];
type Matrix = number[][];
function finiteVector(values: number[], name: string): Vector {
    const out = values.map(Number);
    if (!out.length || out.some((x) => !Number.isFinite(x)))
        throw new ContractError(`${name} must be a non-empty finite vector`);
    return out;
}
function matrix(values: number[][], rows: number, cols: number, name: string): Matrix {
    const out = values.map((row) => row.map(Number));
    if (out.length !== rows || out.some((row) => row.length !== cols) || out.flat().some((x) => !Number.isFinite(x))) {
        throw new ContractError(`${name} must have shape ${rows}x${cols} with finite values`);
    }
    return out;
}
function solve(a: Matrix, b: Vector): Vector {
    const n = b.length;
    const aug = a.map((row, i) => [...row, b[i]]);
    for (let col = 0; col < n; col++) {
        let pivot = col;
        for (let row = col + 1; row < n; row++)
            if (Math.abs(aug[row][col]) > Math.abs(aug[pivot][col]))
                pivot = row;
        if (Math.abs(aug[pivot][col]) <= 1e-14)
            throw new ContractError("linear system is singular");
        [aug[col], aug[pivot]] = [aug[pivot], aug[col]];
        const scale = aug[col][col];
        aug[col] = aug[col].map((x) => x / scale);
        for (let row = 0; row < n; row++)
            if (row !== col) {
                const factor = aug[row][col];
                aug[row] = aug[row].map((x, j) => x - factor * aug[col][j]);
            }
    }
    return aug.map((row) => row[n]);
}
function validateSpd(a: Matrix, name: string): void {
    const n = a.length;
    if (a.some((row, i) => row.some((x, j) => Math.abs(x - a[j][i]) > 1e-12)))
        throw new ContractError(`${name} must be symmetric`);
    const lower = Array.from({ length: n }, () => Array(n).fill(0));
    for (let i = 0; i < n; i++)
        for (let j = 0; j <= i; j++) {
            const value = a[i][j] - Array.from({ length: j }, (_, k) => lower[i][k] * lower[j][k]).reduce((x, y) => x + y, 0);
            if (i === j) {
                if (value <= 1e-14)
                    throw new ContractError(`${name} must be symmetric positive definite`);
                lower[i][j] = Math.sqrt(value);
            }
            else
                lower[i][j] = value / lower[j][j];
        }
}
const dot = (a: Vector, b: Vector) => a.reduce((sum, x, i) => sum + x * b[i], 0);
const matVec = (a: Matrix, x: Vector) => a.map((row) => dot(row, x));
function* combinations(n: number, k: number, start = 0, prefix: number[] = []): Generator<number[]> {
    if (prefix.length === k) {
        yield prefix;
        return;
    }
    for (let i = start; i < n; i++)
        yield* combinations(n, k, i + 1, [...prefix, i]);
}
function longOnlyQp(mu: Vector, sigma: Matrix, riskPenalty: number): Vector {
    const n = mu.length;
    if (n > 12)
        throw new ContractError("reference active-set allocator supports at most 12 assets");
    let best: {
        objective: number;
        weights: Vector;
    } | undefined;
    for (let size = 1; size <= n; size++)
        for (const active of combinations(n, size)) {
            let weights = Array(n).fill(0);
            if (size === 1)
                weights[active[0]] = 1;
            else {
                const sub = active.map((i) => active.map((j) => sigma[i][j]));
                let invMu: Vector, invOne: Vector;
                try {
                    invMu = solve(sub, active.map((i) => mu[i]));
                    invOne = solve(sub, Array(size).fill(1));
                }
                catch {
                    continue;
                }
                const lagrange = (invMu.reduce((a, b) => a + b, 0) - 2 * riskPenalty) / invOne.reduce((a, b) => a + b, 0);
                const subW = invMu.map((x, i) => (x - lagrange * invOne[i]) / (2 * riskPenalty));
                if (Math.min(...subW) <= 1e-12)
                    continue;
                active.forEach((asset, i) => { weights[asset] = subW[i]; });
            }
            const variance = dot(weights, matVec(sigma, weights));
            const objective = dot(mu, weights) - riskPenalty * variance;
            if (!best || objective > best.objective + 1e-14)
                best = { objective, weights };
        }
    if (!best)
        throw new ContractError("no feasible simplex allocation");
    return best.weights;
}
export interface BlackLittermanInput {
    marketWeights: number[];
    covariance: number[][];
    riskAversion: number;
    tau: number;
    viewMatrix: number[][];
    viewReturns: number[];
    viewErrorCovariance: number[][];
    riskPenalty?: number;
}
export interface BlackLittermanResult {
    priorReturns: Vector;
    posteriorReturns: Vector;
    weights: Vector;
    priorView: Vector;
    posteriorView: Vector;
    viewSurprise: Vector;
    variance: number;
    objective: number;
    status: "optimal";
}
export function blackLittermanAllocate(input: BlackLittermanInput): BlackLittermanResult {
    const wm = finiteVector(input.marketWeights, "marketWeights");
    const n = wm.length;
    if (wm.some((x) => x < 0) || Math.abs(wm.reduce((a, b) => a + b, 0) - 1) > 1e-10)
        throw new ContractError("marketWeights must be a non-negative simplex vector");
    const sigma = matrix(input.covariance, n, n, "covariance");
    validateSpd(sigma, "covariance");
    const { riskAversion, tau } = input;
    const riskPenalty = input.riskPenalty ?? 1;
    if (![riskAversion, tau, riskPenalty].every(Number.isFinite) || !(riskAversion > 0) || !(tau > 0) || !(riskPenalty > 0))
        throw new ContractError("riskAversion, tau, and riskPenalty must be positive");
    const q = finiteVector(input.viewReturns, "viewReturns");
    const k = q.length;
    const p = matrix(input.viewMatrix, k, n, "viewMatrix");
    const omega = matrix(input.viewErrorCovariance, k, k, "viewErrorCovariance");
    validateSpd(omega, "viewErrorCovariance");
    const prior = matVec(sigma, wm).map((x) => riskAversion * x);
    const priorView = matVec(p, prior);
    const surprise = q.map((x, i) => x - priorView[i]);
    const tauSigma = sigma.map((row) => row.map((x) => tau * x));
    const middle = Array.from({ length: k }, (_, i) => Array.from({ length: k }, (_, j) => p[i].reduce((s1, pia, a) => s1 + tauSigma[a].reduce((s2, tab, b) => s2 + pia * tab * p[j][b], 0), 0) + omega[i][j]));
    validateSpd(middle, "posterior view system");
    const solved = solve(middle, surprise);
    const tilt = Array.from({ length: n }, (_, i) => p.reduce((sum, row, j) => sum + row.reduce((s, pa, a) => s + tauSigma[i][a] * pa * solved[j], 0), 0));
    const posterior = prior.map((x, i) => x + tilt[i]);
    const weights = longOnlyQp(posterior, sigma, riskPenalty);
    const variance = dot(weights, matVec(sigma, weights));
    return { priorReturns: prior, posteriorReturns: posterior, weights, priorView, posteriorView: matVec(p, posterior), viewSurprise: surprise, variance, objective: dot(posterior, weights) - riskPenalty * variance, status: "optimal" };
}
