// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D09-statistical-time-series/D09-F06-hilbert-and-ehlers-cycle-analytics/D09-F06-A02-hilbert-transform-dominant-cycle-phase/implementations/typescript/hilbert_transform_dominant_cycle_phase.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D09-F06-A02: Hilbert Transform Dominant Cycle Phase. */
import { hilbertTransformDominantCyclePhase as nativeHilbertTransformDominantCyclePhase, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D09-F06-A02";
export const TITLE = "Hilbert Transform Dominant Cycle Phase";

export function hilbertTransformDominantCyclePhase(input: TopicInput): TopicResult {
  return nativeHilbertTransformDominantCyclePhase(input);
}
