// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D06-price-action-and-candlesticks/D06-F03-two-candle-patterns/D06-F03-A10-kicking-pattern/implementations/typescript/kicking_pattern.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D06-F03-A10: Kicking Pattern. */
import { kickingPattern as nativeKickingPattern, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D06-F03-A10";
export const TITLE = "Kicking Pattern";

export function kickingPattern(input: TopicInput): TopicResult {
  return nativeKickingPattern(input);
}
