/**
 * Belt Hold
 *
 * Topic D06-F02-A13 · Price Action and Candlesticks / Single-Candle Patterns · difficulty 2
 * Shape: record-transform · entry: beltHold()
 * Article: https://thefintechbuilder.com/price-action-and-candlesticks/single-candle-patterns/belt-hold/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D06-F02-A13-belt-hold
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { beltHold as run } from "./impl.ts";

export const meta = {
  id: "D06-F02-A13",
  title: "Belt Hold",
  slug: "belt-hold",
  domainId: "D06",
  domain: "Price Action and Candlesticks",
  familyId: "D06-F02",
  family: "Single-Candle Patterns",
  difficulty: 2,
  archetype: "record-transform",
  entry: "beltHold",
  path: "price-action-and-candlesticks/single-candle-patterns/belt-hold",
  articleUrl: "https://thefintechbuilder.com/price-action-and-candlesticks/single-candle-patterns/belt-hold/",
  repoUrl: null,
} as const;
