/**
 * Effective Spread
 *
 * Topic D11-F02-A02 · Market Microstructure / Liquidity and Spreads · difficulty 3
 * Shape: record-transform · entry: effectiveSpread()
 * Article: https://thefintechbuilder.com/market-microstructure/liquidity-and-spreads/effective-spread/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D11-F02-A02-effective-spread
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { effectiveSpread as run } from "./impl.ts";

export const meta = {
  id: "D11-F02-A02",
  title: "Effective Spread",
  slug: "effective-spread",
  domainId: "D11",
  domain: "Market Microstructure",
  familyId: "D11-F02",
  family: "Liquidity and Spreads",
  difficulty: 3,
  archetype: "record-transform",
  entry: "effectiveSpread",
  path: "market-microstructure/liquidity-and-spreads/effective-spread",
  articleUrl: "https://thefintechbuilder.com/market-microstructure/liquidity-and-spreads/effective-spread/",
  repoUrl: null,
} as const;
