/**
 * Marubozu
 *
 * Topic D06-F02-A04 · Price Action and Candlesticks / Single-Candle Patterns · difficulty 2
 * Shape: record-transform · entry: marubozu()
 * Article: https://thefintechbuilder.com/price-action-and-candlesticks/single-candle-patterns/marubozu/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D06-F02-A04-marubozu
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { marubozu as run } from "./impl.ts";

export const meta = {
  id: "D06-F02-A04",
  title: "Marubozu",
  slug: "marubozu",
  domainId: "D06",
  domain: "Price Action and Candlesticks",
  familyId: "D06-F02",
  family: "Single-Candle Patterns",
  difficulty: 2,
  archetype: "record-transform",
  entry: "marubozu",
  path: "price-action-and-candlesticks/single-candle-patterns/marubozu",
  articleUrl: "https://thefintechbuilder.com/price-action-and-candlesticks/single-candle-patterns/marubozu/",
  repoUrl: null,
} as const;
