/**
 * Bearish Harami
 *
 * Topic D06-F03-A04 · Price Action and Candlesticks / Two-Candle Patterns · difficulty 3
 * Shape: record-transform · entry: bearishHarami()
 * Article: https://thefintechbuilder.com/price-action-and-candlesticks/two-candle-patterns/bearish-harami/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D06-F03-A04-bearish-harami
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { bearishHarami as run } from "./impl.ts";

export const meta = {
  id: "D06-F03-A04",
  title: "Bearish Harami",
  slug: "bearish-harami",
  domainId: "D06",
  domain: "Price Action and Candlesticks",
  familyId: "D06-F03",
  family: "Two-Candle Patterns",
  difficulty: 3,
  archetype: "record-transform",
  entry: "bearishHarami",
  path: "price-action-and-candlesticks/two-candle-patterns/bearish-harami",
  articleUrl: "https://thefintechbuilder.com/price-action-and-candlesticks/two-candle-patterns/bearish-harami/",
  repoUrl: null,
} as const;
