/**
 * Student-t Distribution and Heavy Tails
 *
 * Topic D00-F07-A07 · Financial Mathematics, Statistics, and Data Foundations / Probability Distributions and Simulation Basics · difficulty 1
 * Shape: record-transform · entry: studentTDistributionAndHeavyTails()
 * Article: https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/probability-distributions-and-simulation-basics/student-t-distribution-and-heavy-tails/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F07-A07-student-t-distri
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { studentTDistributionAndHeavyTails as run } from "./impl.ts";

export const meta = {
  id: "D00-F07-A07",
  title: "Student-t Distribution and Heavy Tails",
  slug: "student-t-distribution-and-heavy-tails",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F07",
  family: "Probability Distributions and Simulation Basics",
  difficulty: 1,
  archetype: "record-transform",
  entry: "studentTDistributionAndHeavyTails",
  path: "financial-mathematics-statistics-and-data-foundations/probability-distributions-and-simulation-basics/student-t-distribution-and-heavy-tails",
  articleUrl: "https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/probability-distributions-and-simulation-basics/student-t-distribution-and-heavy-tails/",
  repoUrl: null,
} as const;
