/**
 * Rising/Falling Three Methods
 *
 * Topic D06-F04-A11 · Price Action and Candlesticks / Multi-Candle Patterns · difficulty 2
 * Shape: record-transform · entry: risingFallingThreeMethods()
 * Article: https://thefintechbuilder.com/price-action-and-candlesticks/multi-candle-patterns/rising-falling-three-methods/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D06-F04-A11-rising-falling-three-methods
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { risingFallingThreeMethods as run } from "./impl.ts";

export const meta = {
  id: "D06-F04-A11",
  title: "Rising/Falling Three Methods",
  slug: "rising-falling-three-methods",
  domainId: "D06",
  domain: "Price Action and Candlesticks",
  familyId: "D06-F04",
  family: "Multi-Candle Patterns",
  difficulty: 2,
  archetype: "record-transform",
  entry: "risingFallingThreeMethods",
  path: "price-action-and-candlesticks/multi-candle-patterns/rising-falling-three-methods",
  articleUrl: "https://thefintechbuilder.com/price-action-and-candlesticks/multi-candle-patterns/rising-falling-three-methods/",
  repoUrl: null,
} as const;
