// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D12-matching-engines-and-venue-logic/D12-F01-continuous-matching/D12-F01-A02-pro-rata-matching/implementations/typescript/continuous-matching.ts
// Re-run `npm run sync` after changing the catalog implementation.
//
// This family shares one implementation across its topics; the body lives at
// src/_shared/continuous-matching.ts and is re-exported here so the public surface of
// this subpath is unchanged.

export * from "../../../_shared/continuous-matching.ts";
