/**
 * Balance-Sheet Resilience Score
 *
 * Topic D18-F09-A08 · Fundamental Analysis and Valuation / Integrated Equity Scoring · difficulty 3
 * Shape: record-transform · entry: balanceSheetResilienceScore()
 * Article: https://thefintechbuilder.com/fundamental-analysis-and-valuation/integrated-equity-scoring/balance-sheet-resilience-score/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D18-F09-A08-balance-sheet-resilience-score
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { balanceSheetResilienceScore as run } from "./impl.ts";

export const meta = {
  id: "D18-F09-A08",
  title: "Balance-Sheet Resilience Score",
  slug: "balance-sheet-resilience-score",
  domainId: "D18",
  domain: "Fundamental Analysis and Valuation",
  familyId: "D18-F09",
  family: "Integrated Equity Scoring",
  difficulty: 3,
  archetype: "record-transform",
  entry: "balanceSheetResilienceScore",
  path: "fundamental-analysis-and-valuation/integrated-equity-scoring/balance-sheet-resilience-score",
  articleUrl: "https://thefintechbuilder.com/fundamental-analysis-and-valuation/integrated-equity-scoring/balance-sheet-resilience-score/",
  repoUrl: null,
} as const;
