// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D18-fundamental-analysis-and-valuation/D18-F03-relative-valuation/D18-F03-A03-price-to-book-valuation/implementations/typescript/relative-valuation.ts
// Re-run `npm run sync` after changing the catalog implementation.
//
// This family shares one implementation across its topics; the body lives at
// src/_shared/relative-valuation.ts and is re-exported here so the public surface of
// this subpath is unchanged.

export * from "../../../_shared/relative-valuation.ts";
