/**
 * Connors RSI
 *
 * Topic D07-F03-A08 · Technical Indicators / Momentum · difficulty 4
 * Shape: series-transform · entry: connorsRsi()
 * Article: https://thefintechbuilder.com/technical-indicators/momentum/connors-rsi/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F03-A08-connors-rsi
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { connorsRsi as run } from "./impl.ts";

export const meta = {
  id: "D07-F03-A08",
  title: "Connors RSI",
  slug: "connors-rsi",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F03",
  family: "Momentum",
  difficulty: 4,
  archetype: "series-transform",
  entry: "connorsRsi",
  path: "technical-indicators/momentum/connors-rsi",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/momentum/connors-rsi/",
  repoUrl: null,
} as const;
