/**
 * Cancel/Replace Priority Rule
 *
 * Topic D12-F04-A02 · Matching Engines and Venue Logic / Order Lifecycle and Queue State · difficulty 4
 * Shape: record-transform · entry: cancelReplacePriority()
 * Article: https://thefintechbuilder.com/matching-engines-and-venue-logic/order-lifecycle-and-queue-state/cancel-replace-priority-rule/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D12-F04-A02-cancel-replace-priority-rule
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { cancelReplacePriority as run } from "./impl.ts";

export const meta = {
  id: "D12-F04-A02",
  title: "Cancel/Replace Priority Rule",
  slug: "cancel-replace-priority-rule",
  domainId: "D12",
  domain: "Matching Engines and Venue Logic",
  familyId: "D12-F04",
  family: "Order Lifecycle and Queue State",
  difficulty: 4,
  archetype: "record-transform",
  entry: "cancelReplacePriority",
  path: "matching-engines-and-venue-logic/order-lifecycle-and-queue-state/cancel-replace-priority-rule",
  articleUrl: "https://thefintechbuilder.com/matching-engines-and-venue-logic/order-lifecycle-and-queue-state/cancel-replace-priority-rule/",
  repoUrl: null,
} as const;
