/**
 * Swing Structure Detector
 *
 * Topic D08-F07-A15 · Geometric Chart Patterns / Market Structure, Breakouts, and Regimes · difficulty 2
 * Shape: record-transform · entry: swingStructureDetector()
 * Article: https://thefintechbuilder.com/geometric-chart-patterns/market-structure-breakouts-and-regimes/swing-structure-detector/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D08-F07-A15-swing-structure-detector
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { swingStructureDetector as run } from "./impl.ts";

export const meta = {
  id: "D08-F07-A15",
  title: "Swing Structure Detector",
  slug: "swing-structure-detector",
  domainId: "D08",
  domain: "Geometric Chart Patterns",
  familyId: "D08-F07",
  family: "Market Structure, Breakouts, and Regimes",
  difficulty: 2,
  archetype: "record-transform",
  entry: "swingStructureDetector",
  path: "geometric-chart-patterns/market-structure-breakouts-and-regimes/swing-structure-detector",
  articleUrl: "https://thefintechbuilder.com/geometric-chart-patterns/market-structure-breakouts-and-regimes/swing-structure-detector/",
  repoUrl: null,
} as const;
