// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D21-credit-risk-and-default/D21-F01-probability-of-default/D21-F01-A06-campbell-hilscher-szilagyi-distress-probability/implementations/typescript/probability-of-default.ts
// Re-run `npm run sync` after changing the catalog implementation.
//
// This family shares one implementation across its topics; the body lives at
// src/_shared/probability-of-default.ts and is re-exported here so the public surface of
// this subpath is unchanged.

export * from "../../../_shared/probability-of-default.ts";
