// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F01-trend-smoothing/D07-F01-A13-arnaud-legoux-moving-average-alma/implementations/typescript/arnaud_legoux_moving_average_alma.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F01-A13: Arnaud Legoux Moving Average (ALMA). */
import { arnaudLegouxMovingAverageAlma as nativeArnaudLegouxMovingAverageAlma, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F01-A13";
export const TITLE = "Arnaud Legoux Moving Average (ALMA)";

export function arnaudLegouxMovingAverageAlma(input: TopicInput): TopicResult {
  return nativeArnaudLegouxMovingAverageAlma(input);
}
