/**
 * Contextual Candlestick Confidence Score
 *
 * Topic D06-F05-A04 · Price Action and Candlesticks / Candlestick Scanning and Context · difficulty 3
 * Shape: record-transform · entry: scoreContext()
 * Article: https://thefintechbuilder.com/price-action-and-candlesticks/candlestick-scanning-and-context/contextual-candlestick-confidence-score/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D06-F05-A04-contextual-candlestick-confidence-score
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { scoreContext as run } from "./impl.ts";

export const meta = {
  id: "D06-F05-A04",
  title: "Contextual Candlestick Confidence Score",
  slug: "contextual-candlestick-confidence-score",
  domainId: "D06",
  domain: "Price Action and Candlesticks",
  familyId: "D06-F05",
  family: "Candlestick Scanning and Context",
  difficulty: 3,
  archetype: "record-transform",
  entry: "scoreContext",
  path: "price-action-and-candlesticks/candlestick-scanning-and-context/contextual-candlestick-confidence-score",
  articleUrl: "https://thefintechbuilder.com/price-action-and-candlesticks/candlestick-scanning-and-context/contextual-candlestick-confidence-score/",
  repoUrl: null,
} as const;
