/**
 * Level-2 Snapshot-and-Delta Reconstruction
 *
 * Topic D01-F05-A02 · Market Data Engineering / Order-Book Feed Engineering · difficulty 3
 * Shape: record-transform · entry: reconstructL2()
 * Article: https://thefintechbuilder.com/market-data-engineering/order-book-feed-engineering/level-2-snapshot-and-delta-reconstruction/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D01-F05-A02-level-2-snapshot-and-delta-reconstruction
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { reconstructL2 as run } from "./impl.ts";

export const meta = {
  id: "D01-F05-A02",
  title: "Level-2 Snapshot-and-Delta Reconstruction",
  slug: "level-2-snapshot-and-delta-reconstruction",
  domainId: "D01",
  domain: "Market Data Engineering",
  familyId: "D01-F05",
  family: "Order-Book Feed Engineering",
  difficulty: 3,
  archetype: "record-transform",
  entry: "reconstructL2",
  path: "market-data-engineering/order-book-feed-engineering/level-2-snapshot-and-delta-reconstruction",
  articleUrl: "https://thefintechbuilder.com/market-data-engineering/order-book-feed-engineering/level-2-snapshot-and-delta-reconstruction/",
  repoUrl: null,
} as const;
