/**
 * Missing, Nonfinite, Censored, and Truncated Values
 *
 * Topic D00-F03-A07 · Financial Mathematics, Statistics, and Data Foundations / Data, Variables, Samples, and Measurement · difficulty 1
 * Shape: record-transform · entry: missingNonfiniteCensoredAndTruncatedValues()
 * Article: https://thefintechbuilder.com/foundations/data-variables-samples-and-measurement/missing-nonfinite-censored-and-truncated-values/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F03-A07-missing-nonfinit
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { missingNonfiniteCensoredAndTruncatedValues as run } from "./impl.ts";

export const meta = {
  id: "D00-F03-A07",
  title: "Missing, Nonfinite, Censored, and Truncated Values",
  slug: "missing-nonfinite-censored-and-truncated-values",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F03",
  family: "Data, Variables, Samples, and Measurement",
  difficulty: 1,
  archetype: "record-transform",
  entry: "missingNonfiniteCensoredAndTruncatedValues",
  path: "foundations/data-variables-samples-and-measurement/missing-nonfinite-censored-and-truncated-values",
  articleUrl: "https://thefintechbuilder.com/foundations/data-variables-samples-and-measurement/missing-nonfinite-censored-and-truncated-values/",
  repoUrl: null,
} as const;
