/**
 * Provider Adjustment-Basis Drift Detector
 *
 * Topic D01-F04-A06 · Market Data Engineering / Data Quality · difficulty 4
 * Shape: row-classify · entry: detectAdjustmentBasisDrift()
 * Article: https://thefintechbuilder.com/market-data-engineering/data-quality/provider-adjustment-basis-drift-detector/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D01-F04-A06-provider-adjustment-basis-drift-detector
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { detectAdjustmentBasisDrift as run } from "./impl.ts";

export const meta = {
  id: "D01-F04-A06",
  title: "Provider Adjustment-Basis Drift Detector",
  slug: "provider-adjustment-basis-drift-detector",
  domainId: "D01",
  domain: "Market Data Engineering",
  familyId: "D01-F04",
  family: "Data Quality",
  difficulty: 4,
  archetype: "row-classify",
  entry: "detectAdjustmentBasisDrift",
  path: "market-data-engineering/data-quality/provider-adjustment-basis-drift-detector",
  articleUrl: "https://thefintechbuilder.com/market-data-engineering/data-quality/provider-adjustment-basis-drift-detector/",
  repoUrl: null,
} as const;
