// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F01-trend-smoothing/D07-F01-A18-mcginley-dynamic/implementations/typescript/mcginley_dynamic.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F01-A18: McGinley Dynamic. */
import { mcginleyDynamic as nativeMcginleyDynamic, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F01-A18";
export const TITLE = "McGinley Dynamic";

export function mcginleyDynamic(input: TopicInput): TopicResult {
  return nativeMcginleyDynamic(input);
}
