/**
 * Parabolic SAR: Audit the Stop, Extreme Point, and Acceleration Factor
 *
 * Topic D07-F02-A07 · Technical Indicators / Trend Systems · difficulty 3
 * Shape: series-transform · entry: parabolic_sar()
 * Article: https://thefintechbuilder.com/technical-indicators/trend-systems/parabolic-sar/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F02-A07-parabolic-sar
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { parabolic_sar as run } from "./impl.ts";

export const meta = {
  id: "D07-F02-A07",
  title: "Parabolic SAR: Audit the Stop, Extreme Point, and Acceleration Factor",
  slug: "parabolic-sar",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F02",
  family: "Trend Systems",
  difficulty: 3,
  archetype: "series-transform",
  entry: "parabolic_sar",
  path: "technical-indicators/trend-systems/parabolic-sar",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/trend-systems/parabolic-sar/",
  repoUrl: null,
} as const;
