/**
 * Factor-Model Covariance
 *
 * Topic D10-F04-A05 · Volatility and Covariance / Covariance Estimation · difficulty 3
 * Shape: record-transform · entry: calculate()
 * Article: https://thefintechbuilder.com/volatility-and-covariance/covariance-estimation/factor-model-covariance/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D10-F04-A05-factor-model-covariance
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { calculate as run } from "./impl.ts";

export const meta = {
  id: "D10-F04-A05",
  title: "Factor-Model Covariance",
  slug: "factor-model-covariance",
  domainId: "D10",
  domain: "Volatility and Covariance",
  familyId: "D10-F04",
  family: "Covariance Estimation",
  difficulty: 3,
  archetype: "record-transform",
  entry: "calculate",
  path: "volatility-and-covariance/covariance-estimation/factor-model-covariance",
  articleUrl: "https://thefintechbuilder.com/volatility-and-covariance/covariance-estimation/factor-model-covariance/",
  repoUrl: null,
} as const;
