/**
 * Tax-Aware Portfolio Optimization
 *
 * Topic D14-F04-A05 · Portfolio Construction / Practical Constraints · difficulty 4
 * Shape: record-transform · entry: optimizeTaxAwareTrade()
 * Article: https://thefintechbuilder.com/portfolio-construction/practical-constraints/tax-aware-portfolio-optimization/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D14-F04-A05-tax-aware-portfolio-optimization
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { optimizeTaxAwareTrade as run } from "./impl.ts";

export const meta = {
  id: "D14-F04-A05",
  title: "Tax-Aware Portfolio Optimization",
  slug: "tax-aware-portfolio-optimization",
  domainId: "D14",
  domain: "Portfolio Construction",
  familyId: "D14-F04",
  family: "Practical Constraints",
  difficulty: 4,
  archetype: "record-transform",
  entry: "optimizeTaxAwareTrade",
  path: "portfolio-construction/practical-constraints/tax-aware-portfolio-optimization",
  articleUrl: "https://thefintechbuilder.com/portfolio-construction/practical-constraints/tax-aware-portfolio-optimization/",
  repoUrl: null,
} as const;
