/**
 * Relative Volume
 *
 * Topic D07-F05-A17 · Technical Indicators / Volume Indicators · difficulty 2
 * Shape: series-transform · entry: relativeVolume()
 * Article: https://thefintechbuilder.com/technical-indicators/volume-indicators/relative-volume/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F05-A17-relative-volume
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { relativeVolume as run } from "./impl.ts";

export const meta = {
  id: "D07-F05-A17",
  title: "Relative Volume",
  slug: "relative-volume",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F05",
  family: "Volume Indicators",
  difficulty: 2,
  archetype: "series-transform",
  entry: "relativeVolume",
  path: "technical-indicators/volume-indicators/relative-volume",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/volume-indicators/relative-volume/",
  repoUrl: null,
} as const;
