// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F03-momentum/D07-F03-A10-rate-of-change-variants-roc-rocp-and-rocr/implementations/typescript/rate_of_change_variants_roc_rocp_and_rocr.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F03-A10: Rate-of-Change Variants (ROC, ROCP, and ROCR). */
import { rateOfChangeVariantsRocRocpAndRocr as nativeRateOfChangeVariantsRocRocpAndRocr, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F03-A10";
export const TITLE = "Rate-of-Change Variants (ROC, ROCP, and ROCR)";

export function rateOfChangeVariantsRocRocpAndRocr(input: TopicInput): TopicResult {
  return nativeRateOfChangeVariantsRocRocpAndRocr(input);
}
