/**
 * Rate-of-Change Variants (ROC, ROCP, and ROCR)
 *
 * Topic D07-F03-A10 · Technical Indicators / Momentum · difficulty 2
 * Shape: series-transform · entry: rateOfChangeVariantsRocRocpAndRocr()
 * Article: https://thefintechbuilder.com/technical-indicators/momentum/rate-of-change-variants-roc-rocp-and-rocr/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F03-A10-rate-of-change-variants-roc-rocp-and-rocr
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { rateOfChangeVariantsRocRocpAndRocr as run } from "./impl.ts";

export const meta = {
  id: "D07-F03-A10",
  title: "Rate-of-Change Variants (ROC, ROCP, and ROCR)",
  slug: "rate-of-change-variants-roc-rocp-and-rocr",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F03",
  family: "Momentum",
  difficulty: 2,
  archetype: "series-transform",
  entry: "rateOfChangeVariantsRocRocpAndRocr",
  path: "technical-indicators/momentum/rate-of-change-variants-roc-rocp-and-rocr",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/momentum/rate-of-change-variants-roc-rocp-and-rocr/",
  repoUrl: null,
} as const;
