/**
 * Stock Score History, Migration, and Change Attribution
 *
 * Topic D18-F09-A14 · Fundamental Analysis and Valuation / Integrated Equity Scoring · difficulty 4
 * Shape: record-transform · entry: stockScoreHistoryMigrationAndChangeAttribution()
 * Article: https://thefintechbuilder.com/fundamental-analysis-and-valuation/integrated-equity-scoring/stock-score-history-migration-and-change-attribution/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D18-F09-A14-stock-score-history-migration-and-change-attribution
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { stockScoreHistoryMigrationAndChangeAttribution as run } from "./impl.ts";

export const meta = {
  id: "D18-F09-A14",
  title: "Stock Score History, Migration, and Change Attribution",
  slug: "stock-score-history-migration-and-change-attribution",
  domainId: "D18",
  domain: "Fundamental Analysis and Valuation",
  familyId: "D18-F09",
  family: "Integrated Equity Scoring",
  difficulty: 4,
  archetype: "record-transform",
  entry: "stockScoreHistoryMigrationAndChangeAttribution",
  path: "fundamental-analysis-and-valuation/integrated-equity-scoring/stock-score-history-migration-and-change-attribution",
  articleUrl: "https://thefintechbuilder.com/fundamental-analysis-and-valuation/integrated-equity-scoring/stock-score-history-migration-and-change-attribution/",
  repoUrl: null,
} as const;
