/**
 * Dechow F-Score for Misstatement Risk
 *
 * Topic D18-F04-A11 · Fundamental Analysis and Valuation / Quality and Distress · difficulty 4
 * Shape: record-transform · entry: dechowFScoreForMisstatementRisk()
 * Article: https://thefintechbuilder.com/fundamental-analysis-and-valuation/quality-and-distress/dechow-f-score-for-misstatement-risk/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D18-F04-A11-dechow-f-score-for-misstatement-risk
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { dechowFScoreForMisstatementRisk as run } from "./impl.ts";

export const meta = {
  id: "D18-F04-A11",
  title: "Dechow F-Score for Misstatement Risk",
  slug: "dechow-f-score-for-misstatement-risk",
  domainId: "D18",
  domain: "Fundamental Analysis and Valuation",
  familyId: "D18-F04",
  family: "Quality and Distress",
  difficulty: 4,
  archetype: "record-transform",
  entry: "dechowFScoreForMisstatementRisk",
  path: "fundamental-analysis-and-valuation/quality-and-distress/dechow-f-score-for-misstatement-risk",
  articleUrl: "https://thefintechbuilder.com/fundamental-analysis-and-valuation/quality-and-distress/dechow-f-score-for-misstatement-risk/",
  repoUrl: null,
} as const;
