/**
 * Rights-Issue Bonus-Factor Adjustment
 *
 * Topic D46-F01-A07 · Earnings and Per-Share Analytics / Earnings and Share Foundations · difficulty 3
 * Shape: record-transform · entry: rightsIssueBonusFactorAdjustment()
 * Article: https://thefintechbuilder.com/earnings-and-per-share-analytics/earnings-and-share-foundations/rights-issue-bonus-factor-adjustment/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D46-F01-A07-rights-issue-bonus-factor-adjustment
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { rightsIssueBonusFactorAdjustment as run } from "./impl.ts";

export const meta = {
  id: "D46-F01-A07",
  title: "Rights-Issue Bonus-Factor Adjustment",
  slug: "rights-issue-bonus-factor-adjustment",
  domainId: "D46",
  domain: "Earnings and Per-Share Analytics",
  familyId: "D46-F01",
  family: "Earnings and Share Foundations",
  difficulty: 3,
  archetype: "record-transform",
  entry: "rightsIssueBonusFactorAdjustment",
  path: "earnings-and-per-share-analytics/earnings-and-share-foundations/rights-issue-bonus-factor-adjustment",
  articleUrl: "https://thefintechbuilder.com/earnings-and-per-share-analytics/earnings-and-share-foundations/rights-issue-bonus-factor-adjustment/",
  repoUrl: null,
} as const;
