/**
 * Count, Sum, Minimum, Maximum, and Range
 *
 * Topic D00-F04-A01 · Financial Mathematics, Statistics, and Data Foundations / Location, Ranking, and Exploratory Summaries · difficulty 1
 * Shape: record-transform · entry: countSumMinimumMaximumAndRange()
 * Article: https://thefintechbuilder.com/foundations/location-ranking-and-exploratory-summaries/count-sum-minimum-maximum-and-range/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F04-A01-count-sum-minimu
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { countSumMinimumMaximumAndRange as run } from "./impl.ts";

export const meta = {
  id: "D00-F04-A01",
  title: "Count, Sum, Minimum, Maximum, and Range",
  slug: "count-sum-minimum-maximum-and-range",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F04",
  family: "Location, Ranking, and Exploratory Summaries",
  difficulty: 1,
  archetype: "record-transform",
  entry: "countSumMinimumMaximumAndRange",
  path: "foundations/location-ranking-and-exploratory-summaries/count-sum-minimum-maximum-and-range",
  articleUrl: "https://thefintechbuilder.com/foundations/location-ranking-and-exploratory-summaries/count-sum-minimum-maximum-and-range/",
  repoUrl: null,
} as const;
