/**
 * Conditional Probability
 *
 * Topic D00-F06-A03 · Financial Mathematics, Statistics, and Data Foundations / Probability and Random Variables · difficulty 1
 * Shape: record-transform · entry: conditionalProbability()
 * Article: https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/probability-and-random-variables/conditional-probability/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F06-A03-conditional-prob
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { conditionalProbability as run } from "./impl.ts";

export const meta = {
  id: "D00-F06-A03",
  title: "Conditional Probability",
  slug: "conditional-probability",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F06",
  family: "Probability and Random Variables",
  difficulty: 1,
  archetype: "record-transform",
  entry: "conditionalProbability",
  path: "financial-mathematics-statistics-and-data-foundations/probability-and-random-variables/conditional-probability",
  articleUrl: "https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/probability-and-random-variables/conditional-probability/",
  repoUrl: null,
} as const;
