// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F05-volume-indicators/D07-F05-A13-klinger-volume-oscillator/implementations/typescript/klinger_volume_oscillator.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F05-A13: Klinger Volume Oscillator. */
import { klingerVolumeOscillator as nativeKlingerVolumeOscillator, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F05-A13";
export const TITLE = "Klinger Volume Oscillator";

export function klingerVolumeOscillator(input: TopicInput): TopicResult {
  return nativeKlingerVolumeOscillator(input);
}
