/**
 * VPIN
 *
 * Topic D11-F03-A06 · Market Microstructure / Order-Flow and Impact · difficulty 5
 * Shape: record-transform · entry: vpin()
 * Article: https://thefintechbuilder.com/market-microstructure/order-flow-and-impact/vpin/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D11-F03-A06-vpin
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { vpin as run } from "./impl.ts";

export const meta = {
  id: "D11-F03-A06",
  title: "VPIN",
  slug: "vpin",
  domainId: "D11",
  domain: "Market Microstructure",
  familyId: "D11-F03",
  family: "Order-Flow and Impact",
  difficulty: 5,
  archetype: "record-transform",
  entry: "vpin",
  path: "market-microstructure/order-flow-and-impact/vpin",
  articleUrl: "https://thefintechbuilder.com/market-microstructure/order-flow-and-impact/vpin/",
  repoUrl: null,
} as const;
