/**
 * Close-to-Close Volatility
 *
 * Topic D10-F01-A01 · Volatility and Covariance / Historical Estimators · difficulty 1
 * Shape: record-transform · entry: calculate()
 * Article: https://thefintechbuilder.com/volatility-and-covariance/historical-estimators/close-to-close-volatility/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D10-F01-A01-close-to-close-volatility
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { calculate as run } from "./impl.ts";

export const meta = {
  id: "D10-F01-A01",
  title: "Close-to-Close Volatility",
  slug: "close-to-close-volatility",
  domainId: "D10",
  domain: "Volatility and Covariance",
  familyId: "D10-F01",
  family: "Historical Estimators",
  difficulty: 1,
  archetype: "record-transform",
  entry: "calculate",
  path: "volatility-and-covariance/historical-estimators/close-to-close-volatility",
  articleUrl: "https://thefintechbuilder.com/volatility-and-covariance/historical-estimators/close-to-close-volatility/",
  repoUrl: null,
} as const;
