// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D08-geometric-chart-patterns/D08-F04-pattern-matching/D08-F04-A04-shapelet-pattern-classifier/implementations/typescript/algorithm.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Topic facade for D08-F04-A04 — Shapelet Pattern Classifier. */
import { classifyShapelet, shapeletDistance, trainShapeletThreshold } from "../../../_shared/matching.ts";
export const train = (series: number[][], labels: boolean[], shapelet: number[]) => trainShapeletThreshold(series, labels, shapelet);
export const classify = (series: number[], shapelet: number[], threshold: number, belowLabel = true) => classifyShapelet(series, shapelet, threshold, belowLabel);
export const distance = (series: number[], shapelet: number[]) => shapeletDistance(series, shapelet);
