/**
 * If-Converted Convertible-Debt Dilution
 *
 * Topic D46-F02-A01 · Earnings and Per-Share Analytics / Basic and Diluted EPS · difficulty 3
 * Shape: record-transform · entry: ifConvertedConvertibleDebtDilution()
 * Article: https://thefintechbuilder.com/earnings-and-per-share-analytics/basic-and-diluted-eps/if-converted-convertible-debt-dilution/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D46-F02-A01-if-converted-convertible-debt-dilution
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { ifConvertedConvertibleDebtDilution as run } from "./impl.ts";

export const meta = {
  id: "D46-F02-A01",
  title: "If-Converted Convertible-Debt Dilution",
  slug: "if-converted-convertible-debt-dilution",
  domainId: "D46",
  domain: "Earnings and Per-Share Analytics",
  familyId: "D46-F02",
  family: "Basic and Diluted EPS",
  difficulty: 3,
  archetype: "record-transform",
  entry: "ifConvertedConvertibleDebtDilution",
  path: "earnings-and-per-share-analytics/basic-and-diluted-eps/if-converted-convertible-debt-dilution",
  articleUrl: "https://thefintechbuilder.com/earnings-and-per-share-analytics/basic-and-diluted-eps/if-converted-convertible-debt-dilution/",
  repoUrl: null,
} as const;
