/**
 * Arithmetic Mean
 *
 * Topic D00-F04-A02 · Financial Mathematics, Statistics, and Data Foundations / Location, Ranking, and Exploratory Summaries · difficulty 1
 * Shape: record-transform · entry: arithmeticMean()
 * Article: https://thefintechbuilder.com/foundations/location-ranking-and-exploratory-summaries/arithmetic-mean/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F04-A02-arithmetic-mean
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { arithmeticMean as run } from "./impl.ts";

export const meta = {
  id: "D00-F04-A02",
  title: "Arithmetic Mean",
  slug: "arithmetic-mean",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F04",
  family: "Location, Ranking, and Exploratory Summaries",
  difficulty: 1,
  archetype: "record-transform",
  entry: "arithmeticMean",
  path: "foundations/location-ranking-and-exploratory-summaries/arithmetic-mean",
  articleUrl: "https://thefintechbuilder.com/foundations/location-ranking-and-exploratory-summaries/arithmetic-mean/",
  repoUrl: null,
} as const;
