/**
 * Exponential, Gamma, and Weibull Waiting-Time Models
 *
 * Topic D00-F07-A08 · Financial Mathematics, Statistics, and Data Foundations / Probability Distributions and Simulation Basics · difficulty 1
 * Shape: record-transform · entry: exponentialGammaAndWeibullWaitingTimeModels()
 * Article: https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/probability-distributions-and-simulation-basics/exponential-gamma-and-weibull-waiting-time-models/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F07-A08-exponential-gamm
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { exponentialGammaAndWeibullWaitingTimeModels as run } from "./impl.ts";

export const meta = {
  id: "D00-F07-A08",
  title: "Exponential, Gamma, and Weibull Waiting-Time Models",
  slug: "exponential-gamma-and-weibull-waiting-time-models",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F07",
  family: "Probability Distributions and Simulation Basics",
  difficulty: 1,
  archetype: "record-transform",
  entry: "exponentialGammaAndWeibullWaitingTimeModels",
  path: "financial-mathematics-statistics-and-data-foundations/probability-distributions-and-simulation-basics/exponential-gamma-and-weibull-waiting-time-models",
  articleUrl: "https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/probability-distributions-and-simulation-basics/exponential-gamma-and-weibull-waiting-time-models/",
  repoUrl: null,
} as const;
