// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F04-volatility-and-channels/D07-F04-A03-bollinger-bands/implementations/typescript/volatility_channels.ts
// Re-run `npm run sync` after changing the catalog implementation.

function finite(v:number[],n:string){if(!Array.isArray(v)||!v.length||v.some(x=>!Number.isFinite(x)))throw new Error(`${n} must contain finite numbers`)}
function hlc(h:number[],l:number[],c:number[]){finite(h,"high");finite(l,"low");finite(c,"close");if(h.length!==l.length||h.length!==c.length)throw new Error("high, low, and close lengths must match");if(h.some((x,i)=>x<l[i]||c[i]<l[i]||c[i]>x))throw new Error("each bar requires low <= close <= high")}


function period(v:number,n="period"){if(!Number.isInteger(v)||v<1)throw new Error(`${n} must be a positive integer`)}

function rolling(close:number[],p:number){period(p);finite(close,"close");const middle:(number|null)[]=Array(close.length).fill(null),stddev:(number|null)[]=Array(close.length).fill(null);for(let i=p-1;i<close.length;i++){const w=close.slice(i-p+1,i+1),m=w.reduce((a,b)=>a+b,0)/p;middle[i]=m;stddev[i]=Math.sqrt(w.reduce((a,b)=>a+(b-m)**2,0)/p)}return{middle,stddev}}
export function bollingerBands(close:number[],p=20,multiplier=2){if(!Number.isFinite(multiplier)||multiplier<=0)throw new Error("multiplier must be finite and positive");const r=rolling(close,p),upper:(number|null)[]=Array(close.length).fill(null),lower:(number|null)[]=Array(close.length).fill(null),percent_b:(number|null)[]=Array(close.length).fill(null);for(let i=0;i<close.length;i++){if(r.middle[i]===null)continue;upper[i]=(r.middle[i] as number)+multiplier*(r.stddev[i] as number);lower[i]=(r.middle[i] as number)-multiplier*(r.stddev[i] as number);const width=(upper[i] as number)-(lower[i] as number);percent_b[i]=width===0?null:(close[i]-(lower[i] as number))/width}return{middle:r.middle,stddev:r.stddev,upper,lower,percent_b}}
