/**
 * Bollinger Bands
 *
 * Topic D07-F04-A03 · Technical Indicators / Volatility and Channels · difficulty 2
 * Shape: series-transform · entry: bollingerBands()
 * Article: https://thefintechbuilder.com/technical-indicators/volatility-and-channels/bollinger-bands/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F04-A03-bollinger-bands
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { bollingerBands as run } from "./impl.ts";

export const meta = {
  id: "D07-F04-A03",
  title: "Bollinger Bands",
  slug: "bollinger-bands",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F04",
  family: "Volatility and Channels",
  difficulty: 2,
  archetype: "series-transform",
  entry: "bollingerBands",
  path: "technical-indicators/volatility-and-channels/bollinger-bands",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/volatility-and-channels/bollinger-bands/",
  repoUrl: null,
} as const;
