// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F01-trend-smoothing/D07-F01-A04-wilder-rma/implementations/typescript/rma.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** SMA-seeded Wilder moving average (RMA) for D07-F01-A04. */

export class RMAValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RMAValidationError";
  }
}

export function calculateRma(
  values: readonly number[],
  period: number,
): Array<number | null> {
  if (!Number.isSafeInteger(period) || period < 1) {
    throw new RMAValidationError("period must be a positive integer.");
  }
  if (!Array.isArray(values)) {
    throw new RMAValidationError("values must be an array.");
  }

  const numbers = values.map((value, index) => {
    if (typeof value !== "number" || !Number.isFinite(value)) {
      throw new RMAValidationError(`values[${index}] must be a finite number.`);
    }
    return value;
  });

  const alpha = 1 / period;
  const output: Array<number | null> = [];
  let seedSum = 0;
  let rma: number | null = null;

  numbers.forEach((value, zeroBasedIndex) => {
    const observation = zeroBasedIndex + 1;
    if (observation <= period) seedSum += value;
    if (observation < period) {
      output.push(null);
    } else if (observation === period) {
      rma = seedSum / period;
      output.push(rma);
    } else {
      rma = (rma as number) + alpha * (value - (rma as number));
      output.push(rma);
    }
  });
  return output;
}
