/**
 * Insurance Fundamental Score
 *
 * Topic D18-F10-A02 · Fundamental Analysis and Valuation / Sector-Specific Equity Scoring · difficulty 4
 * Shape: record-transform · entry: insuranceFundamentalScore()
 * Article: https://thefintechbuilder.com/fundamental-analysis-and-valuation/sector-specific-equity-scoring/insurance-fundamental-score/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D18-F10-A02-insurance-fundamental-score
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { insuranceFundamentalScore as run } from "./impl.ts";

export const meta = {
  id: "D18-F10-A02",
  title: "Insurance Fundamental Score",
  slug: "insurance-fundamental-score",
  domainId: "D18",
  domain: "Fundamental Analysis and Valuation",
  familyId: "D18-F10",
  family: "Sector-Specific Equity Scoring",
  difficulty: 4,
  archetype: "record-transform",
  entry: "insuranceFundamentalScore",
  path: "fundamental-analysis-and-valuation/sector-specific-equity-scoring/insurance-fundamental-score",
  articleUrl: "https://thefintechbuilder.com/fundamental-analysis-and-valuation/sector-specific-equity-scoring/insurance-fundamental-score/",
  repoUrl: null,
} as const;
