/**
 * Fractal Adaptive Moving Average (FRAMA)
 *
 * Topic D07-F01-A14 · Technical Indicators / Trend Smoothing · difficulty 2
 * Shape: series-transform · entry: fractalAdaptiveMovingAverageFrama()
 * Article: https://thefintechbuilder.com/technical-indicators/trend-smoothing/fractal-adaptive-moving-average-frama/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F01-A14-fractal-adaptive-moving-average-frama
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { fractalAdaptiveMovingAverageFrama as run } from "./impl.ts";

export const meta = {
  id: "D07-F01-A14",
  title: "Fractal Adaptive Moving Average (FRAMA)",
  slug: "fractal-adaptive-moving-average-frama",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F01",
  family: "Trend Smoothing",
  difficulty: 2,
  archetype: "series-transform",
  entry: "fractalAdaptiveMovingAverageFrama",
  path: "technical-indicators/trend-smoothing/fractal-adaptive-moving-average-frama",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/trend-smoothing/fractal-adaptive-moving-average-frama/",
  repoUrl: null,
} as const;
