/**
 * Residuals, MAE, MSE, and RMSE
 *
 * Topic D00-F09-A08 · Financial Mathematics, Statistics, and Data Foundations / Dependence, Regression, and Model Foundations · difficulty 1
 * Shape: record-transform · entry: residualsMaeMseAndRmse()
 * Article: https://thefintechbuilder.com/foundations/dependence-regression-and-model-foundations/residuals-mae-mse-and-rmse/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F09-A08-residuals-mae-ms
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { residualsMaeMseAndRmse as run } from "./impl.ts";

export const meta = {
  id: "D00-F09-A08",
  title: "Residuals, MAE, MSE, and RMSE",
  slug: "residuals-mae-mse-and-rmse",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F09",
  family: "Dependence, Regression, and Model Foundations",
  difficulty: 1,
  archetype: "record-transform",
  entry: "residualsMaeMseAndRmse",
  path: "foundations/dependence-regression-and-model-foundations/residuals-mae-mse-and-rmse",
  articleUrl: "https://thefintechbuilder.com/foundations/dependence-regression-and-model-foundations/residuals-mae-mse-and-rmse/",
  repoUrl: null,
} as const;
