/**
 * Triple Bottom
 *
 * Topic D08-F02-A04 · Geometric Chart Patterns / Reversal Structures · difficulty 3
 * Shape: record-transform · entry: triple_bottom()
 * Article: https://thefintechbuilder.com/geometric-chart-patterns/reversal-structures/triple-bottom/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D08-F02-A04-triple-bottom
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { triple_bottom as run } from "./impl.ts";

export const meta = {
  id: "D08-F02-A04",
  title: "Triple Bottom",
  slug: "triple-bottom",
  domainId: "D08",
  domain: "Geometric Chart Patterns",
  familyId: "D08-F02",
  family: "Reversal Structures",
  difficulty: 3,
  archetype: "record-transform",
  entry: "triple_bottom",
  path: "geometric-chart-patterns/reversal-structures/triple-bottom",
  articleUrl: "https://thefintechbuilder.com/geometric-chart-patterns/reversal-structures/triple-bottom/",
  repoUrl: null,
} as const;
