// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D09-statistical-time-series/D09-F02-forecast-models/D09-F02-A02-arma/implementations/typescript/arma.ts
// Re-run `npm run sync` after changing the catalog implementation.


type ForecastResult = {
  forecast:number[];
  fitted:(number|null)[];
  residuals?:number[];
  state:Record<string,unknown>;
  [key:string]:unknown;
};
const finite=(value:number,name:string)=>{
  if(typeof value!=="number"||!Number.isFinite(value))throw new Error(`${name} must be finite`);
  return value;
};
const positiveInt=(value:number,name:string,min=1)=>{
  if(!Number.isInteger(value)||value<min)throw new Error(`${name} must be an integer >= ${min}`);
  return value;
};
const series=(values:number[],minimum=2)=>{
  if(!Array.isArray(values)||values.length<minimum)throw new Error(`values must contain at least ${minimum} observations`);
  return values.map((value,index)=>finite(value,`values[${index}]`));
};
const coefficients=(values:number[],name:string,allowEmpty=true)=>{
  if(!Array.isArray(values)||(!allowEmpty&&values.length===0))throw new Error(`${name} must be a coefficient list`);
  return values.map((value,index)=>finite(value,`${name}[${index}]`));
};

function armaCore(values:number[],ar:number[],ma:number[],intercept:number,horizon:number):ForecastResult{
  const a=coefficients(ar,"ar"),m=coefficients(ma,"ma");
  if(a.length===0&&m.length===0)throw new Error("at least one AR or MA coefficient is required");
  const p=a.length,q=m.length,y=series(values,Math.max(p+2,q+2,3)),c=finite(intercept,"intercept"),H=positiveInt(horizon,"horizon");
  const fitted:(number|null)[]=Array(y.length).fill(null),residuals:number[]=Array(y.length).fill(0);
  for(let t=p;t<y.length;t++){
    let prediction=c;
    for(let lag=1;lag<=p;lag++)prediction+=a[lag-1]*y[t-lag];
    for(let lag=1;lag<=q;lag++)if(t-lag>=0)prediction+=m[lag-1]*residuals[t-lag];
    fitted[t]=prediction;residuals[t]=y[t]-prediction;
  }
  const extended=[...y],errors=[...residuals],forecast:number[]=[];
  for(let step=0;step<H;step++){
    const t=extended.length;let prediction=c;
    for(let lag=1;lag<=p;lag++)prediction+=a[lag-1]*extended[t-lag];
    for(let lag=1;lag<=q;lag++)if(t-lag>=0)prediction+=m[lag-1]*errors[t-lag];
    extended.push(prediction);errors.push(0);forecast.push(prediction);
  }
  return {forecast,fitted,residuals,state:{order:[p,q],last_values:y.slice(-Math.max(1,p)),last_residuals:residuals.slice(-Math.max(1,q)),presample_innovations:"zero",future_innovations:"zero conditional mean"}};
}

export function forecastARMA(values:number[],ar:number[],ma:number[],intercept:number,horizon:number):ForecastResult{
  return armaCore(values,ar,ma,intercept,horizon);
}
