/**
 * Weighted-Product AMM
 *
 * Topic D25-F01-A04 · Digital Assets and On-Chain Finance / AMM Pricing · difficulty 3
 * Shape: record-transform · entry: weightedProductQuote()
 * Article: https://thefintechbuilder.com/digital-assets-and-on-chain-finance/amm-pricing/weighted-product-amm/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D25-F01-A04-weighted-product-amm
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { weightedProductQuote as run } from "./impl.ts";

export const meta = {
  id: "D25-F01-A04",
  title: "Weighted-Product AMM",
  slug: "weighted-product-amm",
  domainId: "D25",
  domain: "Digital Assets and On-Chain Finance",
  familyId: "D25-F01",
  family: "AMM Pricing",
  difficulty: 3,
  archetype: "record-transform",
  entry: "weightedProductQuote",
  path: "digital-assets-and-on-chain-finance/amm-pricing/weighted-product-amm",
  articleUrl: "https://thefintechbuilder.com/digital-assets-and-on-chain-finance/amm-pricing/weighted-product-amm/",
  repoUrl: null,
} as const;
