/**
 * Price Relative
 *
 * Topic D07-F08-A07 · Technical Indicators / Price Transforms · difficulty 2
 * Shape: series-transform · entry: priceRelative()
 * Article: https://thefintechbuilder.com/technical-indicators/price-transforms/price-relative/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F08-A07-price-relative
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { priceRelative as run } from "./impl.ts";

export const meta = {
  id: "D07-F08-A07",
  title: "Price Relative",
  slug: "price-relative",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F08",
  family: "Price Transforms",
  difficulty: 2,
  archetype: "series-transform",
  entry: "priceRelative",
  path: "technical-indicators/price-transforms/price-relative",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/price-transforms/price-relative/",
  repoUrl: null,
} as const;
