/**
 * Opening-Cross Price
 *
 * Topic D12-F02-A03 · Matching Engines and Venue Logic / Auctions · difficulty 5
 * Shape: record-transform · entry: openingCrossPrice()
 * Article: https://thefintechbuilder.com/matching-engines-and-venue-logic/auctions/opening-cross-price/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D12-F02-A03-opening-cross-price
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { openingCrossPrice as run } from "./impl.ts";

export const meta = {
  id: "D12-F02-A03",
  title: "Opening-Cross Price",
  slug: "opening-cross-price",
  domainId: "D12",
  domain: "Matching Engines and Venue Logic",
  familyId: "D12-F02",
  family: "Auctions",
  difficulty: 5,
  archetype: "record-transform",
  entry: "openingCrossPrice",
  path: "matching-engines-and-venue-logic/auctions/opening-cross-price",
  articleUrl: "https://thefintechbuilder.com/matching-engines-and-venue-logic/auctions/opening-cross-price/",
  repoUrl: null,
} as const;
