/**
 * Trend Trigger Factor
 *
 * Topic D07-F02-A17 · Technical Indicators / Trend Systems · difficulty 2
 * Shape: series-transform · entry: trendTriggerFactor()
 * Article: https://thefintechbuilder.com/technical-indicators/trend-systems/trend-trigger-factor/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F02-A17-trend-trigger-factor
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { trendTriggerFactor as run } from "./impl.ts";

export const meta = {
  id: "D07-F02-A17",
  title: "Trend Trigger Factor",
  slug: "trend-trigger-factor",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F02",
  family: "Trend Systems",
  difficulty: 2,
  archetype: "series-transform",
  entry: "trendTriggerFactor",
  path: "technical-indicators/trend-systems/trend-trigger-factor",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/trend-systems/trend-trigger-factor/",
  repoUrl: null,
} as const;
