// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D00-financial-mathematics-statistics-and-data-foundations/D00-F12-statistical-computing-and-reproducibility/D00-F12-A02-stable-summation/implementations/typescript/algorithm.ts
// Re-run `npm run sync` after changing the catalog implementation.

import { runTopic as runD00Topic, type D00Input, type D00Output } from "../../../_shared/d00Engine.ts";

/** Run the canonical D00-F12-A02 calculation. */
export function stableSummationAndMeanCalculation(input: D00Input): D00Output {
  return runD00Topic("D00-F12-A02", input);
}
