/**
 * Arms Index (TRIN)
 *
 * Topic D04-F04-A02 · Market Breadth and Internals / Thrust and Pressure · difficulty 3
 * Shape: record-transform · entry: calculate()
 * Article: https://thefintechbuilder.com/market-breadth-and-internals/thrust-and-pressure/arms-index-trin/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D04-F04-A02-arms-index-trin
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { calculate as run } from "./impl.ts";

export const meta = {
  id: "D04-F04-A02",
  title: "Arms Index (TRIN)",
  slug: "arms-index-trin",
  domainId: "D04",
  domain: "Market Breadth and Internals",
  familyId: "D04-F04",
  family: "Thrust and Pressure",
  difficulty: 3,
  archetype: "record-transform",
  entry: "calculate",
  path: "market-breadth-and-internals/thrust-and-pressure/arms-index-trin",
  articleUrl: "https://thefintechbuilder.com/market-breadth-and-internals/thrust-and-pressure/arms-index-trin/",
  repoUrl: null,
} as const;
