// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D06-price-action-and-candlesticks/D06-F03-two-candle-patterns/D06-F03-A08-tweezer-bottom/implementations/typescript/candlestick-detection.ts
// Re-run `npm run sync` after changing the catalog implementation.
//
// This family shares one implementation across its topics; the body lives at
// src/_shared/candlestick-detection.ts and is re-exported here so the public surface of
// this subpath is unchanged.

export * from "../../../_shared/candlestick-detection.ts";
