// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D08-geometric-chart-patterns/D08-F02-reversal-structures/D08-F02-A01-double-top/implementations/typescript/reversal.ts
// Re-run `npm run sync` after changing the catalog implementation.
//
// This family shares one implementation across its topics; the body lives at
// src/_shared/reversal.ts and is re-exported here so the public surface of
// this subpath is unchanged.

export * from "../../../_shared/reversal.ts";
