/**
 * Double Top
 *
 * Topic D08-F02-A01 · Geometric Chart Patterns / Reversal Structures · difficulty 2
 * Shape: record-transform · entry: doubleTop()
 * Article: https://thefintechbuilder.com/geometric-chart-patterns/reversal-structures/double-top/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D08-F02-A01-double-top
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { doubleTop as run } from "./impl.ts";

export const meta = {
  id: "D08-F02-A01",
  title: "Double Top",
  slug: "double-top",
  domainId: "D08",
  domain: "Geometric Chart Patterns",
  familyId: "D08-F02",
  family: "Reversal Structures",
  difficulty: 2,
  archetype: "record-transform",
  entry: "doubleTop",
  path: "geometric-chart-patterns/reversal-structures/double-top",
  articleUrl: "https://thefintechbuilder.com/geometric-chart-patterns/reversal-structures/double-top/",
  repoUrl: null,
} as const;
