/**
 * Arrival-Price Execution
 *
 * Topic D13-F02-A03 · Execution and Transaction Cost Analysis / Cost/Risk Optimization · difficulty 4
 * Shape: record-transform · entry: arrivalPriceExecution()
 * Article: https://thefintechbuilder.com/execution-and-transaction-cost-analysis/cost-risk-optimization/arrival-price-execution/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D13-F02-A03-arrival-price-execution
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { arrivalPriceExecution as run } from "./impl.ts";

export const meta = {
  id: "D13-F02-A03",
  title: "Arrival-Price Execution",
  slug: "arrival-price-execution",
  domainId: "D13",
  domain: "Execution and Transaction Cost Analysis",
  familyId: "D13-F02",
  family: "Cost/Risk Optimization",
  difficulty: 4,
  archetype: "record-transform",
  entry: "arrivalPriceExecution",
  path: "execution-and-transaction-cost-analysis/cost-risk-optimization/arrival-price-execution",
  articleUrl: "https://thefintechbuilder.com/execution-and-transaction-cost-analysis/cost-risk-optimization/arrival-price-execution/",
  repoUrl: null,
} as const;
