/**
 * Depth-at-Distance Profile
 *
 * Topic D11-F05-A03 · Market Microstructure / Market-Depth Analytics · difficulty 3
 * Shape: record-transform · entry: depthAtDistanceProfile()
 * Article: https://thefintechbuilder.com/market-microstructure/market-depth-analytics/depth-at-distance-profile/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D11-F05-A03-depth-at-distance-profile
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { depthAtDistanceProfile as run } from "./impl.ts";

export const meta = {
  id: "D11-F05-A03",
  title: "Depth-at-Distance Profile",
  slug: "depth-at-distance-profile",
  domainId: "D11",
  domain: "Market Microstructure",
  familyId: "D11-F05",
  family: "Market-Depth Analytics",
  difficulty: 3,
  archetype: "record-transform",
  entry: "depthAtDistanceProfile",
  path: "market-microstructure/market-depth-analytics/depth-at-distance-profile",
  articleUrl: "https://thefintechbuilder.com/market-microstructure/market-depth-analytics/depth-at-distance-profile/",
  repoUrl: null,
} as const;
