// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F05-volume-indicators/D07-F05-A14-volume-oscillator/implementations/typescript/volume_oscillator.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F05-A14: Volume Oscillator. */
import { volumeOscillator as nativeVolumeOscillator, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F05-A14";
export const TITLE = "Volume Oscillator";

export function volumeOscillator(input: TopicInput): TopicResult {
  return nativeVolumeOscillator(input);
}
