/**
 * Volume Oscillator
 *
 * Topic D07-F05-A14 · Technical Indicators / Volume Indicators · difficulty 2
 * Shape: series-transform · entry: volumeOscillator()
 * Article: https://thefintechbuilder.com/technical-indicators/volume-indicators/volume-oscillator/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F05-A14-volume-oscillator
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { volumeOscillator as run } from "./impl.ts";

export const meta = {
  id: "D07-F05-A14",
  title: "Volume Oscillator",
  slug: "volume-oscillator",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F05",
  family: "Volume Indicators",
  difficulty: 2,
  archetype: "series-transform",
  entry: "volumeOscillator",
  path: "technical-indicators/volume-indicators/volume-oscillator",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/volume-indicators/volume-oscillator/",
  repoUrl: null,
} as const;
