/**
 * Inverted Hammer
 *
 * Topic D06-F02-A08 · Price Action and Candlesticks / Single-Candle Patterns · difficulty 3
 * Shape: record-transform · entry: invertedHammer()
 * Article: https://thefintechbuilder.com/price-action-and-candlesticks/single-candle-patterns/inverted-hammer/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D06-F02-A08-inverted-hammer
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { invertedHammer as run } from "./impl.ts";

export const meta = {
  id: "D06-F02-A08",
  title: "Inverted Hammer",
  slug: "inverted-hammer",
  domainId: "D06",
  domain: "Price Action and Candlesticks",
  familyId: "D06-F02",
  family: "Single-Candle Patterns",
  difficulty: 3,
  archetype: "record-transform",
  entry: "invertedHammer",
  path: "price-action-and-candlesticks/single-candle-patterns/inverted-hammer",
  articleUrl: "https://thefintechbuilder.com/price-action-and-candlesticks/single-candle-patterns/inverted-hammer/",
  repoUrl: null,
} as const;
