// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F06-range-and-volatility-indicators/D07-F06-A05-volatility-ratio/implementations/typescript/volatility_ratio.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F06-A05: Volatility Ratio. */
import { volatilityRatio as nativeVolatilityRatio, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F06-A05";
export const TITLE = "Volatility Ratio";

export function volatilityRatio(input: TopicInput): TopicResult {
  return nativeVolatilityRatio(input);
}
