// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D13-execution-and-transaction-cost-analysis/D13-F02-cost-risk-optimization/D13-F02-A02-implementation-shortfall-execution/implementations/typescript/cost-risk-optimization.ts
// Re-run `npm run sync` after changing the catalog implementation.
//
// This family shares one implementation across its topics; the body lives at
// src/_shared/cost-risk-optimization.ts and is re-exported here so the public surface of
// this subpath is unchanged.

export * from "../../../_shared/cost-risk-optimization.ts";
