// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F01-trend-smoothing/D07-F01-A17-variable-index-dynamic-average-vidya/implementations/typescript/variable_index_dynamic_average_vidya.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F01-A17: Variable Index Dynamic Average (VIDYA). */
import { variableIndexDynamicAverageVidya as nativeVariableIndexDynamicAverageVidya, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F01-A17";
export const TITLE = "Variable Index Dynamic Average (VIDYA)";

export function variableIndexDynamicAverageVidya(input: TopicInput): TopicResult {
  return nativeVariableIndexDynamicAverageVidya(input);
}
