/**
 * Variable Index Dynamic Average (VIDYA)
 *
 * Topic D07-F01-A17 · Technical Indicators / Trend Smoothing · difficulty 2
 * Shape: series-transform · entry: variableIndexDynamicAverageVidya()
 * Article: https://thefintechbuilder.com/technical-indicators/trend-smoothing/variable-index-dynamic-average-vidya/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F01-A17-variable-index-dynamic-average-vidya
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { variableIndexDynamicAverageVidya as run } from "./impl.ts";

export const meta = {
  id: "D07-F01-A17",
  title: "Variable Index Dynamic Average (VIDYA)",
  slug: "variable-index-dynamic-average-vidya",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F01",
  family: "Trend Smoothing",
  difficulty: 2,
  archetype: "series-transform",
  entry: "variableIndexDynamicAverageVidya",
  path: "technical-indicators/trend-smoothing/variable-index-dynamic-average-vidya",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/trend-smoothing/variable-index-dynamic-average-vidya/",
  repoUrl: null,
} as const;
