// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D09-statistical-time-series/D09-F02-forecast-models/D09-F02-A06-theta-forecast/implementations/typescript/theta_forecast.ts
// Re-run `npm run sync` after changing the catalog implementation.


type ForecastResult = {
  forecast:number[];
  fitted:(number|null)[];
  residuals?:number[];
  state:Record<string,unknown>;
  [key:string]:unknown;
};
const finite=(value:number,name:string)=>{
  if(typeof value!=="number"||!Number.isFinite(value))throw new Error(`${name} must be finite`);
  return value;
};
const positiveInt=(value:number,name:string,min=1)=>{
  if(!Number.isInteger(value)||value<min)throw new Error(`${name} must be an integer >= ${min}`);
  return value;
};
const series=(values:number[],minimum=2)=>{
  if(!Array.isArray(values)||values.length<minimum)throw new Error(`values must contain at least ${minimum} observations`);
  return values.map((value,index)=>finite(value,`values[${index}]`));
};
const coefficients=(values:number[],name:string,allowEmpty=true)=>{
  if(!Array.isArray(values)||(!allowEmpty&&values.length===0))throw new Error(`${name} must be a coefficient list`);
  return values.map((value,index)=>finite(value,`${name}[${index}]`));
};

export function forecastTheta(values:number[],alpha:number,horizon:number):ForecastResult{
  const y=series(values,4),a=finite(alpha,"alpha"),H=positiveInt(horizon,"horizon");if(a<=0||a>1)throw new Error("alpha must be in (0, 1]");
  const n=y.length,meanT=(n-1)/2,meanY=y.reduce((s,v)=>s+v,0)/n,den=Array.from({length:n},(_,t)=>(t-meanT)**2).reduce((s,v)=>s+v,0);
  const slope=y.reduce((s,value,t)=>s+(t-meanT)*(value-meanY),0)/den;
  let level=y[0];const fitted:(number|null)[]=[null];
  for(const observation of y.slice(1)){fitted.push(level);level=a*observation+(1-a)*level;}
  const correction=1/a-(1-a)**n/a,forecast=Array.from({length:H},(_,index)=>level+.5*slope*(index+correction));
  return {forecast,fitted,state:{ses_level:level,ols_slope:slope,alpha:a,finite_sample_correction:correction}};
}
