/**
 * Order Flow Imbalance
 *
 * Topic D11-F03-A01 · Market Microstructure / Order-Flow and Impact · difficulty 3
 * Shape: record-transform · entry: orderFlowImbalance()
 * Article: https://thefintechbuilder.com/market-microstructure/order-flow-and-impact/order-flow-imbalance/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D11-F03-A01-order-flow-imbalance
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { orderFlowImbalance as run } from "./impl.ts";

export const meta = {
  id: "D11-F03-A01",
  title: "Order Flow Imbalance",
  slug: "order-flow-imbalance",
  domainId: "D11",
  domain: "Market Microstructure",
  familyId: "D11-F03",
  family: "Order-Flow and Impact",
  difficulty: 3,
  archetype: "record-transform",
  entry: "orderFlowImbalance",
  path: "market-microstructure/order-flow-and-impact/order-flow-imbalance",
  articleUrl: "https://thefintechbuilder.com/market-microstructure/order-flow-and-impact/order-flow-imbalance/",
  repoUrl: null,
} as const;
