/**
 * Gordon Growth Model
 *
 * Topic D18-F02-A03 · Fundamental Analysis and Valuation / Intrinsic Valuation · difficulty 3
 * Shape: record-transform · entry: gordonGrowthModel()
 * Article: https://thefintechbuilder.com/fundamental-analysis-and-valuation/intrinsic-valuation/gordon-growth-model/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D18-F02-A03-gordon-growth-model
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { gordonGrowthModel as run } from "./impl.ts";

export const meta = {
  id: "D18-F02-A03",
  title: "Gordon Growth Model",
  slug: "gordon-growth-model",
  domainId: "D18",
  domain: "Fundamental Analysis and Valuation",
  familyId: "D18-F02",
  family: "Intrinsic Valuation",
  difficulty: 3,
  archetype: "record-transform",
  entry: "gordonGrowthModel",
  path: "fundamental-analysis-and-valuation/intrinsic-valuation/gordon-growth-model",
  articleUrl: "https://thefintechbuilder.com/fundamental-analysis-and-valuation/intrinsic-valuation/gordon-growth-model/",
  repoUrl: null,
} as const;
