// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F03-momentum/D07-F03-A27-balance-of-power/implementations/typescript/balance_of_power.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F03-A27: Balance of Power. */
import { balanceOfPower as nativeBalanceOfPower, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F03-A27";
export const TITLE = "Balance of Power";

export function balanceOfPower(input: TopicInput): TopicResult {
  return nativeBalanceOfPower(input);
}
