/**
 * Microprice
 *
 * Topic D11-F04-A03 · Market Microstructure / Order-Book Dynamics · difficulty 4
 * Shape: record-transform · entry: microprice()
 * Article: https://thefintechbuilder.com/market-microstructure/order-book-dynamics/microprice/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D11-F04-A03-microprice
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { microprice as run } from "./impl.ts";

export const meta = {
  id: "D11-F04-A03",
  title: "Microprice",
  slug: "microprice",
  domainId: "D11",
  domain: "Market Microstructure",
  familyId: "D11-F04",
  family: "Order-Book Dynamics",
  difficulty: 4,
  archetype: "record-transform",
  entry: "microprice",
  path: "market-microstructure/order-book-dynamics/microprice",
  articleUrl: "https://thefintechbuilder.com/market-microstructure/order-book-dynamics/microprice/",
  repoUrl: null,
} as const;
