/**
 * CRSP Cumulative Price Adjustment: Respect the Vendor Basis, Sign, and Gaps
 *
 * Topic D02-F01-A04 · Corporate Actions and Security Master Data / Adjustment Factors · difficulty 3
 * Shape: record-transform · entry: calculate()
 * Article: https://thefintechbuilder.com/corporate-actions-and-security-master-data/adjustment-factors/crsp-cumulative-price-adjustment/
 * Repo:    https://github.com/IslamBaraka90/Fintech-CRSP-Cumulative-Price-Adjustment-Corporate-Actions-algorithm
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D02-F01-A04-crsp-cumulative-price-adjustment
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { calculate as run } from "./impl.ts";

export const meta = {
  id: "D02-F01-A04",
  title: "CRSP Cumulative Price Adjustment: Respect the Vendor Basis, Sign, and Gaps",
  slug: "crsp-cumulative-price-adjustment",
  domainId: "D02",
  domain: "Corporate Actions and Security Master Data",
  familyId: "D02-F01",
  family: "Adjustment Factors",
  difficulty: 3,
  archetype: "record-transform",
  entry: "calculate",
  path: "corporate-actions-and-security-master-data/adjustment-factors/crsp-cumulative-price-adjustment",
  articleUrl: "https://thefintechbuilder.com/corporate-actions-and-security-master-data/adjustment-factors/crsp-cumulative-price-adjustment/",
  repoUrl: "https://github.com/IslamBaraka90/Fintech-CRSP-Cumulative-Price-Adjustment-Corporate-Actions-algorithm",
} as const;
