/**
 * Piotroski F-Score
 *
 * Topic D18-F04-A02 · Fundamental Analysis and Valuation / Quality and Distress · difficulty 2
 * Shape: record-transform · entry: piotroskiFScore()
 * Article: https://thefintechbuilder.com/fundamental-analysis-and-valuation/quality-and-distress/piotroski-f-score/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D18-F04-A02-piotroski-f-score
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { piotroskiFScore as run } from "./impl.ts";

export const meta = {
  id: "D18-F04-A02",
  title: "Piotroski F-Score",
  slug: "piotroski-f-score",
  domainId: "D18",
  domain: "Fundamental Analysis and Valuation",
  familyId: "D18-F04",
  family: "Quality and Distress",
  difficulty: 2,
  archetype: "record-transform",
  entry: "piotroskiFScore",
  path: "fundamental-analysis-and-valuation/quality-and-distress/piotroski-f-score",
  articleUrl: "https://thefintechbuilder.com/fundamental-analysis-and-valuation/quality-and-distress/piotroski-f-score/",
  repoUrl: null,
} as const;
