/**
 * Relative Strength Index (RSI)
 *
 * Topic D07-F03-A01 · Technical Indicators / Momentum · difficulty 2
 * Shape: series-transform · entry: rsi()
 * Article: https://thefintechbuilder.com/technical-indicators/momentum/rsi/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F03-A01-rsi
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { rsi as run } from "./impl.ts";

export const meta = {
  id: "D07-F03-A01",
  title: "Relative Strength Index (RSI)",
  slug: "rsi",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F03",
  family: "Momentum",
  difficulty: 2,
  archetype: "series-transform",
  entry: "rsi",
  path: "technical-indicators/momentum/rsi",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/momentum/rsi/",
  repoUrl: null,
} as const;
