/**
 * Arithmetic versus Geometric Average Return
 *
 * Topic D00-F02-A09 · Financial Mathematics, Statistics, and Data Foundations / Financial Arithmetic, Time Value, and Returns · difficulty 1
 * Shape: record-transform · entry: arithmeticVersusGeometricAverageReturn()
 * Article: https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/financial-arithmetic-time-value-and-returns/arithmetic-geometric-return/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F02-A09-arithmetic-geometric-return
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { arithmeticVersusGeometricAverageReturn as run } from "./impl.ts";

export const meta = {
  id: "D00-F02-A09",
  title: "Arithmetic versus Geometric Average Return",
  slug: "arithmetic-geometric-return",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F02",
  family: "Financial Arithmetic, Time Value, and Returns",
  difficulty: 1,
  archetype: "record-transform",
  entry: "arithmeticVersusGeometricAverageReturn",
  path: "financial-mathematics-statistics-and-data-foundations/financial-arithmetic-time-value-and-returns/arithmetic-geometric-return",
  articleUrl: "https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/financial-arithmetic-time-value-and-returns/arithmetic-geometric-return/",
  repoUrl: null,
} as const;
