/**
 * Shadow-to-Body Ratio
 *
 * Topic D06-F01-A03 · Price Action and Candlesticks / Candle Foundations · difficulty 2
 * Shape: record-transform · entry: shadowToBodyRatio()
 * Article: https://thefintechbuilder.com/price-action-and-candlesticks/candle-foundations/shadow-to-body-ratio/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D06-F01-A03-shadow-to-body-ratio
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { shadowToBodyRatio as run } from "./impl.ts";

export const meta = {
  id: "D06-F01-A03",
  title: "Shadow-to-Body Ratio",
  slug: "shadow-to-body-ratio",
  domainId: "D06",
  domain: "Price Action and Candlesticks",
  familyId: "D06-F01",
  family: "Candle Foundations",
  difficulty: 2,
  archetype: "record-transform",
  entry: "shadowToBodyRatio",
  path: "price-action-and-candlesticks/candle-foundations/shadow-to-body-ratio",
  articleUrl: "https://thefintechbuilder.com/price-action-and-candlesticks/candle-foundations/shadow-to-body-ratio/",
  repoUrl: null,
} as const;
