/**
 * Lognormal Distribution and Positive Quantities
 *
 * Topic D00-F07-A06 · Financial Mathematics, Statistics, and Data Foundations / Probability Distributions and Simulation Basics · difficulty 1
 * Shape: record-transform · entry: lognormalDistributionAndPositiveQuantities()
 * Article: https://thefintechbuilder.com/foundations/probability-distributions-and-simulation-basics/lognormal-distribution-and-positive-quantities/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F07-A06-lognormal-distri
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { lognormalDistributionAndPositiveQuantities as run } from "./impl.ts";

export const meta = {
  id: "D00-F07-A06",
  title: "Lognormal Distribution and Positive Quantities",
  slug: "lognormal-distribution-and-positive-quantities",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F07",
  family: "Probability Distributions and Simulation Basics",
  difficulty: 1,
  archetype: "record-transform",
  entry: "lognormalDistributionAndPositiveQuantities",
  path: "foundations/probability-distributions-and-simulation-basics/lognormal-distribution-and-positive-quantities",
  articleUrl: "https://thefintechbuilder.com/foundations/probability-distributions-and-simulation-basics/lognormal-distribution-and-positive-quantities/",
  repoUrl: null,
} as const;
