// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F06-range-and-volatility-indicators/D07-F06-A11-normalized-price-range/implementations/typescript/normalized_price_range.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F06-A11: Normalized Price Range. */
import { normalizedPriceRange as nativeNormalizedPriceRange, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F06-A11";
export const TITLE = "Normalized Price Range";

export function normalizedPriceRange(input: TopicInput): TopicResult {
  return nativeNormalizedPriceRange(input);
}
