/**
 * Economic Value Added
 *
 * Topic D18-F02-A05 · Fundamental Analysis and Valuation / Intrinsic Valuation · difficulty 4
 * Shape: record-transform · entry: economicValueAdded()
 * Article: https://thefintechbuilder.com/fundamental-analysis-and-valuation/intrinsic-valuation/economic-value-added/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D18-F02-A05-economic-value-added
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { economicValueAdded as run } from "./impl.ts";

export const meta = {
  id: "D18-F02-A05",
  title: "Economic Value Added",
  slug: "economic-value-added",
  domainId: "D18",
  domain: "Fundamental Analysis and Valuation",
  familyId: "D18-F02",
  family: "Intrinsic Valuation",
  difficulty: 4,
  archetype: "record-transform",
  entry: "economicValueAdded",
  path: "fundamental-analysis-and-valuation/intrinsic-valuation/economic-value-added",
  articleUrl: "https://thefintechbuilder.com/fundamental-analysis-and-valuation/intrinsic-valuation/economic-value-added/",
  repoUrl: null,
} as const;
