/**
 * Compound Interest
 *
 * Topic D00-F02-A02 · Financial Mathematics, Statistics, and Data Foundations / Financial Arithmetic, Time Value, and Returns · difficulty 1
 * Shape: record-transform · entry: compoundInterest()
 * Article: https://thefintechbuilder.com/foundations/financial-arithmetic-time-value-and-returns/compound-interest/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F02-A02-compound-interest
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { compoundInterest as run } from "./impl.ts";

export const meta = {
  id: "D00-F02-A02",
  title: "Compound Interest",
  slug: "compound-interest",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F02",
  family: "Financial Arithmetic, Time Value, and Returns",
  difficulty: 1,
  archetype: "record-transform",
  entry: "compoundInterest",
  path: "foundations/financial-arithmetic-time-value-and-returns/compound-interest",
  articleUrl: "https://thefintechbuilder.com/foundations/financial-arithmetic-time-value-and-returns/compound-interest/",
  repoUrl: null,
} as const;
