/**
 * Rising/Falling Window
 *
 * Topic D06-F03-A12 · Price Action and Candlesticks / Two-Candle Patterns · difficulty 2
 * Shape: record-transform · entry: risingFallingWindow()
 * Article: https://thefintechbuilder.com/price-action-and-candlesticks/two-candle-patterns/rising-falling-window/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D06-F03-A12-rising-falling-window
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { risingFallingWindow as run } from "./impl.ts";

export const meta = {
  id: "D06-F03-A12",
  title: "Rising/Falling Window",
  slug: "rising-falling-window",
  domainId: "D06",
  domain: "Price Action and Candlesticks",
  familyId: "D06-F03",
  family: "Two-Candle Patterns",
  difficulty: 2,
  archetype: "record-transform",
  entry: "risingFallingWindow",
  path: "price-action-and-candlesticks/two-candle-patterns/rising-falling-window",
  articleUrl: "https://thefintechbuilder.com/price-action-and-candlesticks/two-candle-patterns/rising-falling-window/",
  repoUrl: null,
} as const;
