/**
 * Projection Bands
 *
 * Topic D07-F07-A09 · Technical Indicators / Bands, Envelopes, and Squeezes · difficulty 2
 * Shape: series-transform · entry: projectionBands()
 * Article: https://thefintechbuilder.com/technical-indicators/bands-envelopes-and-squeezes/projection-bands/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F07-A09-projection-bands
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { projectionBands as run } from "./impl.ts";

export const meta = {
  id: "D07-F07-A09",
  title: "Projection Bands",
  slug: "projection-bands",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F07",
  family: "Bands, Envelopes, and Squeezes",
  difficulty: 2,
  archetype: "series-transform",
  entry: "projectionBands",
  path: "technical-indicators/bands-envelopes-and-squeezes/projection-bands",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/bands-envelopes-and-squeezes/projection-bands/",
  repoUrl: null,
} as const;
