/**
 * Breakout Strength
 *
 * Topic D08-F07-A03 · Geometric Chart Patterns / Market Structure, Breakouts, and Regimes · difficulty 2
 * Shape: record-transform · entry: breakoutStrength()
 * Article: https://thefintechbuilder.com/geometric-chart-patterns/market-structure-breakouts-and-regimes/breakout-strength/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D08-F07-A03-breakout-strength
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { breakoutStrength as run } from "./impl.ts";

export const meta = {
  id: "D08-F07-A03",
  title: "Breakout Strength",
  slug: "breakout-strength",
  domainId: "D08",
  domain: "Geometric Chart Patterns",
  familyId: "D08-F07",
  family: "Market Structure, Breakouts, and Regimes",
  difficulty: 2,
  archetype: "record-transform",
  entry: "breakoutStrength",
  path: "geometric-chart-patterns/market-structure-breakouts-and-regimes/breakout-strength",
  articleUrl: "https://thefintechbuilder.com/geometric-chart-patterns/market-structure-breakouts-and-regimes/breakout-strength/",
  repoUrl: null,
} as const;
