// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D18-fundamental-analysis-and-valuation/D18-F01-statement-ratios/D18-F01-A06-common-size-statements/implementations/typescript/statement-ratios.ts
// Re-run `npm run sync` after changing the catalog implementation.
//
// This family shares one implementation across its topics; the body lives at
// src/_shared/statement-ratios.ts and is re-exported here so the public surface of
// this subpath is unchanged.

export * from "../../../_shared/statement-ratios.ts";
