// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F06-range-and-volatility-indicators/D07-F06-A02-chaikin-volatility/implementations/typescript/chaikin_volatility.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F06-A02: Chaikin Volatility. */
import { chaikinVolatility as nativeChaikinVolatility, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F06-A02";
export const TITLE = "Chaikin Volatility";

export function chaikinVolatility(input: TopicInput): TopicResult {
  return nativeChaikinVolatility(input);
}
