/**
 * Merger Predecessor/Successor Mapping: Preserve Identity and Entitlements Without Inventing Continuity
 *
 * Topic D02-F03-A04 · Corporate Actions and Security Master Data / Identity Continuity · difficulty 4
 * Shape: row-classify · entry: resolveMerger()
 * Article: https://thefintechbuilder.com/corporate-actions-and-security-master-data/identity-continuity/merger-predecessor-successor-mapping/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D02-F03-A04-merger-predecessor-successor-mapping
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { resolveMerger as run } from "./impl.ts";

export const meta = {
  id: "D02-F03-A04",
  title: "Merger Predecessor/Successor Mapping: Preserve Identity and Entitlements Without Inventing Continuity",
  slug: "merger-predecessor-successor-mapping",
  domainId: "D02",
  domain: "Corporate Actions and Security Master Data",
  familyId: "D02-F03",
  family: "Identity Continuity",
  difficulty: 4,
  archetype: "row-classify",
  entry: "resolveMerger",
  path: "corporate-actions-and-security-master-data/identity-continuity/merger-predecessor-successor-mapping",
  articleUrl: "https://thefintechbuilder.com/corporate-actions-and-security-master-data/identity-continuity/merger-predecessor-successor-mapping/",
  repoUrl: null,
} as const;
