// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F03-momentum/D07-F03-A23-wavetrend-oscillator/implementations/typescript/wavetrend_oscillator.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F03-A23: WaveTrend Oscillator. */
import { wavetrendOscillator as nativeWavetrendOscillator, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F03-A23";
export const TITLE = "WaveTrend Oscillator";

export function wavetrendOscillator(input: TopicInput): TopicResult {
  return nativeWavetrendOscillator(input);
}
