/**
 * TWAP Execution
 *
 * Topic D13-F01-A01 · Execution and Transaction Cost Analysis / Schedule-Based Execution · difficulty 2
 * Shape: record-transform · entry: twapExecution()
 * Article: https://thefintechbuilder.com/execution-and-transaction-cost-analysis/schedule-based-execution/twap-execution/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D13-F01-A01-twap-execution
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { twapExecution as run } from "./impl.ts";

export const meta = {
  id: "D13-F01-A01",
  title: "TWAP Execution",
  slug: "twap-execution",
  domainId: "D13",
  domain: "Execution and Transaction Cost Analysis",
  familyId: "D13-F01",
  family: "Schedule-Based Execution",
  difficulty: 2,
  archetype: "record-transform",
  entry: "twapExecution",
  path: "execution-and-transaction-cost-analysis/schedule-based-execution/twap-execution",
  articleUrl: "https://thefintechbuilder.com/execution-and-transaction-cost-analysis/schedule-based-execution/twap-execution/",
  repoUrl: null,
} as const;
