/**
 * Partial-Fill and Residual-Quantity Processing
 *
 * Topic D12-F04-A03 · Matching Engines and Venue Logic / Order Lifecycle and Queue State · difficulty 3
 * Shape: record-transform · entry: partialFillResidual()
 * Article: https://thefintechbuilder.com/matching-engines-and-venue-logic/order-lifecycle-and-queue-state/partial-fill-and-residual-quantity-processing/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D12-F04-A03-partial-fill-and-residual-quantity-processing
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { partialFillResidual as run } from "./impl.ts";

export const meta = {
  id: "D12-F04-A03",
  title: "Partial-Fill and Residual-Quantity Processing",
  slug: "partial-fill-and-residual-quantity-processing",
  domainId: "D12",
  domain: "Matching Engines and Venue Logic",
  familyId: "D12-F04",
  family: "Order Lifecycle and Queue State",
  difficulty: 3,
  archetype: "record-transform",
  entry: "partialFillResidual",
  path: "matching-engines-and-venue-logic/order-lifecycle-and-queue-state/partial-fill-and-residual-quantity-processing",
  articleUrl: "https://thefintechbuilder.com/matching-engines-and-venue-logic/order-lifecycle-and-queue-state/partial-fill-and-residual-quantity-processing/",
  repoUrl: null,
} as const;
