/**
 * Log Price Transform
 *
 * Topic D07-F08-A06 · Technical Indicators / Price Transforms · difficulty 2
 * Shape: series-transform · entry: logPriceTransform()
 * Article: https://thefintechbuilder.com/technical-indicators/price-transforms/log-price-transform/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F08-A06-log-price-transform
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { logPriceTransform as run } from "./impl.ts";

export const meta = {
  id: "D07-F08-A06",
  title: "Log Price Transform",
  slug: "log-price-transform",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F08",
  family: "Price Transforms",
  difficulty: 2,
  archetype: "series-transform",
  entry: "logPriceTransform",
  path: "technical-indicators/price-transforms/log-price-transform",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/price-transforms/log-price-transform/",
  repoUrl: null,
} as const;
