/**
 * Divergence Strength and Quality Scoring
 *
 * Topic D08-F05-A05 · Geometric Chart Patterns / Indicator Divergence Detection · difficulty 4
 * Shape: record-transform · entry: divergenceStrengthAndQualityScoring()
 * Article: https://thefintechbuilder.com/geometric-chart-patterns/indicator-divergence-detection/divergence-strength-and-quality-scoring/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D08-F05-A05-divergence-strength-and-quality-scoring
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { divergenceStrengthAndQualityScoring as run } from "./impl.ts";

export const meta = {
  id: "D08-F05-A05",
  title: "Divergence Strength and Quality Scoring",
  slug: "divergence-strength-and-quality-scoring",
  domainId: "D08",
  domain: "Geometric Chart Patterns",
  familyId: "D08-F05",
  family: "Indicator Divergence Detection",
  difficulty: 4,
  archetype: "record-transform",
  entry: "divergenceStrengthAndQualityScoring",
  path: "geometric-chart-patterns/indicator-divergence-detection/divergence-strength-and-quality-scoring",
  articleUrl: "https://thefintechbuilder.com/geometric-chart-patterns/indicator-divergence-detection/divergence-strength-and-quality-scoring/",
  repoUrl: null,
} as const;
