/**
 * Efficiency Ratio
 *
 * Topic D08-F07-A10 · Geometric Chart Patterns / Market Structure, Breakouts, and Regimes · difficulty 2
 * Shape: record-transform · entry: efficiencyRatio()
 * Article: https://thefintechbuilder.com/geometric-chart-patterns/market-structure-breakouts-and-regimes/efficiency-ratio/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D08-F07-A10-efficiency-ratio
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { efficiencyRatio as run } from "./impl.ts";

export const meta = {
  id: "D08-F07-A10",
  title: "Efficiency Ratio",
  slug: "efficiency-ratio",
  domainId: "D08",
  domain: "Geometric Chart Patterns",
  familyId: "D08-F07",
  family: "Market Structure, Breakouts, and Regimes",
  difficulty: 2,
  archetype: "record-transform",
  entry: "efficiencyRatio",
  path: "geometric-chart-patterns/market-structure-breakouts-and-regimes/efficiency-ratio",
  articleUrl: "https://thefintechbuilder.com/geometric-chart-patterns/market-structure-breakouts-and-regimes/efficiency-ratio/",
  repoUrl: null,
} as const;
