/**
 * Active Return and Tracking Error
 *
 * Topic D00-F11-A09 · Financial Mathematics, Statistics, and Data Foundations / Financial Risk and Performance Statistics · difficulty 1
 * Shape: record-transform · entry: activeReturnAndTrackingError()
 * Article: https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/financial-risk-and-performance-statistics/active-return-and-tracking-error/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F11-A09-active-return-an
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { activeReturnAndTrackingError as run } from "./impl.ts";

export const meta = {
  id: "D00-F11-A09",
  title: "Active Return and Tracking Error",
  slug: "active-return-and-tracking-error",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F11",
  family: "Financial Risk and Performance Statistics",
  difficulty: 1,
  archetype: "record-transform",
  entry: "activeReturnAndTrackingError",
  path: "financial-mathematics-statistics-and-data-foundations/financial-risk-and-performance-statistics/active-return-and-tracking-error",
  articleUrl: "https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/financial-risk-and-performance-statistics/active-return-and-tracking-error/",
  repoUrl: null,
} as const;
