// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F01-trend-smoothing/D07-F01-A12-following-adaptive-moving-average-fama/implementations/typescript/following_adaptive_moving_average_fama.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F01-A12: Following Adaptive Moving Average (FAMA). */
import { followingAdaptiveMovingAverageFama as nativeFollowingAdaptiveMovingAverageFama, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F01-A12";
export const TITLE = "Following Adaptive Moving Average (FAMA)";

export function followingAdaptiveMovingAverageFama(input: TopicInput): TopicResult {
  return nativeFollowingAdaptiveMovingAverageFama(input);
}
