/**
 * Following Adaptive Moving Average (FAMA)
 *
 * Topic D07-F01-A12 · Technical Indicators / Trend Smoothing · difficulty 2
 * Shape: series-transform · entry: followingAdaptiveMovingAverageFama()
 * Article: https://thefintechbuilder.com/technical-indicators/trend-smoothing/following-adaptive-moving-average-fama/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F01-A12-following-adaptive-moving-average-fama
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { followingAdaptiveMovingAverageFama as run } from "./impl.ts";

export const meta = {
  id: "D07-F01-A12",
  title: "Following Adaptive Moving Average (FAMA)",
  slug: "following-adaptive-moving-average-fama",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F01",
  family: "Trend Smoothing",
  difficulty: 2,
  archetype: "series-transform",
  entry: "followingAdaptiveMovingAverageFama",
  path: "technical-indicators/trend-smoothing/following-adaptive-moving-average-fama",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/trend-smoothing/following-adaptive-moving-average-fama/",
  repoUrl: null,
} as const;
