// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F02-trend-systems/D07-F02-A14-mass-index/implementations/typescript/mass_index.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F02-A14: Mass Index. */
import { massIndex as nativeMassIndex, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F02-A14";
export const TITLE = "Mass Index";

export function massIndex(input: TopicInput): TopicResult {
  return nativeMassIndex(input);
}
