/**
 * Rolling Beta
 *
 * Topic D07-F09-A03 · Technical Indicators / Rolling Statistical Indicators · difficulty 2
 * Shape: series-transform · entry: rollingBeta()
 * Article: https://thefintechbuilder.com/technical-indicators/rolling-statistical-indicators/rolling-beta/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F09-A03-rolling-beta
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { rollingBeta as run } from "./impl.ts";

export const meta = {
  id: "D07-F09-A03",
  title: "Rolling Beta",
  slug: "rolling-beta",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F09",
  family: "Rolling Statistical Indicators",
  difficulty: 2,
  archetype: "series-transform",
  entry: "rollingBeta",
  path: "technical-indicators/rolling-statistical-indicators/rolling-beta",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/rolling-statistical-indicators/rolling-beta/",
  repoUrl: null,
} as const;
