/**
 * Free-Cash-Flow DCF
 *
 * Topic D18-F02-A01 · Fundamental Analysis and Valuation / Intrinsic Valuation · difficulty 4
 * Shape: record-transform · entry: freeCashFlowDcf()
 * Article: https://thefintechbuilder.com/fundamental-analysis-and-valuation/intrinsic-valuation/free-cash-flow-dcf/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D18-F02-A01-free-cash-flow-dcf
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { freeCashFlowDcf as run } from "./impl.ts";

export const meta = {
  id: "D18-F02-A01",
  title: "Free-Cash-Flow DCF",
  slug: "free-cash-flow-dcf",
  domainId: "D18",
  domain: "Fundamental Analysis and Valuation",
  familyId: "D18-F02",
  family: "Intrinsic Valuation",
  difficulty: 4,
  archetype: "record-transform",
  entry: "freeCashFlowDcf",
  path: "fundamental-analysis-and-valuation/intrinsic-valuation/free-cash-flow-dcf",
  articleUrl: "https://thefintechbuilder.com/fundamental-analysis-and-valuation/intrinsic-valuation/free-cash-flow-dcf/",
  repoUrl: null,
} as const;
