/**
 * Ichimoku Cloud: Separate Range Midpoints from Plot-Time Displacement
 *
 * Topic D07-F02-A06 · Technical Indicators / Trend Systems · difficulty 3
 * Shape: series-transform · entry: ichimoku()
 * Article: https://thefintechbuilder.com/technical-indicators/trend-systems/ichimoku-cloud/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F02-A06-ichimoku-cloud
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { ichimoku as run } from "./impl.ts";

export const meta = {
  id: "D07-F02-A06",
  title: "Ichimoku Cloud: Separate Range Midpoints from Plot-Time Displacement",
  slug: "ichimoku-cloud",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F02",
  family: "Trend Systems",
  difficulty: 3,
  archetype: "series-transform",
  entry: "ichimoku",
  path: "technical-indicators/trend-systems/ichimoku-cloud",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/trend-systems/ichimoku-cloud/",
  repoUrl: null,
} as const;
