/**
 * STL Decomposition
 *
 * Topic D09-F05-A01 · Statistical Time Series / Decomposition and Cycles · difficulty 3
 * Shape: record-transform · entry: stlDecompose()
 * Article: https://thefintechbuilder.com/statistical-time-series/decomposition-and-cycles/stl-decomposition/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D09-F05-A01-stl-decomposition
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { stlDecompose as run } from "./impl.ts";

export const meta = {
  id: "D09-F05-A01",
  title: "STL Decomposition",
  slug: "stl-decomposition",
  domainId: "D09",
  domain: "Statistical Time Series",
  familyId: "D09-F05",
  family: "Decomposition and Cycles",
  difficulty: 3,
  archetype: "record-transform",
  entry: "stlDecompose",
  path: "statistical-time-series/decomposition-and-cycles/stl-decomposition",
  articleUrl: "https://thefintechbuilder.com/statistical-time-series/decomposition-and-cycles/stl-decomposition/",
  repoUrl: null,
} as const;
