/**
 * Zmijewski X-Score
 *
 * Topic D18-F04-A06 · Fundamental Analysis and Valuation / Quality and Distress · difficulty 2
 * Shape: record-transform · entry: zmijewskiXScore()
 * Article: https://thefintechbuilder.com/fundamental-analysis-and-valuation/quality-and-distress/zmijewski-x-score/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D18-F04-A06-zmijewski-x-score
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { zmijewskiXScore as run } from "./impl.ts";

export const meta = {
  id: "D18-F04-A06",
  title: "Zmijewski X-Score",
  slug: "zmijewski-x-score",
  domainId: "D18",
  domain: "Fundamental Analysis and Valuation",
  familyId: "D18-F04",
  family: "Quality and Distress",
  difficulty: 2,
  archetype: "record-transform",
  entry: "zmijewskiXScore",
  path: "fundamental-analysis-and-valuation/quality-and-distress/zmijewski-x-score",
  articleUrl: "https://thefintechbuilder.com/fundamental-analysis-and-valuation/quality-and-distress/zmijewski-x-score/",
  repoUrl: null,
} as const;
