/**
 * Yang-Zhang Volatility
 *
 * Topic D10-F01-A05 · Volatility and Covariance / Historical Estimators · difficulty 3
 * Shape: record-transform · entry: calculate()
 * Article: https://thefintechbuilder.com/volatility-and-covariance/historical-estimators/yang-zhang-volatility/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D10-F01-A05-yang-zhang-volatility
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { calculate as run } from "./impl.ts";

export const meta = {
  id: "D10-F01-A05",
  title: "Yang-Zhang Volatility",
  slug: "yang-zhang-volatility",
  domainId: "D10",
  domain: "Volatility and Covariance",
  familyId: "D10-F01",
  family: "Historical Estimators",
  difficulty: 3,
  archetype: "record-transform",
  entry: "calculate",
  path: "volatility-and-covariance/historical-estimators/yang-zhang-volatility",
  articleUrl: "https://thefintechbuilder.com/volatility-and-covariance/historical-estimators/yang-zhang-volatility/",
  repoUrl: null,
} as const;
