/**
 * Trimmed and Winsorized Means
 *
 * Topic D00-F04-A05 · Financial Mathematics, Statistics, and Data Foundations / Location, Ranking, and Exploratory Summaries · difficulty 1
 * Shape: record-transform · entry: trimmedAndWinsorizedMeans()
 * Article: https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/location-ranking-and-exploratory-summaries/trimmed-and-winsorized-means/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F04-A05-trimmed-and-wins
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { trimmedAndWinsorizedMeans as run } from "./impl.ts";

export const meta = {
  id: "D00-F04-A05",
  title: "Trimmed and Winsorized Means",
  slug: "trimmed-and-winsorized-means",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F04",
  family: "Location, Ranking, and Exploratory Summaries",
  difficulty: 1,
  archetype: "record-transform",
  entry: "trimmedAndWinsorizedMeans",
  path: "financial-mathematics-statistics-and-data-foundations/location-ranking-and-exploratory-summaries/trimmed-and-winsorized-means",
  articleUrl: "https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/location-ranking-and-exploratory-summaries/trimmed-and-winsorized-means/",
  repoUrl: null,
} as const;
