// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D02-corporate-actions-and-security-master-data/D02-F04-point-in-time-universe/D02-F04-A04-filing-revision-versioning/implementations/typescript/filing_revision_versioning.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Point-in-time filing-version selection for D02-F04-A04. */

const textValue = (value, name) => {
  if (typeof value !== "string" || !value.trim()) throw new TypeError(`${name} must be a non-empty string`);
  return value;
};

const instant = (value, name) => {
  const text = textValue(value, name);
  if (!/(?:Z|[+-]\d{2}:\d{2})$/.test(text)) throw new RangeError(`${name} must include a UTC offset`);
  const milliseconds = Date.parse(text);
  if (!Number.isFinite(milliseconds)) throw new RangeError(`${name} must be a valid ISO 8601 instant`);
  return milliseconds;
};

const nonnegativeInteger = (value, name) => {
  if (!Number.isInteger(value) || value < 0) throw new TypeError(`${name} must be a non-negative integer`);
  return value;
};

const factsValue = (value, name) => {
  if (!value || typeof value !== "object" || Array.isArray(value) || !Object.keys(value).length) {
    throw new TypeError(`${name} must be a non-empty object`);
  }
  for (const [key, number] of Object.entries(value)) {
    textValue(key, `${name} key`);
    if (typeof number !== "number" || !Number.isFinite(number)) throw new TypeError(`${name}.${key} must be finite`);
  }
  return structuredClone(value);
};

const validateRecord = (record, index, entityId, reportPeriod, formFamily) => {
  if (!record || typeof record !== "object" || Array.isArray(record)) throw new TypeError(`records[${index}] must be an object`);
  const prefix = `records[${index}]`;
  const recordEntity = textValue(record.entityId, `${prefix}.entityId`);
  const recordPeriod = textValue(record.reportPeriod, `${prefix}.reportPeriod`);
  const form = textValue(record.form, `${prefix}.form`);
  const accessionNo = textValue(record.accessionNo, `${prefix}.accessionNo`);
  const amendmentNumber = nonnegativeInteger(record.amendmentNumber, `${prefix}.amendmentNumber`);
  const acceptedInstant = instant(record.acceptedAt, `${prefix}.acceptedAt`);
  const ingestedInstant = instant(record.ingestedAt, `${prefix}.ingestedAt`);
  const facts = factsValue(record.facts, `${prefix}.facts`);
  if (recordEntity !== entityId || recordPeriod !== reportPeriod) throw new RangeError(`${prefix} does not match the requested entity and report period`);
  if (![formFamily, `${formFamily}/A`].includes(form)) throw new RangeError(`${prefix}.form is outside the requested form family`);
  if (amendmentNumber === 0 && form !== formFamily) throw new RangeError(`${prefix} marks an amendment as an original filing`);
  if (amendmentNumber > 0 && form !== `${formFamily}/A`) throw new RangeError(`${prefix} amendmentNumber requires an amended form`);
  if (ingestedInstant < acceptedInstant) throw new RangeError(`${prefix}.ingestedAt cannot precede acceptedAt for direct SEC ingestion`);
  if (!Array.isArray(record.amendmentScope) || !record.amendmentScope.length || record.amendmentScope.some(item => typeof item !== "string" || !item)) {
    throw new TypeError(`${prefix}.amendmentScope must be a non-empty list of strings`);
  }
  return { ...record, accessionNo, amendmentNumber, acceptedInstant, ingestedInstant, facts };
};

export function calculate(data) {
  if (!data || typeof data !== "object" || Array.isArray(data)) throw new TypeError("data must be an object");
  const entityId = textValue(data.entityId, "entityId");
  const reportPeriod = textValue(data.reportPeriod, "reportPeriod");
  const formFamily = textValue(data.formFamily, "formFamily");
  const asOf = textValue(data.asOf, "asOf");
  const asOfInstant = instant(asOf, "asOf");
  if (!Array.isArray(data.records) || !data.records.length) throw new TypeError("records must be a non-empty list");
  const checked = data.records.map((record, index) => validateRecord(record, index, entityId, reportPeriod, formFamily));
  const accessions = checked.map(record => record.accessionNo);
  if (new Set(accessions).size !== accessions.length) throw new RangeError("accessionNo values must be unique");
  const eligible = checked.filter(record => record.ingestedInstant <= asOfInstant);
  if (!eligible.length) throw new RangeError("no filing version was locally available by asOf");
  const selected = eligible.toSorted((left, right) =>
    left.acceptedInstant - right.acceptedInstant ||
    left.amendmentNumber - right.amendmentNumber ||
    left.accessionNo.localeCompare(right.accessionNo)
  ).at(-1);
  return {
    entityId,
    reportPeriod,
    asOf,
    selectionBasis: "latest accepted filing among locally ingested versions",
    accessionNo: selected.accessionNo,
    form: selected.form,
    amendmentNumber: selected.amendmentNumber,
    acceptedAt: selected.acceptedAt,
    ingestedAt: selected.ingestedAt,
    amendmentScope: [...selected.amendmentScope],
    facts: structuredClone(selected.facts),
    eligibleAccessions: eligible.map(record => record.accessionNo).sort(),
    excludedNotYetIngested: checked.filter(record => record.ingestedInstant > asOfInstant).map(record => record.accessionNo).sort(),
  };
}
