/**
 * Bernoulli and Binomial Distributions
 *
 * Topic D00-F07-A02 · Financial Mathematics, Statistics, and Data Foundations / Probability Distributions and Simulation Basics · difficulty 1
 * Shape: record-transform · entry: bernoulliAndBinomialDistributions()
 * Article: https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/probability-distributions-and-simulation-basics/bernoulli-and-binomial-distributions/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F07-A02-bernoulli-and-bi
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { bernoulliAndBinomialDistributions as run } from "./impl.ts";

export const meta = {
  id: "D00-F07-A02",
  title: "Bernoulli and Binomial Distributions",
  slug: "bernoulli-and-binomial-distributions",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F07",
  family: "Probability Distributions and Simulation Basics",
  difficulty: 1,
  archetype: "record-transform",
  entry: "bernoulliAndBinomialDistributions",
  path: "financial-mathematics-statistics-and-data-foundations/probability-distributions-and-simulation-basics/bernoulli-and-binomial-distributions",
  articleUrl: "https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/probability-distributions-and-simulation-basics/bernoulli-and-binomial-distributions/",
  repoUrl: null,
} as const;
