// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D02-corporate-actions-and-security-master-data/D02-F01-adjustment-factors/D02-F01-A05-crsp-cumulative-share-volume-adjustment/implementations/typescript/crsp_cumulative_share_volume_adjustment.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** CRSP CIZ 2.0 cumulative share/volume adjustment reference.
 *
 * This is the documented CRSP vendor convention. A CRSP price factor is not
 * accepted as a substitute for DlyCumFacShr or MthCumFacShr.
 */

export const SCHEMA_VERSION = "CRSP_US_STOCK_CIZ_2_0" as const;
export const ROUNDING_DIGITS = 12;

type Frequency = "daily" | "monthly";
type FactorStatus = "observed" | "continued_across_gap" | "missing";
type MonthlyFlagCode = "N" | "S" | "O" | "B";
type MonthlyFlagState = "none" | "within_period" | "unknown";

export interface CrspInputRecord {
  packageSecurityKey: string;
  date: string;
  frequency: Frequency;
  crspFactorField: "DlyCumFacShr" | "MthCumFacShr";
  crspCumulativeShareFactor: number | null;
  crspFactorStatus: FactorStatus;
  rawSharesOutstandingThousands: number | null;
  rawVolumeShares: number | null;
  crspMthFacShrFlg?: MonthlyFlagCode | null;
}

export interface CrspAdjustmentInput {
  schemaVersion: typeof SCHEMA_VERSION;
  sourceRelease: string;
  crspBasisDate: string;
  extractCoverage: "full_history" | "partial_extract";
  records: CrspInputRecord[];
}

const factorFields: Record<Frequency, "DlyCumFacShr" | "MthCumFacShr"> = {
  daily: "DlyCumFacShr",
  monthly: "MthCumFacShr",
};
const factorStatuses = new Set<FactorStatus>(["observed", "continued_across_gap", "missing"]);
const monthlyFlagCodes = new Set<MonthlyFlagCode>(["N", "S", "O", "B"]);

function isoDate(value: unknown, name: string): string {
  if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    throw new TypeError(`${name} must be YYYY-MM-DD`);
  }
  const parsed = new Date(`${value}T00:00:00Z`);
  if (Number.isNaN(parsed.valueOf()) || parsed.toISOString().slice(0, 10) !== value) {
    throw new RangeError(`${name} must be YYYY-MM-DD`);
  }
  return value;
}

function numberOrNull(value: unknown, name: string, positive = false): number | null {
  if (value === null) return null;
  if (typeof value !== "number" || !Number.isFinite(value)) {
    throw new TypeError(`${name} must be finite or null`);
  }
  if (positive ? value <= 0 : value < 0) {
    throw new RangeError(`${name} must be ${positive ? "positive" : "non-negative"}`);
  }
  return value;
}

function rounded(value: number): number {
  if (!Number.isFinite(value)) throw new RangeError("value must be finite before rounding");
  const negative = value < 0;
  const [mantissa, exponentText = "0"] = Math.abs(value).toString().toLowerCase().split("e");
  const [whole, fraction = ""] = mantissa.split(".");
  const digits = BigInt(`${whole}${fraction}`);
  const decimalExponent = Number(exponentText) - fraction.length;
  const scaledExponent = decimalExponent + ROUNDING_DIGITS;
  let scaledInteger: bigint;
  if (scaledExponent >= 0) {
    scaledInteger = digits * (10n ** BigInt(scaledExponent));
  } else {
    const divisor = 10n ** BigInt(-scaledExponent);
    const quotient = digits / divisor;
    const remainder = digits % divisor;
    scaledInteger = quotient + (remainder * 2n >= divisor ? 1n : 0n);
  }
  if (scaledInteger === 0n) return 0;
  const padded = scaledInteger.toString().padStart(ROUNDING_DIGITS + 1, "0");
  const integerPart = padded.slice(0, -ROUNDING_DIGITS);
  const fractionalPart = padded.slice(-ROUNDING_DIGITS).replace(/0+$/, "");
  const decimalText = fractionalPart ? `${integerPart}.${fractionalPart}` : integerPart;
  return Number(`${negative ? "-" : ""}${decimalText}`);
}

function quantityResult(
  raw: number | null,
  factor: number | null,
  factorStatus: FactorStatus,
  monthlyVolumeFlag?: MonthlyFlagState,
): [string, number | null, number | null] {
  if (raw === null) return ["missing_raw", null, null];
  if (factorStatus === "missing") return ["missing_crsp_factor", null, null];
  if (monthlyVolumeFlag === "within_period" || monthlyVolumeFlag === "unknown") {
    return ["blocked_mixed_basis_month", null, null];
  }
  if (factor === null) throw new Error("internal factor validation failure");
  const adjusted = rounded(raw * factor);
  const residual = rounded(adjusted / factor - raw);
  const status = factorStatus === "continued_across_gap"
    ? "computed_crsp_gap_assumption"
    : "computed_crsp";
  return [status, adjusted, residual];
}

export function calculate(data: CrspAdjustmentInput) {
  if (!data || typeof data !== "object" || Array.isArray(data)) {
    throw new TypeError("data must be an object");
  }
  if (data.schemaVersion !== SCHEMA_VERSION) {
    throw new RangeError(`schemaVersion must equal ${SCHEMA_VERSION}`);
  }
  if (typeof data.sourceRelease !== "string" || !data.sourceRelease.trim()) {
    throw new TypeError("sourceRelease must be a non-empty string");
  }
  const basisDate = isoDate(data.crspBasisDate, "crspBasisDate");
  if (data.extractCoverage !== "full_history" && data.extractCoverage !== "partial_extract") {
    throw new RangeError("extractCoverage must be full_history or partial_extract");
  }
  if (!Array.isArray(data.records) || data.records.length === 0) {
    throw new TypeError("records must be a non-empty list");
  }

  let expectedSecurityKey: string | null = null;
  let expectedFrequency: Frequency | null = null;
  let previousDate: string | null = null;
  let lastFactor: number | null = null;
  let lastFactorStatus: FactorStatus | null = null;
  const rows = data.records.map((record, index) => {
    if (!record || typeof record !== "object" || Array.isArray(record)) {
      throw new TypeError(`records[${index}] must be an object`);
    }
    if (typeof record.packageSecurityKey !== "string" || !record.packageSecurityKey.trim()) {
      throw new TypeError(`records[${index}].packageSecurityKey must be a non-empty string`);
    }
    const securityKey = record.packageSecurityKey.trim();
    if (!securityKey.startsWith("SYNTHETIC-")) {
      throw new RangeError("packageSecurityKey must begin SYNTHETIC-; real CRSP PERMNO belongs in licensed lineage");
    }
    expectedSecurityKey ??= securityKey;
    if (securityKey !== expectedSecurityKey) {
      throw new RangeError("one calculation may contain only one packageSecurityKey");
    }
    const recordDate = isoDate(record.date, `records[${index}].date`);
    if (recordDate > basisDate) throw new RangeError("record date cannot be after the CRSP basis date");
    if (previousDate !== null && recordDate <= previousDate) {
      throw new RangeError("record dates must be strictly increasing");
    }
    previousDate = recordDate;
    if (record.frequency !== "daily" && record.frequency !== "monthly") {
      throw new RangeError("frequency must be daily or monthly");
    }
    expectedFrequency ??= record.frequency;
    if (record.frequency !== expectedFrequency) {
      throw new RangeError("one calculation cannot mix daily and monthly CRSP frequencies");
    }
    const expectedField = factorFields[record.frequency];
    if (record.crspFactorField !== expectedField) {
      throw new RangeError(`${record.frequency} records require CRSP field ${expectedField}`);
    }
    if (!factorStatuses.has(record.crspFactorStatus)) throw new RangeError("invalid crspFactorStatus");
    const factor = numberOrNull(record.crspCumulativeShareFactor, "crspCumulativeShareFactor", true);
    if (record.crspFactorStatus === "missing" && factor !== null) {
      throw new RangeError("a missing CRSP factor must have a null value");
    }
    if (record.crspFactorStatus !== "missing" && factor === null) {
      throw new RangeError("an observed CRSP factor must have a value");
    }
    lastFactor = factor;
    lastFactorStatus = record.crspFactorStatus;
    const shares = numberOrNull(record.rawSharesOutstandingThousands, "rawSharesOutstandingThousands");
    const volume = numberOrNull(record.rawVolumeShares, "rawVolumeShares");
    if (shares === null && volume === null) {
      throw new RangeError("each row needs a raw shares or raw volume value");
    }
    const monthlyCode = record.crspMthFacShrFlg;
    let monthlyState: MonthlyFlagState | undefined;
    if (record.frequency === "monthly") {
      if (monthlyCode === undefined || (monthlyCode !== null && !monthlyFlagCodes.has(monthlyCode))) {
        throw new RangeError("monthly rows require CRSP MthFacShrFlg code N, S, O, B, or null");
      }
      monthlyState = monthlyCode === null ? "unknown" : monthlyCode === "N" ? "none" : "within_period";
    } else if (monthlyCode !== undefined) {
      throw new RangeError("daily rows must not set crspMthFacShrFlg");
    }

    const [sharesStatus, adjustedShares, sharesResidual] = quantityResult(
      shares, factor, record.crspFactorStatus,
    );
    const [volumeStatus, adjustedVolume, volumeResidual] = quantityResult(
      volume,
      factor,
      record.crspFactorStatus,
      monthlyState,
    );
    return {
      packageSecurityKey: securityKey,
      date: recordDate,
      frequency: record.frequency,
      crspFactorField: expectedField,
      crspCumulativeShareFactor: factor,
      crspFactorStatus: record.crspFactorStatus,
      crspMthFacShrFlg: record.frequency === "monthly" ? monthlyCode : null,
      crspMonthlyShareFactorState: monthlyState ?? null,
      crspSharesStatus: sharesStatus,
      crspAdjustedSharesOutstandingThousands: adjustedShares,
      crspSharesRoundTripResidual: sharesResidual,
      crspVolumeStatus: volumeStatus,
      crspAdjustedVolumeShares: adjustedVolume,
      crspVolumeRoundTripResidual: volumeResidual,
    };
  });

  if (data.extractCoverage === "full_history" && (
    previousDate !== basisDate || lastFactorStatus !== "observed" || lastFactor !== 1
  )) {
    throw new RangeError("full_history must end on the CRSP basis date with observed factor 1");
  }

  return {
    schemaVersion: SCHEMA_VERSION,
    sourceRelease: data.sourceRelease.trim(),
    packageSecurityKey: expectedSecurityKey,
    crspBasisDate: basisDate,
    extractCoverage: data.extractCoverage,
    roundingDigits: ROUNDING_DIGITS,
    rows,
  };
}
