/**
 * Absolute Breadth Index
 *
 * Topic D04-F01-A05 · Market Breadth and Internals / Advance/Decline Breadth · difficulty 2
 * Shape: snapshot-evaluate · entry: evaluateAbsoluteBreadthIndex()
 * Article: https://thefintechbuilder.com/market-breadth-and-internals/advance-decline-breadth/absolute-breadth-index/
 * Repo:    https://github.com/IslamBaraka90/Fintech-Absolute-Breadth-Index-Market-Breadth-algorithm
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D04-F01-A05-absolute-breadth-index
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { evaluateAbsoluteBreadthIndex as run } from "./impl.ts";

export const meta = {
  id: "D04-F01-A05",
  title: "Absolute Breadth Index",
  slug: "absolute-breadth-index",
  domainId: "D04",
  domain: "Market Breadth and Internals",
  familyId: "D04-F01",
  family: "Advance/Decline Breadth",
  difficulty: 2,
  archetype: "snapshot-evaluate",
  entry: "evaluateAbsoluteBreadthIndex",
  path: "market-breadth-and-internals/advance-decline-breadth/absolute-breadth-index",
  articleUrl: "https://thefintechbuilder.com/market-breadth-and-internals/advance-decline-breadth/absolute-breadth-index/",
  repoUrl: "https://github.com/IslamBaraka90/Fintech-Absolute-Breadth-Index-Market-Breadth-algorithm",
} as const;
