// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D40-model-validation-and-backtesting/D40-F05-classification-and-score-validation/D40-F05-A09-slice-based-validation-by-sector-country-and-regime/implementations/typescript/classification-validation.ts
// Re-run `npm run sync` after changing the catalog implementation.
//
// This family shares one implementation across its topics; the body lives at
// src/_shared/classification-validation.ts and is re-exported here so the public surface of
// this subpath is unchanged.

export * from "../../../_shared/classification-validation.ts";
