/**
 * Vortex Indicator (+VI/−VI)
 *
 * Topic D07-F02-A10 · Technical Indicators / Trend Systems · difficulty 2
 * Shape: series-transform · entry: vortexIndicatorViVi()
 * Article: https://thefintechbuilder.com/technical-indicators/trend-systems/vortex-indicator-vi-vi/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F02-A10-vortex-indicator-vi-vi
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { vortexIndicatorViVi as run } from "./impl.ts";

export const meta = {
  id: "D07-F02-A10",
  title: "Vortex Indicator (+VI/−VI)",
  slug: "vortex-indicator-vi-vi",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F02",
  family: "Trend Systems",
  difficulty: 2,
  archetype: "series-transform",
  entry: "vortexIndicatorViVi",
  path: "technical-indicators/trend-systems/vortex-indicator-vi-vi",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/trend-systems/vortex-indicator-vi-vi/",
  repoUrl: null,
} as const;
