/**
 * Percentage-of-Volume Execution
 *
 * Topic D13-F01-A04 · Execution and Transaction Cost Analysis / Schedule-Based Execution · difficulty 3
 * Shape: record-transform · entry: percentageOfVolumeExecution()
 * Article: https://thefintechbuilder.com/execution-and-transaction-cost-analysis/schedule-based-execution/percentage-of-volume-execution/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D13-F01-A04-percentage-of-volume-execution
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { percentageOfVolumeExecution as run } from "./impl.ts";

export const meta = {
  id: "D13-F01-A04",
  title: "Percentage-of-Volume Execution",
  slug: "percentage-of-volume-execution",
  domainId: "D13",
  domain: "Execution and Transaction Cost Analysis",
  familyId: "D13-F01",
  family: "Schedule-Based Execution",
  difficulty: 3,
  archetype: "record-transform",
  entry: "percentageOfVolumeExecution",
  path: "execution-and-transaction-cost-analysis/schedule-based-execution/percentage-of-volume-execution",
  articleUrl: "https://thefintechbuilder.com/execution-and-transaction-cost-analysis/schedule-based-execution/percentage-of-volume-execution/",
  repoUrl: null,
} as const;
