/**
 * Unified Candlestick Pattern Registry
 *
 * Topic D06-F05-A01 · Price Action and Candlesticks / Candlestick Scanning and Context · difficulty 2
 * Shape: record-transform · entry: buildRegistry()
 * Article: https://thefintechbuilder.com/price-action-and-candlesticks/candlestick-scanning-and-context/unified-candlestick-pattern-registry/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D06-F05-A01-unified-candlestick-pattern-registry
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { buildRegistry as run } from "./impl.ts";

export const meta = {
  id: "D06-F05-A01",
  title: "Unified Candlestick Pattern Registry",
  slug: "unified-candlestick-pattern-registry",
  domainId: "D06",
  domain: "Price Action and Candlesticks",
  familyId: "D06-F05",
  family: "Candlestick Scanning and Context",
  difficulty: 2,
  archetype: "record-transform",
  entry: "buildRegistry",
  path: "price-action-and-candlesticks/candlestick-scanning-and-context/unified-candlestick-pattern-registry",
  articleUrl: "https://thefintechbuilder.com/price-action-and-candlesticks/candlestick-scanning-and-context/unified-candlestick-pattern-registry/",
  repoUrl: null,
} as const;
