/**
 * Accumulation/Distribution Line
 *
 * Topic D07-F05-A02 · Technical Indicators / Volume Indicators · difficulty 2
 * Shape: series-transform · entry: accumulationDistributionLine()
 * Article: https://thefintechbuilder.com/technical-indicators/volume-indicators/accumulation-distribution-line/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F05-A02-accumulation-distribution-line
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { accumulationDistributionLine as run } from "./impl.ts";

export const meta = {
  id: "D07-F05-A02",
  title: "Accumulation/Distribution Line",
  slug: "accumulation-distribution-line",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F05",
  family: "Volume Indicators",
  difficulty: 2,
  archetype: "series-transform",
  entry: "accumulationDistributionLine",
  path: "technical-indicators/volume-indicators/accumulation-distribution-line",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/volume-indicators/accumulation-distribution-line/",
  repoUrl: null,
} as const;
