/**
 * Quadratic-Weighted Moving Average
 *
 * Topic D07-F01-A21 · Technical Indicators / Trend Smoothing · difficulty 2
 * Shape: series-transform · entry: quadraticWeightedMovingAverage()
 * Article: https://thefintechbuilder.com/technical-indicators/trend-smoothing/quadratic-weighted-moving-average/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F01-A21-quadratic-weighted-moving-average
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { quadraticWeightedMovingAverage as run } from "./impl.ts";

export const meta = {
  id: "D07-F01-A21",
  title: "Quadratic-Weighted Moving Average",
  slug: "quadratic-weighted-moving-average",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F01",
  family: "Trend Smoothing",
  difficulty: 2,
  archetype: "series-transform",
  entry: "quadraticWeightedMovingAverage",
  path: "technical-indicators/trend-smoothing/quadratic-weighted-moving-average",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/trend-smoothing/quadratic-weighted-moving-average/",
  repoUrl: null,
} as const;
