/**
 * High-Low Index
 *
 * Topic D04-F03-A03 · Market Breadth and Internals / High/Low and Trend Breadth · difficulty 3
 * Shape: record-transform · entry: calculate()
 * Article: https://thefintechbuilder.com/market-breadth-and-internals/high-low-and-trend-breadth/high-low-index/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D04-F03-A03-high-low-index
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { calculate as run } from "./impl.ts";

export const meta = {
  id: "D04-F03-A03",
  title: "High-Low Index",
  slug: "high-low-index",
  domainId: "D04",
  domain: "Market Breadth and Internals",
  familyId: "D04-F03",
  family: "High/Low and Trend Breadth",
  difficulty: 3,
  archetype: "record-transform",
  entry: "calculate",
  path: "market-breadth-and-internals/high-low-and-trend-breadth/high-low-index",
  articleUrl: "https://thefintechbuilder.com/market-breadth-and-internals/high-low-and-trend-breadth/high-low-index/",
  repoUrl: null,
} as const;
