// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D09-statistical-time-series/D09-F03-multivariate-systems/D09-F03-A05-forecast-error-variance-decomposition/implementations/typescript/multivariate.ts
// Re-run `npm run sync` after changing the catalog implementation.
//
// This family shares one implementation across its topics; the body lives at
// src/_shared/multivariate.ts and is re-exported here so the public surface of
// this subpath is unchanged.

export * from "../../../_shared/multivariate.ts";
