/**
 * Money Flow Multiplier and Money Flow Volume
 *
 * Topic D07-F05-A18 · Technical Indicators / Volume Indicators · difficulty 2
 * Shape: series-transform · entry: moneyFlowMultiplierAndMoneyFlowVolume()
 * Article: https://thefintechbuilder.com/technical-indicators/volume-indicators/money-flow-multiplier-and-money-flow-volume/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F05-A18-money-flow-multiplier-and-money-flow-volume
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { moneyFlowMultiplierAndMoneyFlowVolume as run } from "./impl.ts";

export const meta = {
  id: "D07-F05-A18",
  title: "Money Flow Multiplier and Money Flow Volume",
  slug: "money-flow-multiplier-and-money-flow-volume",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F05",
  family: "Volume Indicators",
  difficulty: 2,
  archetype: "series-transform",
  entry: "moneyFlowMultiplierAndMoneyFlowVolume",
  path: "technical-indicators/volume-indicators/money-flow-multiplier-and-money-flow-volume",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/volume-indicators/money-flow-multiplier-and-money-flow-volume/",
  repoUrl: null,
} as const;
