/**
 * Weighted Close
 *
 * Topic D07-F08-A03 · Technical Indicators / Price Transforms · difficulty 2
 * Shape: series-transform · entry: weightedClose()
 * Article: https://thefintechbuilder.com/technical-indicators/price-transforms/weighted-close/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F08-A03-weighted-close
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { weightedClose as run } from "./impl.ts";

export const meta = {
  id: "D07-F08-A03",
  title: "Weighted Close",
  slug: "weighted-close",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F08",
  family: "Price Transforms",
  difficulty: 2,
  archetype: "series-transform",
  entry: "weightedClose",
  path: "technical-indicators/price-transforms/weighted-close",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/price-transforms/weighted-close/",
  repoUrl: null,
} as const;
