/**
 * Ranks, Ties, and Percentile Rank
 *
 * Topic D00-F04-A07 · Financial Mathematics, Statistics, and Data Foundations / Location, Ranking, and Exploratory Summaries · difficulty 1
 * Shape: record-transform · entry: ranksTiesAndPercentileRank()
 * Article: https://thefintechbuilder.com/foundations/location-ranking-and-exploratory-summaries/ranks-ties-and-percentile-rank/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F04-A07-ranks-ties-and
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { ranksTiesAndPercentileRank as run } from "./impl.ts";

export const meta = {
  id: "D00-F04-A07",
  title: "Ranks, Ties, and Percentile Rank",
  slug: "ranks-ties-and-percentile-rank",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F04",
  family: "Location, Ranking, and Exploratory Summaries",
  difficulty: 1,
  archetype: "record-transform",
  entry: "ranksTiesAndPercentileRank",
  path: "foundations/location-ranking-and-exploratory-summaries/ranks-ties-and-percentile-rank",
  articleUrl: "https://thefintechbuilder.com/foundations/location-ranking-and-exploratory-summaries/ranks-ties-and-percentile-rank/",
  repoUrl: null,
} as const;
