/**
 * AutoReg
 *
 * Topic D09-F02-A01 · Statistical Time Series / Forecast Models · difficulty 2
 * Shape: record-transform · entry: forecastAutoReg()
 * Article: https://thefintechbuilder.com/statistical-time-series/forecast-models/autoreg/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D09-F02-A01-autoreg
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { forecastAutoReg as run } from "./impl.ts";

export const meta = {
  id: "D09-F02-A01",
  title: "AutoReg",
  slug: "autoreg",
  domainId: "D09",
  domain: "Statistical Time Series",
  familyId: "D09-F02",
  family: "Forecast Models",
  difficulty: 2,
  archetype: "record-transform",
  entry: "forecastAutoReg",
  path: "statistical-time-series/forecast-models/autoreg",
  articleUrl: "https://thefintechbuilder.com/statistical-time-series/forecast-models/autoreg/",
  repoUrl: null,
} as const;
