/**
 * High-Wave Candle
 *
 * Topic D06-F02-A12 · Price Action and Candlesticks / Single-Candle Patterns · difficulty 2
 * Shape: record-transform · entry: highWaveCandle()
 * Article: https://thefintechbuilder.com/price-action-and-candlesticks/single-candle-patterns/high-wave-candle/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D06-F02-A12-high-wave-candle
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { highWaveCandle as run } from "./impl.ts";

export const meta = {
  id: "D06-F02-A12",
  title: "High-Wave Candle",
  slug: "high-wave-candle",
  domainId: "D06",
  domain: "Price Action and Candlesticks",
  familyId: "D06-F02",
  family: "Single-Candle Patterns",
  difficulty: 2,
  archetype: "record-transform",
  entry: "highWaveCandle",
  path: "price-action-and-candlesticks/single-candle-patterns/high-wave-candle",
  articleUrl: "https://thefintechbuilder.com/price-action-and-candlesticks/single-candle-patterns/high-wave-candle/",
  repoUrl: null,
} as const;
