/**
 * Leakage-Free Fitting, Scaling, and Preprocessing
 *
 * Topic D00-F12-A08 · Financial Mathematics, Statistics, and Data Foundations / Statistical Computing and Reproducibility · difficulty 1
 * Shape: record-transform · entry: leakageFreeFittingScalingAndPreprocessing()
 * Article: https://thefintechbuilder.com/foundations/statistical-computing-and-reproducibility/leakage-free-fitting-scaling-and-preprocessing/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F12-A08-leakage-free-fit
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { leakageFreeFittingScalingAndPreprocessing as run } from "./impl.ts";

export const meta = {
  id: "D00-F12-A08",
  title: "Leakage-Free Fitting, Scaling, and Preprocessing",
  slug: "leakage-free-fitting-scaling-and-preprocessing",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F12",
  family: "Statistical Computing and Reproducibility",
  difficulty: 1,
  archetype: "record-transform",
  entry: "leakageFreeFittingScalingAndPreprocessing",
  path: "foundations/statistical-computing-and-reproducibility/leakage-free-fitting-scaling-and-preprocessing",
  articleUrl: "https://thefintechbuilder.com/foundations/statistical-computing-and-reproducibility/leakage-free-fitting-scaling-and-preprocessing/",
  repoUrl: null,
} as const;
