/**
 * ARIMA
 *
 * Topic D09-F02-A03 · Statistical Time Series / Forecast Models · difficulty 3
 * Shape: record-transform · entry: forecastARIMA()
 * Article: https://thefintechbuilder.com/statistical-time-series/forecast-models/arima/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D09-F02-A03-arima
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { forecastARIMA as run } from "./impl.ts";

export const meta = {
  id: "D09-F02-A03",
  title: "ARIMA",
  slug: "arima",
  domainId: "D09",
  domain: "Statistical Time Series",
  familyId: "D09-F02",
  family: "Forecast Models",
  difficulty: 3,
  archetype: "record-transform",
  entry: "forecastARIMA",
  path: "statistical-time-series/forecast-models/arima",
  articleUrl: "https://thefintechbuilder.com/statistical-time-series/forecast-models/arima/",
  repoUrl: null,
} as const;
