// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D01-market-data-engineering/D01-F04-data-quality/D01-F04-A01-missing-bar-gap-classifier/implementations/typescript/missingBarGapClassifier.ts
// Re-run `npm run sync` after changing the catalog implementation.

export type GapClass =
  | "present"
  | "closed_session"
  | "expected_halt"
  | "feed_outage"
  | "inactive"
  | "bar_builder_error"
  | "unknown"
  | "conflicting_evidence";

export type BarState = "present" | "absent" | "unknown";
export type SessionStatus = "open" | "closed" | "unknown" | "conflicting";
export type HaltStatus = "active" | "inactive" | "unknown" | "conflicting";
export type HeartbeatStatus = "healthy" | "lost" | "unknown" | "conflicting";
export type SequenceStatus = "continuous" | "gap" | "unknown" | "conflicting";
export type ActivityStatus = "trades" | "no_trades" | "unknown" | "conflicting";

export interface GapRow {
  timestamp?: string;
  bar_state: BarState;
  session_status: SessionStatus;
  halt_status: HaltStatus;
  heartbeat_status: HeartbeatStatus;
  sequence_status: SequenceStatus;
  activity_status: ActivityStatus;
  activity_independent: boolean;
  evidence_ids: string[];
  [key: string]: unknown;
}

export interface GapDiagnosis {
  classification: GapClass;
  decisive_layer: string;
  reason: string;
  evidence_ids: string[];
  warnings: string[];
}

const allowed: Record<string, Set<string>> = {
  bar_state: new Set(["present", "absent", "unknown"]),
  session_status: new Set(["open", "closed", "unknown", "conflicting"]),
  halt_status: new Set(["active", "inactive", "unknown", "conflicting"]),
  heartbeat_status: new Set(["healthy", "lost", "unknown", "conflicting"]),
  sequence_status: new Set(["continuous", "gap", "unknown", "conflicting"]),
  activity_status: new Set(["trades", "no_trades", "unknown", "conflicting"]),
};

function validate(row: GapRow): void {
  for (const [field, values] of Object.entries(allowed)) {
    if (!values.has(row[field] as string)) {
      throw new Error(`${field} has an invalid value`);
    }
  }
  if (typeof row.activity_independent !== "boolean") {
    throw new Error("activity_independent must be a boolean");
  }
  if (
    !Array.isArray(row.evidence_ids) ||
    row.evidence_ids.length === 0 ||
    row.evidence_ids.some((value) => typeof value !== "string" || value.trim() === "")
  ) {
    throw new Error("evidence_ids must be a non-empty list of strings");
  }
}

function result(
  classification: GapClass,
  decisive_layer: string,
  reason: string,
  row: GapRow,
  warnings: string[] = [],
): GapDiagnosis {
  return { classification, decisive_layer, reason, evidence_ids: [...row.evidence_ids], warnings };
}

export function diagnoseGap(row: GapRow): GapDiagnosis {
  validate(row);
  if (row.bar_state === "present") return result("present", "bar", "A validated bar is materialized.", row);
  if (row.bar_state === "unknown") return result("unknown", "bar", "Bar presence has not been established.", row);

  if (row.session_status === "conflicting") return result("conflicting_evidence", "session", "Calendar sources disagree about whether the slot belongs to a session.", row);
  if (row.session_status === "unknown") return result("unknown", "session", "Session membership is unavailable.", row);
  if (row.session_status === "closed") return result("closed_session", "session", "Authoritative session evidence excludes this slot.", row);

  if (row.halt_status === "conflicting") return result("conflicting_evidence", "market_state", "Market-status sources disagree about an active halt.", row);
  if (row.halt_status === "unknown") return result("unknown", "market_state", "Halt state is not known.", row);
  if (row.halt_status === "active") return result("expected_halt", "market_state", "An authoritative halt interval covers the missing slot.", row);

  if (row.heartbeat_status === "conflicting" || row.sequence_status === "conflicting") return result("conflicting_evidence", "transport", "Transport-health evidence conflicts.", row);
  if (row.heartbeat_status === "lost" || row.sequence_status === "gap") return result("feed_outage", "transport", "A lost heartbeat or sequenced-message gap is positive feed-failure evidence.", row);
  if (row.heartbeat_status === "unknown" || row.sequence_status === "unknown") return result("unknown", "transport", "Feed continuity is not fully observed.", row);

  if (row.activity_status === "conflicting") return result("conflicting_evidence", "activity", "Activity sources disagree about whether trades occurred.", row);
  if (row.activity_status === "unknown") return result("unknown", "activity", "Trade activity is not known.", row);
  if (!row.activity_independent) return result("unknown", "activity", "Activity evidence is not independent of the missing bar path.", row, ["Do not use the failed path to prove that no trades occurred."]);
  if (row.activity_status === "no_trades") return result("inactive", "activity", "Independent activity evidence reports no trades in a healthy, open interval.", row);
  return result("bar_builder_error", "construction", "Independent trade evidence exists, but the expected bar is absent.", row);
}

export function classifyGap(row: GapRow): GapClass {
  return diagnoseGap(row).classification;
}

export function classifyRows(rows: GapRow[]) {
  return rows.map((row) => ({ ...row, ...diagnoseGap(row) }));
}
