/**
 * Multi-Indicator Divergence Confluence
 *
 * Topic D08-F05-A07 · Geometric Chart Patterns / Indicator Divergence Detection · difficulty 4
 * Shape: record-transform · entry: multiIndicatorDivergenceConfluence()
 * Article: https://thefintechbuilder.com/geometric-chart-patterns/indicator-divergence-detection/multi-indicator-divergence-confluence/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D08-F05-A07-multi-indicator-divergence-confluence
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { multiIndicatorDivergenceConfluence as run } from "./impl.ts";

export const meta = {
  id: "D08-F05-A07",
  title: "Multi-Indicator Divergence Confluence",
  slug: "multi-indicator-divergence-confluence",
  domainId: "D08",
  domain: "Geometric Chart Patterns",
  familyId: "D08-F05",
  family: "Indicator Divergence Detection",
  difficulty: 4,
  archetype: "record-transform",
  entry: "multiIndicatorDivergenceConfluence",
  path: "geometric-chart-patterns/indicator-divergence-detection/multi-indicator-divergence-confluence",
  articleUrl: "https://thefintechbuilder.com/geometric-chart-patterns/indicator-divergence-detection/multi-indicator-divergence-confluence/",
  repoUrl: null,
} as const;
