// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F03-momentum/D07-F03-A15-trix/implementations/typescript/trix.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F03-A15: TRIX. */
import { trix as nativeTrix, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F03-A15";
export const TITLE = "TRIX";

export function trix(input: TopicInput): TopicResult {
  return nativeTrix(input);
}
