/**
 * Donchian Channels
 *
 * Topic D07-F04-A05 · Technical Indicators / Volatility and Channels · difficulty 2
 * Shape: series-transform · entry: donchian_channels()
 * Article: https://thefintechbuilder.com/technical-indicators/volatility-and-channels/donchian-channels/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F04-A05-donchian-channels
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { donchian_channels as run } from "./impl.ts";

export const meta = {
  id: "D07-F04-A05",
  title: "Donchian Channels",
  slug: "donchian-channels",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F04",
  family: "Volatility and Channels",
  difficulty: 2,
  archetype: "series-transform",
  entry: "donchian_channels",
  path: "technical-indicators/volatility-and-channels/donchian-channels",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/volatility-and-channels/donchian-channels/",
  repoUrl: null,
} as const;
