/**
 * Rolling Support and Resistance
 *
 * Topic D08-F01-A10 · Geometric Chart Patterns / Pivots and Levels · difficulty 2
 * Shape: record-transform · entry: rollingSupportAndResistance()
 * Article: https://thefintechbuilder.com/geometric-chart-patterns/pivots-and-levels/rolling-support-and-resistance/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D08-F01-A10-rolling-support-and-resistance
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { rollingSupportAndResistance as run } from "./impl.ts";

export const meta = {
  id: "D08-F01-A10",
  title: "Rolling Support and Resistance",
  slug: "rolling-support-and-resistance",
  domainId: "D08",
  domain: "Geometric Chart Patterns",
  familyId: "D08-F01",
  family: "Pivots and Levels",
  difficulty: 2,
  archetype: "record-transform",
  entry: "rollingSupportAndResistance",
  path: "geometric-chart-patterns/pivots-and-levels/rolling-support-and-resistance",
  articleUrl: "https://thefintechbuilder.com/geometric-chart-patterns/pivots-and-levels/rolling-support-and-resistance/",
  repoUrl: null,
} as const;
