/**
 * Percentage Price Oscillator (PPO): Normalize the MACD Spread
 *
 * Topic D07-F02-A02 · Technical Indicators / Trend Systems · difficulty 2
 * Shape: series-transform · entry: ppo()
 * Article: https://thefintechbuilder.com/technical-indicators/trend-systems/percentage-price-oscillator/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F02-A02-percentage-price-oscillator
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { ppo as run } from "./impl.ts";

export const meta = {
  id: "D07-F02-A02",
  title: "Percentage Price Oscillator (PPO): Normalize the MACD Spread",
  slug: "percentage-price-oscillator",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F02",
  family: "Trend Systems",
  difficulty: 2,
  archetype: "series-transform",
  entry: "ppo",
  path: "technical-indicators/trend-systems/percentage-price-oscillator",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/trend-systems/percentage-price-oscillator/",
  repoUrl: null,
} as const;
