/**
 * Extended Kalman Filter
 *
 * Topic D09-F04-A02 · Statistical Time Series / State and Regime Models · difficulty 4
 * Shape: record-transform · entry: runFilter()
 * Article: https://thefintechbuilder.com/statistical-time-series/state-and-regime-models/extended-kalman-filter/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D09-F04-A02-extended-kalman-filter
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { runFilter as run } from "./impl.ts";

export const meta = {
  id: "D09-F04-A02",
  title: "Extended Kalman Filter",
  slug: "extended-kalman-filter",
  domainId: "D09",
  domain: "Statistical Time Series",
  familyId: "D09-F04",
  family: "State and Regime Models",
  difficulty: 4,
  archetype: "record-transform",
  entry: "runFilter",
  path: "statistical-time-series/state-and-regime-models/extended-kalman-filter",
  articleUrl: "https://thefintechbuilder.com/statistical-time-series/state-and-regime-models/extended-kalman-filter/",
  repoUrl: null,
} as const;
