// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D04-market-breadth-and-internals/D04-F04-thrust-and-pressure/D04-F04-A04-upside-downside-volume-ratio/implementations/typescript/upside_downside_volume_ratio.ts
// Re-run `npm run sync` after changing the catalog implementation.

export type Result = Record<string, any>;
const numberValue = (value: unknown, name: string): number => {
  if (typeof value !== "number" || !Number.isFinite(value)) throw new Error(`${name} must be a finite number`);
  return value;
};

export function calculate(row:any):Result {
  if(row.ready===false)return{status:"incomplete",reason:"unready observation",value:null};
  const up=numberValue(row.advancing_volume,"advancing_volume"),down=numberValue(row.declining_volume,"declining_volume");
  if(up<0||down<0)return{status:"incomplete",reason:"negative volume",value:null};
  if(down===0)return up>0?{status:"unbounded",reason:"zero declining volume",value:null}:{status:"incomplete",reason:"no classified volume",value:null};
  return{status:"resolved",value:up/down};
}
