// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D08-geometric-chart-patterns/D08-F07-market-structure-breakouts-and-regimes/D08-F07-A09-hurst-exponent/implementations/typescript/hurst_exponent.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D08-F07-A09: Hurst Exponent. */
import { hurstExponent as nativeHurstExponent, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D08-F07-A09";
export const TITLE = "Hurst Exponent";

export function hurstExponent(input: TopicInput): TopicResult {
  return nativeHurstExponent(input);
}
