/**
 * Volatility-Auction Reopening
 *
 * Topic D12-F02-A05 · Matching Engines and Venue Logic / Auctions · difficulty 5
 * Shape: record-transform · entry: volatilityAuctionReopening()
 * Article: https://thefintechbuilder.com/matching-engines-and-venue-logic/auctions/volatility-auction-reopening/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D12-F02-A05-volatility-auction-reopening
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { volatilityAuctionReopening as run } from "./impl.ts";

export const meta = {
  id: "D12-F02-A05",
  title: "Volatility-Auction Reopening",
  slug: "volatility-auction-reopening",
  domainId: "D12",
  domain: "Matching Engines and Venue Logic",
  familyId: "D12-F02",
  family: "Auctions",
  difficulty: 5,
  archetype: "record-transform",
  entry: "volatilityAuctionReopening",
  path: "matching-engines-and-venue-logic/auctions/volatility-auction-reopening",
  articleUrl: "https://thefintechbuilder.com/matching-engines-and-venue-logic/auctions/volatility-auction-reopening/",
  repoUrl: null,
} as const;
