/**
 * Ehlers Decycler
 *
 * Topic D09-F06-A08 · Statistical Time Series / Hilbert and Ehlers Cycle Analytics · difficulty 2
 * Shape: record-transform · entry: ehlersDecycler()
 * Article: https://thefintechbuilder.com/statistical-time-series/hilbert-and-ehlers-cycle-analytics/ehlers-decycler/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D09-F06-A08-ehlers-decycler
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { ehlersDecycler as run } from "./impl.ts";

export const meta = {
  id: "D09-F06-A08",
  title: "Ehlers Decycler",
  slug: "ehlers-decycler",
  domainId: "D09",
  domain: "Statistical Time Series",
  familyId: "D09-F06",
  family: "Hilbert and Ehlers Cycle Analytics",
  difficulty: 2,
  archetype: "record-transform",
  entry: "ehlersDecycler",
  path: "statistical-time-series/hilbert-and-ehlers-cycle-analytics/ehlers-decycler",
  articleUrl: "https://thefintechbuilder.com/statistical-time-series/hilbert-and-ehlers-cycle-analytics/ehlers-decycler/",
  repoUrl: null,
} as const;
