// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F08-price-transforms/D07-F08-A05-heikin-ashi-transform/implementations/typescript/heikin_ashi_transform.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F08-A05: Heikin-Ashi Transform. */
import { heikinAshiTransform as nativeHeikinAshiTransform, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F08-A05";
export const TITLE = "Heikin-Ashi Transform";

export function heikinAshiTransform(input: TopicInput): TopicResult {
  return nativeHeikinAshiTransform(input);
}
