// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D04-market-breadth-and-internals/D04-F05-concentration-and-diffusion/D04-F05-A05-factor-diffusion-index/implementations/typescript/factor_diffusion_index.ts
// Re-run `npm run sync` after changing the catalog implementation.
//
// This family shares one implementation across its topics; the body lives at
// src/_shared/sector_diffusion_index.ts and is re-exported here so the public surface of
// this subpath is unchanged.

export * from "../../../_shared/sector_diffusion_index.ts";
