/**
 * Factor Diffusion Index
 *
 * Topic D04-F05-A05 · Market Breadth and Internals / Concentration and Diffusion · difficulty 3
 * Shape: record-transform · entry: calculate()
 * Article: https://thefintechbuilder.com/market-breadth-and-internals/concentration-and-diffusion/factor-diffusion-index/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D04-F05-A05-factor-diffusion-index
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { calculate as run } from "./impl.ts";

export const meta = {
  id: "D04-F05-A05",
  title: "Factor Diffusion Index",
  slug: "factor-diffusion-index",
  domainId: "D04",
  domain: "Market Breadth and Internals",
  familyId: "D04-F05",
  family: "Concentration and Diffusion",
  difficulty: 3,
  archetype: "record-transform",
  entry: "calculate",
  path: "market-breadth-and-internals/concentration-and-diffusion/factor-diffusion-index",
  articleUrl: "https://thefintechbuilder.com/market-breadth-and-internals/concentration-and-diffusion/factor-diffusion-index/",
  repoUrl: null,
} as const;
