/**
 * Realized Spread
 *
 * Topic D11-F02-A03 · Market Microstructure / Liquidity and Spreads · difficulty 4
 * Shape: record-transform · entry: realizedSpread()
 * Article: https://thefintechbuilder.com/market-microstructure/liquidity-and-spreads/realized-spread/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D11-F02-A03-realized-spread
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { realizedSpread as run } from "./impl.ts";

export const meta = {
  id: "D11-F02-A03",
  title: "Realized Spread",
  slug: "realized-spread",
  domainId: "D11",
  domain: "Market Microstructure",
  familyId: "D11-F02",
  family: "Liquidity and Spreads",
  difficulty: 4,
  archetype: "record-transform",
  entry: "realizedSpread",
  path: "market-microstructure/liquidity-and-spreads/realized-spread",
  articleUrl: "https://thefintechbuilder.com/market-microstructure/liquidity-and-spreads/realized-spread/",
  repoUrl: null,
} as const;
