/**
 * Constant-Sum AMM
 *
 * Topic D25-F01-A02 · Digital Assets and On-Chain Finance / AMM Pricing · difficulty 2
 * Shape: record-transform · entry: constantSumQuote()
 * Article: https://thefintechbuilder.com/digital-assets-and-on-chain-finance/amm-pricing/constant-sum-amm/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D25-F01-A02-constant-sum-amm
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { constantSumQuote as run } from "./impl.ts";

export const meta = {
  id: "D25-F01-A02",
  title: "Constant-Sum AMM",
  slug: "constant-sum-amm",
  domainId: "D25",
  domain: "Digital Assets and On-Chain Finance",
  familyId: "D25-F01",
  family: "AMM Pricing",
  difficulty: 2,
  archetype: "record-transform",
  entry: "constantSumQuote",
  path: "digital-assets-and-on-chain-finance/amm-pricing/constant-sum-amm",
  articleUrl: "https://thefintechbuilder.com/digital-assets-and-on-chain-finance/amm-pricing/constant-sum-amm/",
  repoUrl: null,
} as const;
