/**
 * On-Balance Volume (OBV)
 *
 * Topic D07-F05-A01 · Technical Indicators / Volume Indicators · difficulty 2
 * Shape: series-transform · entry: obv()
 * Article: https://thefintechbuilder.com/technical-indicators/volume-indicators/obv/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F05-A01-obv
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { obv as run } from "./impl.ts";

export const meta = {
  id: "D07-F05-A01",
  title: "On-Balance Volume (OBV)",
  slug: "obv",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F05",
  family: "Volume Indicators",
  difficulty: 2,
  archetype: "series-transform",
  entry: "obv",
  path: "technical-indicators/volume-indicators/obv",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/volume-indicators/obv/",
  repoUrl: null,
} as const;
