/**
 * fintech-algorithms — The Fintech Builder algorithm library.
 *
 * The root export carries metadata only. Import an algorithm from its subpath,
 * which mirrors its article URL exactly:
 *
 *   import { ema } from "fintech-algorithms/technical-indicators/trend-smoothing/ema";
 *
 * Every algorithm is provider-agnostic: it takes plain arrays and plain objects.
 * Bring data from any source by mapping it into the documented input shape.
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: scripts/sync.mjs
// Re-run `npm run sync` after changing the catalog implementation.

export { topics, type TopicMeta, type Archetype } from "./_registry.ts";
import { topics } from "./_registry.ts";
import { modules } from "./_modules.ts";

/** Look up a topic's metadata by catalog id, e.g. "D07-F01-A02". */
export function topic(id: string) {
  return topics.find((t) => t.id === id);
}

/** Every topic in a domain, e.g. "D07". */
export function byDomain(domainId: string) {
  return topics.filter((t) => t.domainId === domainId);
}

/** Every topic in a family, e.g. "D01-F01". */
export function byFamily(familyId: string) {
  return topics.filter((t) => t.familyId === familyId);
}

/** Every topic sharing an input/output shape. */
export function byArchetype(archetype: string) {
  return topics.filter((t) => t.archetype === archetype);
}

/**
 * Dynamically load a topic module by catalog id.
 *
 * Prefer a direct subpath import when you know the algorithm at build time —
 * this exists for registry-driven callers (playgrounds, docs, test harnesses).
 */
export async function load(id: string): Promise<Record<string, unknown>> {
  const loader = modules[id];
  if (!loader) throw new Error(`unknown topic id: ${id}`);
  return loader();
}

/** Load a topic and return its primary function. */
export async function runner(id: string): Promise<(...args: unknown[]) => unknown> {
  const mod = await load(id);
  const fn = mod.run ?? mod[topic(id)?.entry ?? ""];
  if (typeof fn !== "function") throw new Error(`topic ${id} exposes no callable entry point`);
  return fn as (...args: unknown[]) => unknown;
}
