// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F02-trend-systems/D07-F02-A01-macd/implementations/typescript/macd.ts
// Re-run `npm run sync` after changing the catalog implementation.

export type MACDStatus = "warming_price_emas" | "warming_signal" | "ready";

export interface MACDPoint {
  index: number;
  value: number;
  fastEma: number | null;
  slowEma: number | null;
  macd: number | null;
  signal: number | null;
  histogram: number | null;
  status: MACDStatus;
}

function validateSpan(name: string, value: number): void {
  if (!Number.isInteger(value) || value < 1) {
    throw new RangeError(`${name} must be a positive integer`);
  }
}

function ema(values: readonly number[], span: number): Array<number | null> {
  const result: Array<number | null> = Array(values.length).fill(null);
  if (values.length < span) return result;

  let previous = values.slice(0, span).reduce((sum, value) => sum + value, 0) / span;
  result[span - 1] = previous;
  const alpha = 2 / (span + 1);
  for (let index = span; index < values.length; index += 1) {
    previous += alpha * (values[index] - previous);
    result[index] = previous;
  }
  return result;
}

export function macd(
  values: readonly number[],
  fastSpan = 12,
  slowSpan = 26,
  signalSpan = 9,
): MACDPoint[] {
  validateSpan("fastSpan", fastSpan);
  validateSpan("slowSpan", slowSpan);
  validateSpan("signalSpan", signalSpan);
  if (fastSpan >= slowSpan) {
    throw new RangeError("fastSpan must be smaller than slowSpan");
  }
  values.forEach((value, index) => {
    if (!Number.isFinite(value)) {
      throw new TypeError(`values[${index}] must be a finite number`);
    }
  });

  const fast = ema(values, fastSpan);
  const slow = ema(values, slowSpan);
  const macdValues = values.map((_, index) => {
    const fastValue = fast[index];
    const slowValue = slow[index];
    return fastValue === null || slowValue === null ? null : fastValue - slowValue;
  });
  const compactMacd = macdValues.filter((value): value is number => value !== null);
  const compactSignal = ema(compactMacd, signalSpan);
  const signal: Array<number | null> = Array(values.length).fill(null);
  const firstMacdIndex = slowSpan - 1;
  compactSignal.forEach((value, index) => {
    signal[firstMacdIndex + index] = value;
  });

  return values.map((value, index) => {
    const macdValue = macdValues[index];
    const signalValue = signal[index];
    const histogram =
      macdValue === null || signalValue === null ? null : macdValue - signalValue;
    const status: MACDStatus =
      macdValue === null
        ? "warming_price_emas"
        : signalValue === null
          ? "warming_signal"
          : "ready";
    return {
      index,
      value,
      fastEma: fast[index],
      slowEma: slow[index],
      macd: macdValue,
      signal: signalValue,
      histogram,
      status,
    };
  });
}
