/**
 * MACD: Read the Spreads Before You Read the Signals
 *
 * Topic D07-F02-A01 · Technical Indicators / Trend Systems · difficulty 2
 * Shape: series-transform · entry: macd()
 * Article: https://thefintechbuilder.com/technical-indicators/trend-systems/macd/
 * Repo:    https://github.com/IslamBaraka90/Fintech-MACD-Moving-Average-Convergence-Divergence-algorithm
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F02-A01-macd
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { macd as run } from "./impl.ts";

export const meta = {
  id: "D07-F02-A01",
  title: "MACD: Read the Spreads Before You Read the Signals",
  slug: "macd",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F02",
  family: "Trend Systems",
  difficulty: 2,
  archetype: "series-transform",
  entry: "macd",
  path: "technical-indicators/trend-systems/macd",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/trend-systems/macd/",
  repoUrl: "https://github.com/IslamBaraka90/Fintech-MACD-Moving-Average-Convergence-Divergence-algorithm",
} as const;
