/**
 * Log Loss
 *
 * Topic D40-F05-A04 · Model Validation and Backtesting / Classification and Score Validation · difficulty 2
 * Shape: record-transform · entry: logLoss()
 * Article: https://thefintechbuilder.com/model-validation-and-backtesting/classification-and-score-validation/log-loss/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D40-F05-A04-log-loss
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { logLoss as run } from "./impl.ts";

export const meta = {
  id: "D40-F05-A04",
  title: "Log Loss",
  slug: "log-loss",
  domainId: "D40",
  domain: "Model Validation and Backtesting",
  familyId: "D40-F05",
  family: "Classification and Score Validation",
  difficulty: 2,
  archetype: "record-transform",
  entry: "logLoss",
  path: "model-validation-and-backtesting/classification-and-score-validation/log-loss",
  articleUrl: "https://thefintechbuilder.com/model-validation-and-backtesting/classification-and-score-validation/log-loss/",
  repoUrl: null,
} as const;
