/**
 * Awesome Oscillator
 *
 * Topic D07-F03-A13 · Technical Indicators / Momentum · difficulty 2
 * Shape: series-transform · entry: awesomeOscillator()
 * Article: https://thefintechbuilder.com/technical-indicators/momentum/awesome-oscillator/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F03-A13-awesome-oscillator
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { awesomeOscillator as run } from "./impl.ts";

export const meta = {
  id: "D07-F03-A13",
  title: "Awesome Oscillator",
  slug: "awesome-oscillator",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F03",
  family: "Momentum",
  difficulty: 2,
  archetype: "series-transform",
  entry: "awesomeOscillator",
  path: "technical-indicators/momentum/awesome-oscillator",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/momentum/awesome-oscillator/",
  repoUrl: null,
} as const;
