/**
 * Stock-Split/Consolidation EPS Restatement
 *
 * Topic D46-F01-A05 · Earnings and Per-Share Analytics / Earnings and Share Foundations · difficulty 3
 * Shape: record-transform · entry: restateEpsForCapitalEvents()
 * Article: https://thefintechbuilder.com/earnings-and-per-share-analytics/earnings-and-share-foundations/stock-split-consolidation-eps-restatement/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D46-F01-A05-stock-split-consolidation-eps-restatement
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { restateEpsForCapitalEvents as run } from "./impl.ts";

export const meta = {
  id: "D46-F01-A05",
  title: "Stock-Split/Consolidation EPS Restatement",
  slug: "stock-split-consolidation-eps-restatement",
  domainId: "D46",
  domain: "Earnings and Per-Share Analytics",
  familyId: "D46-F01",
  family: "Earnings and Share Foundations",
  difficulty: 3,
  archetype: "record-transform",
  entry: "restateEpsForCapitalEvents",
  path: "earnings-and-per-share-analytics/earnings-and-share-foundations/stock-split-consolidation-eps-restatement",
  articleUrl: "https://thefintechbuilder.com/earnings-and-per-share-analytics/earnings-and-share-foundations/stock-split-consolidation-eps-restatement/",
  repoUrl: null,
} as const;
