// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D18-fundamental-analysis-and-valuation/D18-F02-intrinsic-valuation/D18-F02-A04-residual-income-model/implementations/typescript/intrinsic-valuation.ts
// Re-run `npm run sync` after changing the catalog implementation.
//
// This family shares one implementation across its topics; the body lives at
// src/_shared/intrinsic-valuation.ts and is re-exported here so the public surface of
// this subpath is unchanged.

export * from "../../../_shared/intrinsic-valuation.ts";
