// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D09-statistical-time-series/D09-F02-forecast-models/D09-F02-A04-sarima-sarimax/implementations/typescript/sarimax.ts
// Re-run `npm run sync` after changing the catalog implementation.


type ForecastResult = {
  forecast:number[];
  fitted:(number|null)[];
  residuals?:number[];
  state:Record<string,unknown>;
  [key:string]:unknown;
};
const finite=(value:number,name:string)=>{
  if(typeof value!=="number"||!Number.isFinite(value))throw new Error(`${name} must be finite`);
  return value;
};
const positiveInt=(value:number,name:string,min=1)=>{
  if(!Number.isInteger(value)||value<min)throw new Error(`${name} must be an integer >= ${min}`);
  return value;
};
const series=(values:number[],minimum=2)=>{
  if(!Array.isArray(values)||values.length<minimum)throw new Error(`values must contain at least ${minimum} observations`);
  return values.map((value,index)=>finite(value,`values[${index}]`));
};
const coefficients=(values:number[],name:string,allowEmpty=true)=>{
  if(!Array.isArray(values)||(!allowEmpty&&values.length===0))throw new Error(`${name} must be a coefficient list`);
  return values.map((value,index)=>finite(value,`${name}[${index}]`));
};

function armaCore(values:number[],ar:number[],ma:number[],intercept:number,horizon:number):ForecastResult{
  const a=coefficients(ar,"ar"),m=coefficients(ma,"ma");
  if(a.length===0&&m.length===0)throw new Error("at least one AR or MA coefficient is required");
  const p=a.length,q=m.length,y=series(values,Math.max(p+2,q+2,3)),c=finite(intercept,"intercept"),H=positiveInt(horizon,"horizon");
  const fitted:(number|null)[]=Array(y.length).fill(null),residuals:number[]=Array(y.length).fill(0);
  for(let t=p;t<y.length;t++){
    let prediction=c;
    for(let lag=1;lag<=p;lag++)prediction+=a[lag-1]*y[t-lag];
    for(let lag=1;lag<=q;lag++)if(t-lag>=0)prediction+=m[lag-1]*residuals[t-lag];
    fitted[t]=prediction;residuals[t]=y[t]-prediction;
  }
  const extended=[...y],errors=[...residuals],forecast:number[]=[];
  for(let step=0;step<H;step++){
    const t=extended.length;let prediction=c;
    for(let lag=1;lag<=p;lag++)prediction+=a[lag-1]*extended[t-lag];
    for(let lag=1;lag<=q;lag++)if(t-lag>=0)prediction+=m[lag-1]*errors[t-lag];
    extended.push(prediction);errors.push(0);forecast.push(prediction);
  }
  return {forecast,fitted,residuals,state:{order:[p,q],last_values:y.slice(-Math.max(1,p)),last_residuals:residuals.slice(-Math.max(1,q)),presample_innovations:"zero",future_innovations:"zero conditional mean"}};
}

const poly=(left:number[],right:number[])=>{
  const result=Array(left.length+right.length-1).fill(0);
  left.forEach((a,i)=>right.forEach((b,j)=>result[i+j]+=a*b));return result;
};
const seasonalPoly=(values:number[],period:number,sign:number)=>{
  const result=Array(period*values.length+1).fill(0);result[0]=1;
  values.forEach((value,index)=>result[(index+1)*period]=sign*value);return result;
};
function combined(ar:number[],ma:number[],sar:number[],sma:number[],period:number){
  positiveInt(period,"period",2);
  const ap=poly([1,...coefficients(ar,"ar").map(v=>-v)],seasonalPoly(coefficients(sar,"seasonal_ar"),period,-1));
  const mp=poly([1,...coefficients(ma,"ma")],seasonalPoly(coefficients(sma,"seasonal_ma"),period,1));
  return {ar:ap.slice(1).map(v=>-v),ma:mp.slice(1)};
}
const dot=(row:number[],beta:number[])=>row.reduce((sum,value,index)=>sum+value*beta[index],0);
function validateRows(rows:number[][],width:number,name:string){
  if(!Array.isArray(rows))throw new Error(`${name} must be a list`);
  return rows.map((row,index)=>{
    if(!Array.isArray(row)||row.length!==width)throw new Error(`${name}[${index}] must contain ${width} values`);
    return row.map((value,column)=>finite(value,`${name}[${index}][${column}]`));
  });
}
function seasonalDifference(values:number[],d:number,D:number,period:number){
  if(![0,1].includes(d)||![0,1].includes(D))throw new Error("d and D must be 0 or 1");
  const result:number[]=[],start=d+D*period;
  for(let t=start;t<values.length;t++){
    if(d===0&&D===0)result.push(values[t]);
    else if(d===1&&D===0)result.push(values[t]-values[t-1]);
    else if(d===0&&D===1)result.push(values[t]-values[t-period]);
    else result.push(values[t]-values[t-1]-values[t-period]+values[t-period-1]);
  }
  return result;
}
function integrate(history:number[],forecast:number,d:number,D:number,period:number){
  if(d===0&&D===0)return forecast;
  if(d===1&&D===0)return forecast+history.at(-1)!;
  if(d===0&&D===1)return forecast+history.at(-period)!;
  return forecast+history.at(-1)!+history.at(-period)!-history.at(-period-1)!;
}
export function forecastSARIMAX(values:number[],exog:number[][],futureExog:number[][],beta:number[],ar:number[],ma:number[],seasonalAr:number[],seasonalMa:number[],intercept:number,differenceOrder:number,seasonalDifferenceOrder:number,period:number,horizon:number):ForecastResult{
  const y=series(values,period*2+4),b=coefficients(beta,"beta"),x=validateRows(exog,b.length,"exog"),xf=validateRows(futureExog,b.length,"future_exog"),H=positiveInt(horizon,"horizon");
  if(x.length!==y.length)throw new Error("exog must align one-for-one with values");
  if(xf.length!==H)throw new Error("future_exog must contain exactly horizon rows");
  const residualized=y.map((value,index)=>value-dot(x[index],b));
  const transformed=seasonalDifference(residualized,differenceOrder,seasonalDifferenceOrder,period);
  const c=combined(ar,ma,seasonalAr,seasonalMa,period),base=armaCore(transformed,c.ar,c.ma,intercept,H);
  const history=[...residualized],residualizedForecast:number[]=[],forecast:number[]=[];
  base.forecast.forEach((value,index)=>{const next=integrate(history,value,differenceOrder,seasonalDifferenceOrder,period);history.push(next);residualizedForecast.push(next);forecast.push(next+dot(xf[index],b));});
  return {...base,forecast,transformed_forecast:base.forecast,residualized_forecast:residualizedForecast,state:{...base.state,orders:{nonseasonal:[ar.length,differenceOrder,ma.length],seasonal:[seasonalAr.length,seasonalDifferenceOrder,seasonalMa.length,period]},combined_ar:c.ar,combined_ma:c.ma,beta:b}};
}
