// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F08-price-transforms/D07-F08-A04-average-price-transform/implementations/typescript/average_price_transform.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F08-A04: Average Price Transform. */
import { averagePriceTransform as nativeAveragePriceTransform, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F08-A04";
export const TITLE = "Average Price Transform";

export function averagePriceTransform(input: TopicInput): TopicResult {
  return nativeAveragePriceTransform(input);
}
