// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D01-market-data-engineering/D01-F01-bar-construction/D01-F01-A02-tick-bars/implementations/typescript/bars.ts
// Re-run `npm run sync` after changing the catalog implementation.

/**
 * Readable reference implementation for fixed-count tick bars.
 *
 * Input order is authoritative. Corrections/cancels, duplicate removal,
 * eligibility filtering, and equal-timestamp source sequencing happen upstream.
 */
export type Trade = {
  tradeId: string;
  timestamp: string;
  session: string;
  symbol: string;
  price: number;
  volume: number;
  currency: string;
};

export type TickBarConfig = {
  targetTicks: number;
  closePartial?: boolean;
};

export type TickBar = {
  barIndex: number;
  session: string;
  startTime: string;
  endTime: string;
  lastTradeTime: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  dollarValue: number;
  tickCount: number;
  firstTradeId: string;
  lastTradeId: string;
  closeReason: "threshold" | "session_end" | "stream_end";
};

const REQUIRED_FIELDS: (keyof Trade)[] = [
  "tradeId", "timestamp", "session", "symbol", "price", "volume", "currency",
];

function timestampMs(value: unknown): number {
  if (typeof value !== "string" || !value.endsWith("Z")) {
    throw new Error("timestamp must be an ISO-8601 UTC string ending in Z");
  }
  const parsed = Date.parse(value);
  if (!Number.isFinite(parsed)) throw new Error("timestamp must be valid ISO-8601");
  return parsed;
}

function positiveNumber(value: unknown, field: string): number {
  if (typeof value !== "number" || !Number.isFinite(value) || value <= 0) {
    throw new Error(`${field} must be a finite positive number`);
  }
  return value;
}

function validate(trades: Trade[], config: TickBarConfig): Required<TickBarConfig> {
  if (!Array.isArray(trades)) throw new Error("trades must be an array");
  if (!config || typeof config !== "object") throw new Error("config must be an object");
  if (!Number.isInteger(config.targetTicks) || config.targetTicks <= 0) {
    throw new Error("targetTicks must be a positive integer");
  }
  const closePartial = config.closePartial ?? true;
  if (typeof closePartial !== "boolean") throw new Error("closePartial must be boolean");

  const ids = new Set<string>();
  const closedSessions = new Set<string>();
  let previousTime = -Infinity;
  let currentSession: string | null = null;
  let symbol: string | null = null;
  let currency: string | null = null;

  for (const trade of trades) {
    if (!trade || typeof trade !== "object" || REQUIRED_FIELDS.some(field => !(field in trade))) {
      throw new Error("trade is missing a required field");
    }
    for (const field of ["tradeId", "session", "symbol", "currency"] as const) {
      if (typeof trade[field] !== "string" || !trade[field].trim()) {
        throw new Error(`${field} must be a non-empty string`);
      }
    }

    const now = timestampMs(trade.timestamp);
    if (now < previousTime) throw new Error("trades must be globally chronological");
    previousTime = now;

    if (ids.has(trade.tradeId)) {
      throw new Error("tradeId must be unique after corrections and cancels");
    }
    ids.add(trade.tradeId);
    positiveNumber(trade.price, "price");
    positiveNumber(trade.volume, "volume");

    if (symbol === null) {
      symbol = trade.symbol;
      currency = trade.currency;
    } else if (trade.symbol !== symbol || trade.currency !== currency) {
      throw new Error("one symbol and one currency are required per call");
    }

    if (currentSession === null) {
      currentSession = trade.session;
    } else if (trade.session !== currentSession) {
      closedSessions.add(currentSession);
      currentSession = trade.session;
      if (closedSessions.has(currentSession)) {
        throw new Error("each session must occupy one contiguous input block");
      }
    }
  }

  return { targetTicks: config.targetTicks, closePartial };
}

function rounded(value: number): number {
  return Number(value.toFixed(8));
}

export function constructBars(trades: Trade[], config: TickBarConfig): TickBar[] {
  const { targetTicks, closePartial } = validate(trades, config);
  const result: TickBar[] = [];
  let current: Trade[] = [];
  let session: string | null = null;

  const emit = (reason: TickBar["closeReason"]): void => {
    if (current.length === 0) return;
    const prices = current.map(trade => trade.price);
    const volumes = current.map(trade => trade.volume);
    result.push({
      barIndex: result.length,
      session: current[0].session,
      startTime: current[0].timestamp,
      endTime: current.at(-1)!.timestamp,
      lastTradeTime: current.at(-1)!.timestamp,
      open: rounded(prices[0]),
      high: rounded(Math.max(...prices)),
      low: rounded(Math.min(...prices)),
      close: rounded(prices.at(-1)!),
      volume: rounded(volumes.reduce((total, value) => total + value, 0)),
      dollarValue: rounded(current.reduce(
        (total, trade) => total + trade.price * trade.volume, 0,
      )),
      tickCount: current.length,
      firstTradeId: current[0].tradeId,
      lastTradeId: current.at(-1)!.tradeId,
      closeReason: reason,
    });
    current = [];
  };

  for (const trade of trades) {
    if (session !== null && trade.session !== session) {
      if (closePartial) emit("session_end");
      else current = [];
    }
    session = trade.session;
    current.push(trade);

    // Each accepted record increments the count by one, so equality is exact.
    if (current.length === targetTicks) emit("threshold");
  }

  if (current.length > 0 && closePartial) emit("stream_end");
  return result;
}
