/**
 * Exponents, Roots, and Logarithms
 *
 * Topic D00-F01-A05 · Financial Mathematics, Statistics, and Data Foundations / Mathematical Language and Quantitative Reasoning · difficulty 1
 * Shape: record-transform · entry: exponentsRootsAndLogarithms()
 * Article: https://thefintechbuilder.com/foundations/mathematical-language-and-quantitative-reasoning/exponents-roots-and-logarithms/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F01-A05-powers-roots-logs
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { exponentsRootsAndLogarithms as run } from "./impl.ts";

export const meta = {
  id: "D00-F01-A05",
  title: "Exponents, Roots, and Logarithms",
  slug: "exponents-roots-and-logarithms",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F01",
  family: "Mathematical Language and Quantitative Reasoning",
  difficulty: 1,
  archetype: "record-transform",
  entry: "exponentsRootsAndLogarithms",
  path: "foundations/mathematical-language-and-quantitative-reasoning/exponents-roots-and-logarithms",
  articleUrl: "https://thefintechbuilder.com/foundations/mathematical-language-and-quantitative-reasoning/exponents-roots-and-logarithms/",
  repoUrl: null,
} as const;
