/**
 * Value at Risk Intuition
 *
 * Topic D00-F11-A05 · Financial Mathematics, Statistics, and Data Foundations / Financial Risk and Performance Statistics · difficulty 1
 * Shape: record-transform · entry: valueAtRiskIntuition()
 * Article: https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/financial-risk-and-performance-statistics/value-at-risk-intuition/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D00-F11-A05-value-at-risk
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { valueAtRiskIntuition as run } from "./impl.ts";

export const meta = {
  id: "D00-F11-A05",
  title: "Value at Risk Intuition",
  slug: "value-at-risk-intuition",
  domainId: "D00",
  domain: "Financial Mathematics, Statistics, and Data Foundations",
  familyId: "D00-F11",
  family: "Financial Risk and Performance Statistics",
  difficulty: 1,
  archetype: "record-transform",
  entry: "valueAtRiskIntuition",
  path: "financial-mathematics-statistics-and-data-foundations/financial-risk-and-performance-statistics/value-at-risk-intuition",
  articleUrl: "https://thefintechbuilder.com/financial-mathematics-statistics-and-data-foundations/financial-risk-and-performance-statistics/value-at-risk-intuition/",
  repoUrl: null,
} as const;
