/**
 * Negative Volume Index
 *
 * Topic D07-F05-A10 · Technical Indicators / Volume Indicators · difficulty 2
 * Shape: series-transform · entry: negativeVolumeIndex()
 * Article: https://thefintechbuilder.com/technical-indicators/volume-indicators/negative-volume-index/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F05-A10-negative-volume-index
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { negativeVolumeIndex as run } from "./impl.ts";

export const meta = {
  id: "D07-F05-A10",
  title: "Negative Volume Index",
  slug: "negative-volume-index",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F05",
  family: "Volume Indicators",
  difficulty: 2,
  archetype: "series-transform",
  entry: "negativeVolumeIndex",
  path: "technical-indicators/volume-indicators/negative-volume-index",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/volume-indicators/negative-volume-index/",
  repoUrl: null,
} as const;
