/**
 * Point-in-Time Availability Guard
 *
 * Topic D01-F04-A05 · Market Data Engineering / Data Quality · difficulty 3
 * Shape: snapshot-evaluate · entry: asOfSnapshot()
 * Article: https://thefintechbuilder.com/market-data-engineering/data-quality/point-in-time-availability-guard/
 * Repo:    https://github.com/IslamBaraka90/Fintech-Point-In-Time-Availability-Guard-Data-Quality-algorithm
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D01-F04-A05-point-in-time-availability-guard
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { asOfSnapshot as run } from "./impl.ts";

export const meta = {
  id: "D01-F04-A05",
  title: "Point-in-Time Availability Guard",
  slug: "point-in-time-availability-guard",
  domainId: "D01",
  domain: "Market Data Engineering",
  familyId: "D01-F04",
  family: "Data Quality",
  difficulty: 3,
  archetype: "snapshot-evaluate",
  entry: "asOfSnapshot",
  path: "market-data-engineering/data-quality/point-in-time-availability-guard",
  articleUrl: "https://thefintechbuilder.com/market-data-engineering/data-quality/point-in-time-availability-guard/",
  repoUrl: "https://github.com/IslamBaraka90/Fintech-Point-In-Time-Availability-Guard-Data-Quality-algorithm",
} as const;
