/**
 * Bharath-Shumway Naive Distance-to-Default
 *
 * Topic D21-F01-A07 · Credit Risk and Default / Probability of Default · difficulty 4
 * Shape: record-transform · entry: bharathShumwayNaiveDistanceToDefault()
 * Article: https://thefintechbuilder.com/credit-risk-and-default/probability-of-default/bharath-shumway-naive-distance-to-default/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D21-F01-A07-bharath-shumway-naive-distance-to-default
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { bharathShumwayNaiveDistanceToDefault as run } from "./impl.ts";

export const meta = {
  id: "D21-F01-A07",
  title: "Bharath-Shumway Naive Distance-to-Default",
  slug: "bharath-shumway-naive-distance-to-default",
  domainId: "D21",
  domain: "Credit Risk and Default",
  familyId: "D21-F01",
  family: "Probability of Default",
  difficulty: 4,
  archetype: "record-transform",
  entry: "bharathShumwayNaiveDistanceToDefault",
  path: "credit-risk-and-default/probability-of-default/bharath-shumway-naive-distance-to-default",
  articleUrl: "https://thefintechbuilder.com/credit-risk-and-default/probability-of-default/bharath-shumway-naive-distance-to-default/",
  repoUrl: null,
} as const;
