/**
 * Cardinality-Constrained Portfolio
 *
 * Topic D14-F04-A03 · Portfolio Construction / Practical Constraints · difficulty 4
 * Shape: record-transform · entry: optimizeCardinalityConstrained()
 * Article: https://thefintechbuilder.com/portfolio-construction/practical-constraints/cardinality-constrained-portfolio/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D14-F04-A03-cardinality-constrained-portfolio
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { optimizeCardinalityConstrained as run } from "./impl.ts";

export const meta = {
  id: "D14-F04-A03",
  title: "Cardinality-Constrained Portfolio",
  slug: "cardinality-constrained-portfolio",
  domainId: "D14",
  domain: "Portfolio Construction",
  familyId: "D14-F04",
  family: "Practical Constraints",
  difficulty: 4,
  archetype: "record-transform",
  entry: "optimizeCardinalityConstrained",
  path: "portfolio-construction/practical-constraints/cardinality-constrained-portfolio",
  articleUrl: "https://thefintechbuilder.com/portfolio-construction/practical-constraints/cardinality-constrained-portfolio/",
  repoUrl: null,
} as const;
