// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D07-technical-indicators/D07-F03-momentum/D07-F03-A19-fisher-transform/implementations/typescript/fisher_transform.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D07-F03-A19: Fisher Transform. */
import { fisherTransform as nativeFisherTransform, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D07-F03-A19";
export const TITLE = "Fisher Transform";

export function fisherTransform(input: TopicInput): TopicResult {
  return nativeFisherTransform(input);
}
