// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/D09-statistical-time-series/D09-F06-hilbert-and-ehlers-cycle-analytics/D09-F06-A05-hilbert-transform-trend-cycle-mode/implementations/typescript/hilbert_transform_trend_cycle_mode.ts
// Re-run `npm run sync` after changing the catalog implementation.

/** Dependency-free native TypeScript entry point for D09-F06-A05: Hilbert Transform Trend/Cycle Mode. */
import { hilbertTransformTrendCycleMode as nativeHilbertTransformTrendCycleMode, type TopicInput, type TopicResult } from "../../../_shared/referenceRuntime.ts";

export const TOPIC_ID = "D09-F06-A05";
export const TITLE = "Hilbert Transform Trend/Cycle Mode";

export function hilbertTransformTrendCycleMode(input: TopicInput): TopicResult {
  return nativeHilbertTransformTrendCycleMode(input);
}
