/**
 * Abandoned Baby
 *
 * Topic D06-F04-A07 · Price Action and Candlesticks / Multi-Candle Patterns · difficulty 5
 * Shape: record-transform · entry: abandonedBaby()
 * Article: https://thefintechbuilder.com/price-action-and-candlesticks/multi-candle-patterns/abandoned-baby/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D06-F04-A07-abandoned-baby
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { abandonedBaby as run } from "./impl.ts";

export const meta = {
  id: "D06-F04-A07",
  title: "Abandoned Baby",
  slug: "abandoned-baby",
  domainId: "D06",
  domain: "Price Action and Candlesticks",
  familyId: "D06-F04",
  family: "Multi-Candle Patterns",
  difficulty: 5,
  archetype: "record-transform",
  entry: "abandonedBaby",
  path: "price-action-and-candlesticks/multi-candle-patterns/abandoned-baby",
  articleUrl: "https://thefintechbuilder.com/price-action-and-candlesticks/multi-candle-patterns/abandoned-baby/",
  repoUrl: null,
} as const;
