/**
 * McClellan Volume Oscillator
 *
 * Topic D04-F02-A05 · Market Breadth and Internals / McClellan Family · difficulty 3
 * Shape: record-transform · entry: calculate()
 * Article: https://thefintechbuilder.com/market-breadth-and-internals/mcclellan-family/mcclellan-volume-oscillator/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D04-F02-A05-mcclellan-volume-oscillator
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { calculate as run } from "./impl.ts";

export const meta = {
  id: "D04-F02-A05",
  title: "McClellan Volume Oscillator",
  slug: "mcclellan-volume-oscillator",
  domainId: "D04",
  domain: "Market Breadth and Internals",
  familyId: "D04-F02",
  family: "McClellan Family",
  difficulty: 3,
  archetype: "record-transform",
  entry: "calculate",
  path: "market-breadth-and-internals/mcclellan-family/mcclellan-volume-oscillator",
  articleUrl: "https://thefintechbuilder.com/market-breadth-and-internals/mcclellan-family/mcclellan-volume-oscillator/",
  repoUrl: null,
} as const;
