/**
 * Percentage Volume Oscillator
 *
 * Topic D07-F05-A15 · Technical Indicators / Volume Indicators · difficulty 2
 * Shape: series-transform · entry: percentageVolumeOscillator()
 * Article: https://thefintechbuilder.com/technical-indicators/volume-indicators/percentage-volume-oscillator/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F05-A15-percentage-volume-oscillator
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { percentageVolumeOscillator as run } from "./impl.ts";

export const meta = {
  id: "D07-F05-A15",
  title: "Percentage Volume Oscillator",
  slug: "percentage-volume-oscillator",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F05",
  family: "Volume Indicators",
  difficulty: 2,
  archetype: "series-transform",
  entry: "percentageVolumeOscillator",
  path: "technical-indicators/volume-indicators/percentage-volume-oscillator",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/volume-indicators/percentage-volume-oscillator/",
  repoUrl: null,
} as const;
