/**
 * Tick-Imbalance Bars
 *
 * Topic D01-F01-A05 · Market Data Engineering / Bar Construction · difficulty 4
 * Shape: tape-aggregate · entry: constructBars()
 * Article: https://thefintechbuilder.com/market-data-engineering/bar-construction/tick-imbalance-bars/
 * Repo:    https://github.com/IslamBaraka90/Fintech-Tick-Imbalance-Bars-Bar-Construction-algorithm
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D01-F01-A05-tick-imbalance-bars
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { constructBars as run } from "./impl.ts";

export const meta = {
  id: "D01-F01-A05",
  title: "Tick-Imbalance Bars",
  slug: "tick-imbalance-bars",
  domainId: "D01",
  domain: "Market Data Engineering",
  familyId: "D01-F01",
  family: "Bar Construction",
  difficulty: 4,
  archetype: "tape-aggregate",
  entry: "constructBars",
  path: "market-data-engineering/bar-construction/tick-imbalance-bars",
  articleUrl: "https://thefintechbuilder.com/market-data-engineering/bar-construction/tick-imbalance-bars/",
  repoUrl: "https://github.com/IslamBaraka90/Fintech-Tick-Imbalance-Bars-Bar-Construction-algorithm",
} as const;
