/**
 * Schaff Trend Cycle
 *
 * Topic D07-F03-A21 · Technical Indicators / Momentum · difficulty 2
 * Shape: series-transform · entry: schaffTrendCycle()
 * Article: https://thefintechbuilder.com/technical-indicators/momentum/schaff-trend-cycle/
 */
// GENERATED by scripts/sync.mjs — do not edit.
// Source of truth: algorithms/domains/.../D07-F03-A21-schaff-trend-cycle
// Re-run `npm run sync` after changing the catalog implementation.

export * from "./impl.ts";
export { schaffTrendCycle as run } from "./impl.ts";

export const meta = {
  id: "D07-F03-A21",
  title: "Schaff Trend Cycle",
  slug: "schaff-trend-cycle",
  domainId: "D07",
  domain: "Technical Indicators",
  familyId: "D07-F03",
  family: "Momentum",
  difficulty: 2,
  archetype: "series-transform",
  entry: "schaffTrendCycle",
  path: "technical-indicators/momentum/schaff-trend-cycle",
  articleUrl: "https://thefintechbuilder.com/technical-indicators/momentum/schaff-trend-cycle/",
  repoUrl: null,
} as const;
